### ISSUE TITLE
adding HTTP/2 support for better result.

### ISSUE THREAD

**Issue by shankarj67** [scrapy/scrapy#2692] opened 2017-03-30 16:06 UTC
Now twisted supports only HTTP/0 or HTTP/1, Is there any way we can add hyper to integrate **scrapy** 
with HTTP/2.

**Comment by pawelmhm** [comment] 2017-04-04 12:58
closing as duplicate of https://github.com/scrapy/scrapy/issues/1854

**Closed by pawelmhm** 2017-04-04 12:58 UTC
