### ISSUE TITLE
Incompatible method call to SSL

### ISSUE THREAD

**Issue by nroose** [scrapy/scrapy#5636] opened 2022-09-26 19:23 UTC
### Description

Incompatible method call to SSL

### Steps to Reproduce

1. Run scrapy

**Expected behavior:** Loading the tls.py file doesn't crash.

**Actual behavior:** Loading the tls.py file crashes.

**Reproduces how often:** 100%

### Versions

Scrapy       : 2.5.1                                                                                                                                               
lxml         : 4.9.1.0                                                                                                                                             
libxml2      : 2.9.14                                                                                                                                              
cssselect    : 1.1.0                                                                                                                                               
parsel       : 1.6.0                                                                                                                                               
w3lib        : 2.0.1                                                                                                                                               
Twisted      : 22.8.0                                                                                                                                              
Python       : 3.9.14 (main, Sep  6 2022, 23:29:09) - [Clang 13.1.6 (clang-1316.0.21.2.5)]                                                                         
pyOpenSSL    : 22.1.0 (OpenSSL 3.0.5 5 Jul 2022)                                                                                                                   
cryptography : 38.0.1                                                                                                                                              
Platform     : macOS-12.6-x86_64-i386-64bit                                                                                                                        

### Additional context
  File "/Users/nroose/Library/Python/3.9/lib/python/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>                                             
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)                                                                                  
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'

**Comment by nroose** [comment] 2022-09-26 19:24
pyOpenSSL version 22.1.0 removes support for SSLv3. It was out 9/25.

**Comment by Gallaecio** [comment] 2022-09-26 19:41
Duplicate of https://github.com/scrapy/scrapy/issues/5635

**Closed by Gallaecio** 2022-09-26 19:41 UTC
