### ISSUE TITLE
Quoted url Location header fails to redirect

### ISSUE THREAD

**Issue by Tarliton** [scrapy/scrapy#2363] opened 2016-10-26 17:39 UTC
Hello,

I'm trying to crawl a website that returns a Location url in the header that is quoted. When that happens the downloadermiddleware_redirect fails to build the correct url.

This little test helps to explain:

``` python
    def test_quoted_location(self):
        req = Request('http://scrapytest.org/first')
        utf8_location = u'http%3A//scrapytest.org/ação'.encode('utf-8')  # header using quoted UTF-8 encoding
        resp = Response('http://scrapytest.org/first', headers={'Location': utf8_location}, status=302)
        req_result = self.mw.process_response(req, resp, self.spider)
        perc_encoded_utf8_url = 'http://scrapytest.org/a%C3%A7%C3%A3o'
        self.assertEquals(perc_encoded_utf8_url, req_result.url)
```

it fails:

``` python
===================================================================== FAILURES =====================================================================
___________________________________________________ RedirectMiddlewareTest.test_quoted_location ____________________________________________________

self = <tests.test_downloadermiddleware_redirect.RedirectMiddlewareTest testMethod=test_quoted_location>

    def test_quoted_location(self):
        req = Request('http://scrapytest.org/first')
        utf8_location = u'http%3A//scrapytest.org/ação'.encode('utf-8')  # header using UTF-8 encoding
        resp = Response('http://scrapytest.org/first', headers={'Location': utf8_location}, status=302)
        req_result = self.mw.process_response(req, resp, self.spider)
        perc_encoded_utf8_url = 'http://scrapytest.org/a%C3%A7%C3%A3o'
>       self.assertEquals(perc_encoded_utf8_url, req_result.url)
E       AssertionError: 'http://scrapytest.org/a%C3%A7%C3%A3o' != 'http://scrapytest.org/http%3A//scrapytest.org/a%C3%A7%C3%A3o'

/home/aurumdev/repos/scrapy/tests/test_downloadermiddleware_redirect.py:177: AssertionError
======================================================= 1 failed, 19 passed in 0.29 seconds ========================================================
```

The quoted url comes from the website.

Is that a bug?

Thank you

**Comment by redapple** [comment] 2016-10-26 18:11
Thanks for reporting @Tarliton .
What version of scrapy are you using?
(There was a fix in latest 1.2.1 about redirection and "Location" header decoding, but I tested with current master and it also fails)

So the website is returning something like this in the response headers?

```
Location: http%3A//scrapytest.org/a%C3%A7%C3%A3o
```
that is, it is quoting the ":" of the `http://` scheme?
That's odd, but maybe it happens in the wild.
Can you share the website so we can test how browsers behave? (in private if you want)

**Comment by Tarliton** [comment] 2016-10-26 18:27
I tested on 1.1.0 and 1.2.1, both fail.

Yes, that's exactly what happens in the response headers Location. The ":" is quoted.

The problem is:
In a previous request I have to send a url param called 'referer'.
Scrapy gets all the params from formdata FormRequest attibute and quote them all.
I want to mimic the website so I'm sending the same parameter (I don't want to make different requests, from the browser). Then the website gets that parameter 'referer' and uses as Location header value (this I'm deducing).
As the parameter was quoted, the server send it quoted as well.
And then scrapy fails to follow.

I don't want to expose the website, so I will send you an email.

Thanks!

**Comment by redapple** [comment] 2016-10-26 18:32
According to [RFC 7231, 7.1.2.  Location](https://tools.ietf.org/html/rfc7231#section-7.1.2)
> Location = URI-reference

And in [RFC 3986, 4.1 URI Reference](https://tools.ietf.org/html/rfc3986#section-4.1) 

> A URI-reference is either a URI or a relative reference.  If the URI-reference's prefix **does not match the syntax of a scheme followed by its colon separator**, then the URI-reference is a relative reference.

So, as I understand the specs, `Location: http%3A//scrapytest.org/a%C3%A7%C3%A3o` is supposed to be handled as a relative reference, hence the `http://scrapytest.org/http%3A//scrapytest.org/a%C3%A7%C3%A3o` result.

I'll wait for your email then.

**Comment by Tarliton** [comment] 2016-10-26 18:55
On Firefox the redirect don't work, but on Chrome it does.
Maybe Chrome is more permissive than Firefox when following those RFC rules.

Email sent.

**Comment by Tarliton** [comment] 2016-10-28 16:33
I was able to solve this with a workaround:
```python
import urlparse


class UnquoteUrlMiddleware(object):

    def __init__(self, crawler):
        self.crawler = crawler

    @classmethod
    def from_crawler(cls, crawler):
        if not crawler.settings.getbool('UNQUOTEURLMIDDLEWARE_ENABLED'):
            return

        ext = cls(crawler)
        return ext

    def process_response(self, request, response, spider):
        allowed_status = (301, 302, 303, 307)
        if 'Location' not in response.headers or response.status not in allowed_status:
            return response

        response.headers['location'] = urlparse.unquote(response.headers['location'])
        return response
```

It's not pretty but it does the job.

**Comment by redapple** [comment] 2016-11-02 16:51
@Tarliton , I'm closing this issue as you found a workaround for the server sending invalid referer values.

**Closed by redapple** 2016-11-02 16:51 UTC

**Comment by kmike** [comment] 2016-11-02 16:53
@redapple but browsers support this redirect somehow, right?

**Comment by redapple** [comment] 2016-11-02 16:55
@kmike , this needs to be checked.

**Comment by kmike** [comment] 2016-11-02 16:56
@Tarliton did redirect worked in a browser on a website you get this broken header from?

**Comment by Tarliton** [comment] 2016-11-02 17:01
@kmike The redirect works on Google Chrome, but fails on Firefox.

**Comment by redapple** [comment] 2016-11-02 17:06
I cannot reproduce the working redirect.

For example using `httpbin.org/redirect-to?url=` endpoint:
if I try to redirect to `http%3A//scrapytest.org/a%C3%A7%C3%A3o`,

```
>>> import urllib
>>> urllib.urlencode({"url": "http%3A//scrapytest.org/a%C3%A7%C3%A3o"})
'url=http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o'
```

I believe this is the correct URL for httpbin: `http://httpbin.org/redirect-to?url=http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o` ([link](http://httpbin.org/redirect-to?url=http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o))

And I get redirected to `http://httpbin.org/http%3A//scrapytest.org/a%C3%A7%C3%A3o` using Chrome.

Using curl, I believe the "Location" is the same as for that website used by @Tarliton 
but the redirect also fails, requesting `http://httpbin.org/http%3A//scrapytest.org/a%C3%A7%C3%A3o`

```
$ curl -L -v http://httpbin.org/redirect-to?url=http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o
*   Trying 23.22.14.18...
* Connected to httpbin.org (23.22.14.18) port 80 (#0)
> GET /redirect-to?url=http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 FOUND
< Server: nginx
< Date: Wed, 02 Nov 2016 16:58:54 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Location: http%3A//scrapytest.org/a%C3%A7%C3%A3o
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
* Connection #0 to host httpbin.org left intact
* Issue another request to this URL: 'http://httpbin.org/http%3A//scrapytest.org/a%C3%A7%C3%A3o'
* Found bundle for host httpbin.org: 0x56311bc03f20 [can pipeline]
* Re-using existing connection! (#0) with host httpbin.org
* Connected to httpbin.org (23.22.14.18) port 80 (#0)
> GET /http%3A//scrapytest.org/a%C3%A7%C3%A3o HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 NOT FOUND
< Server: nginx
< Date: Wed, 02 Nov 2016 16:58:55 GMT
< Content-Type: text/html
< Content-Length: 233
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
* Connection #0 to host httpbin.org left intact
```

**Comment by Tarliton** [comment] 2016-11-02 17:35
sorry, I was wrong at the first post.
I used:
```python
urllib.quote('http://scrapytest.org/ação')
'http%3A//scrapytest.org/a%C3%A7%C3%A3o'
```

instead of:
```python
urllib.urlencode({'url':'http://scrapytest.org/ação'})
'url=http%3A%2F%2Fscrapytest.org%2Fa%C3%A7%C3%A3o'
```

this:
```
http%3A%2F%2Fscrapytest.org%2Fa%C3%A7%C3%A3o
```
is different than this:
```
http%253A%2F%2Fscrapytest.org%2Fa%25C3%25A7%25C3%25A3o
```
although, I still can't explain what's going on on that website.
