### ISSUE TITLE
[bug?] sending cookies with `cookies=` and `cookie in headers` and `'dont merge cookie' meta`

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3241] opened 2018-04-28 04:05 UTC
`fetch('https://httpbin.org/cookies/set?foo=bar', cookies={'foo1':'bar1'}, meta={'dont_merge_cookies': True}, headers={'Cookie':'foor2=bar2'})`

```
request.cookies
request.headers['cookie']
```
is:
{'foo1': 'bar1'}
b'foor2=bar2'

but `response.text`:
{\n  "cookies": {\n    "foor2": "bar2"\n  }\n}\n

shouldn't request.cookies been sent with the `fetch` request?

**Comment by wRAR** [comment] 2018-09-24 13:18
This is a duplicate of #2124, there is come discussion there.

**Closed** 2019-02-13 19:31 UTC
