### ISSUE TITLE
twisted error stack trace doesn't output when the spider is running in scrapyd

### ISSUE THREAD

**Issue by ksimple** [scrapy/scrapy#1964] opened 2016-05-02 12:32 UTC
The outputted log is something like the following text and no stack trace which makes diagnostic super hard.
2016-05-02 20:25:02 [twisted] CRITICAL: Unhandled error in Deferred:
2016-05-02 20:25:02 [twisted] CRITICAL:

I created a from_crawler method on spider and it runs successfully on local machine but failed on scrapyd. Finally I notice that the signature of from_crawler on scrapyd should be from_crawler(cls, crawler, **kwargs) since there is a _job parameter. This is the first hard thing to discover since the reference doesn't mention it.

But the diagnostic of this one is toooooooooooo hard since there is no stack trace in twisted log. I have to write my own log observer and use addObeserve to log it by myself and find the first issue.

So please check why the stack trace doesn't output to log. I downloaded the code but can't figure out by just reading the code, thanks.

**Comment by redapple** [comment] 2016-05-02 12:37
@ksimple , a few questions,
- what version of scrapy are you using locally?
- what version of scrapyd are you running?
- do you have a simple/minimal spider class reproducing the issue?

**Comment by ksimple** [comment] 2016-05-02 12:47
local Scrapy 1.0.5
remote Scrapy 1.2.0dev2 on docker image vimagick/scrapyd

spider
# -*- coding: utf-8 -*-
import scrapy


class ReproNologSpider(scrapy.Spider):
    name = "repro_nolog"
    allowed_domains = ["adhoc"]
    start_urls = (
        'http://www.google.com/',
    )

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler = crawler)

    def parse(self, response):
        pas

log on scrapyd, the ktwisted is the logger I wrote to grab the lost log
2016-05-02 12:45:41 [scrapy] INFO: Scrapy 1.2.0dev2 started (bot: adhoc)
2016-05-02 12:45:41 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'adhoc.spiders', 'FEED_URI': 'file:///var/lib/scrapyd/items/adhoc/repro_nolog/c60d94c8106311e6868e0242ac110003.jl', 'SPIDER_MODULES': ['adhoc.spiders'], 'BOT_NAME': 'adhoc', 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36', 'LOG_FILE': '/var/lib/scrapyd/logs/adhoc/repro_nolog/c60d94c8106311e6868e0242ac110003.log'}
2016-05-02 12:45:41 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-05-02 12:45:41 [ktwisted] CRITICAL: ()
2016-05-02 12:45:41 [twisted] CRITICAL: Unhandled error in Deferred:
2016-05-02 12:45:41 [ktwisted] CRITICAL: from_crawler() got an unexpected keyword argument '_job'  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)

2016-05-02 12:45:41 [twisted] CRITICAL:

**Comment by redapple** [comment] 2016-05-02 14:02
I'm getting the same with master scrapyd (1.1.0), and scrapy 1.0.5 (i.e. no running with Docker)

Nothing much in the logs:

```
2016-05-02 15:59:46 [scrapy] INFO: Scrapy 1.0.5 started (bot: scrapydnolog)
2016-05-02 15:59:46 [scrapy] INFO: Optional features available: ssl, http11
2016-05-02 15:59:46 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'scrapydnolog.spiders', 'SPIDER_MODULES': ['scrapydnolog.spiders'], 'LOG_FILE': 'logs/scrapydnolog/repro_nolog/1fcb54dc106e11e6af79e8e0b7a12154.log', 'BOT_NAME': 'scrapydnolog'}
2016-05-02 15:59:46 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2016-05-02 15:59:46 [twisted] CRITICAL: Unhandled error in Deferred:
2016-05-02 15:59:46 [twisted] CRITICAL: 
```

But something on the console:

```
$ scrapyd
2016-05-02 15:59:30+0200 [-] Log opened.
2016-05-02 15:59:30+0200 [-] twistd 15.5.0 (/home/paul/.virtualenvs/scrapyd/bin/python2 2.7.10) starting up.
2016-05-02 15:59:30+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-05-02 15:59:30+0200 [-] Site starting on 6800
2016-05-02 15:59:30+0200 [-] Starting factory <twisted.web.server.Site instance at 0x7f5b8c382518>
2016-05-02 15:59:30+0200 [Launcher] Scrapyd 1.1.0 started: max_proc=16, runner='scrapyd.runner'
2016-05-02 15:59:41+0200 [-] "127.0.0.1" - - [02/May/2016:13:59:39 +0000] "POST /addversion.json HTTP/1.1" 200 119 "-" "Python-urllib/2.7"
2016-05-02 15:59:44+0200 [-] "127.0.0.1" - - [02/May/2016:13:59:44 +0000] "POST /schedule.json HTTP/1.1" 200 98 "-" "curl/7.43.0"
2016-05-02 15:59:45+0200 [-] Process started:  project='scrapydnolog' spider='repro_nolog' job='1fcb54dc106e11e6af79e8e0b7a12154' pid=4452 log='logs/scrapydnolog/repro_nolog/1fcb54dc106e11e6af79e8e0b7a12154.log' items=None
2016-05-02 15:59:46+0200 [Launcher,4452/stderr] Unhandled error in Deferred:
2016-05-02 15:59:46+0200 [Launcher,4452/stderr] 
	
	Traceback (most recent call last):
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 150, in _run_command
	    cmd.run(args, opts)
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
	    self.crawler_process.crawl(spname, **opts.spargs)
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 153, in crawl
	    d = crawler.crawl(*args, **kwargs)
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 70, in crawl
	    self.spider = self._create_spider(*args, **kwargs)
	  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 80, in _create_spider
	    return self.spidercls.from_crawler(self, *args, **kwargs)
	exceptions.TypeError: from_crawler() got an unexpected keyword argument '_job'
2016-05-02 15:59:46+0200 [-] Process finished:  project='scrapydnolog' spider='repro_nolog' job='1fcb54dc106e11e6af79e8e0b7a12154' pid=4452 log='logs/scrapydnolog/repro_nolog/1fcb54dc106e11e6af79e8e0b7a12154.log' items=None
```

I believe this is more for scrapyd than scrapy

**Comment by redapple** [comment] 2016-05-02 14:21
hi @Digenis , do you know if this lost logs issues is already tracked? I could not find similar issue on [scrapy/scrapyd](https://github.com/scrapy/scrapyd/issues)

**Comment by ksimple** [comment] 2016-05-02 14:42
Another issue, the configure_logging is called after the settings.py is executed. Any exception or log in that file isn't tracked.

I added some code in settings.py since I need a place to do some static initialization such as adding  observe twisted log, but I can't find a proper place to write the code. Maybe you can point a new place to me, thanks.

**Comment by Digenis** [comment] 2016-05-04 09:48
Hi, sorry for the late reply.

This is a scrapy bug and there are many tickets about it.
#1646 is one.

`LOG_STDOUT = False` makes log messages disappear from logfiles
regardless if  they are running in scrapyd.
This has being going unnoticed since migrating to python logging
because without a logfile, the log also goes to stdout.
It looks like everything is going to the same stream
when looking at the console output only.

`LOG_STDOUT = True` on the other hand hides command output
when a logfile is set. Probably other error output too.

Optimally, stdout should always be copied to the log
(unless this log is already stdout).
I had my take on #1646 but didn't manage.
I'll try once more because I don't remember considering
the parenthesised clause above.

**Comment by Digenis** [comment] 2016-12-14 14:56
@ksimple, which version of twisted are you using?
(you can see this with scrapyd --version)
I recently noticed that on newer twisted versions
the traceback is logged as it should.
See https://github.com/scrapy/scrapy/pull/2450#issue-195544830

**Comment by redapple** [comment] 2017-08-23 15:53
> I recently noticed that on newer twisted versions
the traceback is logged as it should.

In the same vein, I cannot reproduce the missing error log in scrapyd's logfile with recent versions of scrapy, scrapyd and Twisted.
```
$ scrapy version -v
Scrapy    : 1.4.0
lxml      : 3.7.3.0
libxml2   : 2.9.4
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.17.0
Twisted   : 17.5.0
Python    : 2.7.10 (default, Oct 14 2015, 16:09:02) - [GCC 5.2.1 20151010]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.10.0-32-generic-x86_64-with-Ubuntu-17.04-zesty

scrapyd==1.2.0
```
I can properly see syntax errors in the log file:
```
2017-08-23 17:35:38 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.example.com> (referer: None)
2017-08-23 17:35:38 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.example.com> (referer: None)
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "build/bdist.linux-x86_64/egg/proj/spiders/syntaxerror.py", line 10, in parse
    passs
NameError: global name 'passs' is not defined
2017-08-23 17:35:38 [scrapy.core.engine] INFO: Closing spider (finished)
```
And also for `TypeError` with [same spider as above](https://github.com/scrapy/scrapy/issues/1964#issuecomment-216226003) in the log file:
```
2017-08-23 17:48:19 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: proj)
2017-08-23 17:48:19 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'proj.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['proj.spiders'], 'LOG_FILE': 'logs/proj/repro_nolog/7be26fe2881a11e7ba07e8e0b7a12154.log', 'BOT_NAME': 'proj'}
2017-08-23 17:48:20 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-08-23 17:48:20 [twisted] CRITICAL: Unhandled error in Deferred:
2017-08-23 17:48:20 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 95, in crawl
    six.reraise(*exc_info)
  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 76, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/home/paul/.virtualenvs/scrapyd/local/lib/python2.7/site-packages/scrapy/crawler.py", line 99, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
TypeError: from_crawler() got an unexpected keyword argument '_job'
```
In that `TypeError` case, though, I also saw a `stderr` line appearing in scrapyd's console output:
```
2017-08-23T17:48:19+0200 [-] Process started:  project='proj' spider='repro_nolog' job='7be26fe2881a11e7ba07e8e0b7a12154' pid=24874 log='logs/proj/repro_nolog/7be26fe2881a11e7ba07e8e0b7a12154.log' items=None
2017-08-23T17:48:20+0200 [Launcher,24874/stderr] Unhandled error in Deferred:
2017-08-23T17:48:20+0200 [-] Process finished:  project='proj' spider='repro_nolog' job='7be26fe2881a11e7ba07e8e0b7a12154' pid=24874 log='logs/proj/repro_nolog/7be26fe2881a11e7ba07e8e0b7a12154.log' items=None
201
```

If anyone else can confirm, that would be awesome.

**Comment by SirOggy** [comment] 2017-09-21 04:29
Yes I am getting the exact same error. I've tried many things and I keep ending up with the same issue, although a tutorial that I was following seemed to have the same code running fine.

Seemed to me like the issue was stemming from [Twisted], but after reinstalling, nothing changes...

Looking at the dates since modified, I doubt it would be because of a version change...
All I can do is speculate, what I want is a real answer to this issue. If there is a solutions somewhere out there I love to hear it.
Also, why is scrapy going through python2.7? Is it just because of all those things that were planted into it ages ago? They should really update python3 with everything that python2.7 has...

**Comment by Gallaecio** [comment] 2024-02-14 08:36
Closing based on https://github.com/scrapy/scrapy/issues/1964#issuecomment-324379947 and the lack of confirmation (https://github.com/scrapy/scrapy/issues/1964#issuecomment-331047983 does not seem to be answering the request for confirmation, might have used older versions).

**Closed by Gallaecio** 2024-02-14 08:36 UTC
Labels: logging
