### ISSUE TITLE
Scrapy.selector Enhancement Proposal

### ISSUE THREAD

**Issue by zwidny** [scrapy/scrapy#906] opened 2014-09-26 03:53 UTC
## Make scrapy.selector into a separate project.
When we're scraping web pages, the most common task you need to perform is to extract data from the HTML source. There are several libraries available to achieve this: **BeautifulSoup**,  **lxml**.
And although scrapy selectors are built over the lxml library, it is a better way to extract data from HTML source. In my opinion, people will prefer **selector** to **BeautifulSoup** and  **lxml** , if make the scrapy.selectors into a separate project,

**Comment by umrashrf** [comment] 2015-01-07 10:18
@dangra @kmike I'm interested to do it.

I think there are two steps to the PR.

- First step is to create a separate package with working selectors in its own repository at github.com/scrapy/selectors
I have successfully untied Selector code from Scrapy and have created separate package. I made some tests and It is working fine locally. I completely removed response caching from LxmlDocument in hope to implement it at Scrapy side.

- Second part is replacing Scrapy selectors with new library
Here I need to dig how to use new selectors with response object efficiently having same kind of caching.

**Comment by Digenis** [comment] 2015-01-27 14:02
I don't like the idea of copy-pasting the selectors code to another
repository. All the code history disappears. I'd even prefer forking
the scrapy repository it self and start from there, instead of creating
a partial copy of the current state of a subdirectoy.

**Comment by umrashrf** [comment] 2015-01-27 14:32
@Digenis good point. I will test this with temporary selectors repo and see how it goes.

**Comment by kmike** [comment] 2015-01-27 14:34
It may be possible to move just one folder without forking the repo; I haven't tried it, but something like http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/ may work.

**Comment by Digenis** [comment] 2015-01-27 15:02
I do occasionally play with such things.
Of course we will not end up with a "honest" history
and it will take several filter-branch commands to get there.

I hope I don't make it seem complicated
but I am suggesting that since we are rewriting history
we should keep a meta-history of how we rewrote it.

I think the deliverables of this milestone should not be just the new repository
but also a list of git commands or a small shell script that create it (reproducible result).

We should be able on an empty repo to add and fetch scrapy as a remote
and after checking out some specific reference, run this list of commands
to create the individual repo.

That way we can see the actions we take to strip-down scrapy to the selectors.
Otherwise we are left only with the final result of each individual attempt to rewrite,
with no way to frame the changes (we will not have diffs to read)
and have something we can understand and comment on.

**Comment by umrashrf** [comment] 2015-01-28 16:03
@Digenis I understand filter-branch will only bring in history to some extent. So the advantage of using your approach over filter-branch is that people get to see where did Selectors repo come from right? If I fork Scrapy and cut it short to Selectors then it answers that question.

> We should be able on an empty repo to add and fetch scrapy as a remote
and after checking out some specific reference, run this list of commands
to create the individual repo.

Why is that required? Why would someone like to do that if there already exists Selectors repo?

**Comment by Digenis** [comment] 2015-01-28 16:55
I probably got to much into details towards the end.
I only argue about showing what you did to separate the selectors.
Of course people will know where the repo comes from.

I wanted to say that once you fork and start rewriting history,
you will be updating all the references and your work on it
will not be visible as in a typical version control workflow.
I expect this to be interesting enough to be exposed.
eg: by publishing the commands you ran to achieve this.

**Comment by dangra** [comment] 2015-01-28 16:59
I second @Digenis on this, I splitted several repositories in the past and it never was in a single pass so I found the best way is to write a script (bash) to rerun on each debug iteration.

Once you wrote the script it is simple to make it public.

**Comment by umrashrf** [comment] 2015-01-28 17:39
I can create a script. First I will see how it pans out with my commits over Scrapy's history. It's just now that I realized what's actually the hardest part :)

**Comment by umrashrf** [comment] 2015-02-12 15:16
Just to update you guys, I have spend some time with git-filter-branch and git-subtree and it seems to me git-filter-branch is the way to go. 

You can see a working script which extracts selector and related modules from scrapy into separate branch. https://gist.github.com/umrashrf/2f090797bdc25857325b

It's still work in progress as I have to apply my changes on it to make selectors reusable. I will soon update the PR.

**Comment by kmike** [comment] 2015-02-12 15:17
Great, thanks Umair!

**Comment by umrashrf** [comment] 2015-02-12 15:31
My pleasure @kmike

**Comment by nyov** [comment] 2015-02-27 16:04
Sorry to find this at such a late stage.
As to history filtering, in this instance I don't so much see the necessity to keep the history (duplicated) in a new repository after splitting Selector code.
The old history is still right here!
Put a link or reference in the new root commit to the scrapy commit it was filtered out of, maybe push a [git-replace](http://git-scm.com/blog/2010/03/17/replace.html) "graftpoint" as well, and be done with it.

Otherwise there is subtree filtering and manual tree grafting, but as noted before it wouldn't be an honest history, missing some files where code was moved to/from in the meantime or renamed.

**Comment by umrashrf** [comment] 2015-03-18 14:51
@nyov I think they are okay with history provided by git-filter-branch. They need the script for historical reasons. The script will be outdated for sure but at any point in future they can see how was it brought into existence.

**Comment by Digenis** [comment] 2015-03-18 15:09
No, not historical.

Each line of code exists to do something specific and hopefully understandable
but the trial and error process that made someone write spawns a longer story.

It often complements well, even "self-documenting" code.
Because one day you will end up reading something counter-intuitive
that can make you waste time figuring out "how"
instead of looking in the history and stopping in the "why".

To explain it in one sentence: "git blame gives you what you couldn't find in the code comments"

**Comment by umrashrf** [comment] 2015-03-18 15:29
So @Digenis are you happy with my current approach to split it? Can you leave your comments at https://github.com/scrapy/scrapy/pull/1007. I pushed script with patches so you can see https://github.com/umrashrf/scrapy/commit/dc6565d989a08756335dcbd514e369fd0a78c274.

**Comment by nyov** [comment] 2015-03-18 15:45
Hmm, I don't think you got my point. The `git blame` history of the project is still right [here](https://github.com/scrapy/scrapy/). With a `git-replace` ref "symlink" or pointer, the whole history of the newly detached project can be recovered by someone merging both project repositories locally (read the git-replace link I posted earlier).

But if you generate a custom, filtered, history to include into the new project, you _rewrote history_, thereby invalidating `git blame`'s usefulness. filter-branch doesn't trivially cover merges, meaningful commit information may get lost. Doing it "wrong", you'll also overwrite the real commit author and date information. (Ofc that's actually the right way, since you rewrote history.)
So by creating a new history this way, you instead make it harder for someone to get the correct, canonical history (besides publishing a duplicated but different history).

I'm just saying this from my experience from rewriting and grafting a lot of project histories together (from svn imports and what not), I believe the `filter-branch` approach is the wrong one here instead of the `git-replace` approach.
OTOH if everyone else agrees on filter-branch, understanding these points I raised, don't let me stop you from going down that road.

**Comment by umrashrf** [comment] 2015-03-19 13:03
I think you make good points @nyov. I will play with git-replace over the weekend.

@Digenis @dangra @kmike what do you think about this approach?

**Comment by Digenis** [comment] 2015-03-19 18:43
I think nyov's made a better suggestion.
I said "history", at some point, then "filter-branch" and didn't think further.
Indeed it would be more convenient if nyov saw this earlier.

Still I find your script interesting and something I would refer to next time I 'll be doing complicated filter-branch sequences.

**Comment by umrashrf** [comment] 2015-03-29 10:57
Guys how this history looks like? :sunglasses: https://github.com/umrashrf/selectors/commits/selectors-20150329

FYI Added two custom references (ROOT for selectors and SCRAPY_HEAD for scrapy commit from where it was detached). There are instructions in root commit as how to bring back full history.

**Comment by nyov** [comment] 2015-03-29 15:30
Oooh, lot's of work there :) Nice and clean history.

If I may say, you could drop the whole rewriting and your current root commit.
That's only taking up git-object space from now until forever, when you're deleting most of the files in the next commit anyway.
After someone adds the git-replace ref, the root commit disappears from history, so it could be an empty commit -- I would take your 2nd commit instead, where you cleaned up (`removed scrapy stuff but kept selectors stuff`) as root.

And where you have `git replace ROOT SCRAPY_HEAD` in the commit message, we need actual SHA1 refs, where `ROOT` is the new root commit (obviously) and `SCRAPY_HEAD` must be the point in time where you took the code from scrapy. (Ideally that would be last commit before selectors get removed from the scrapy repo.) Just pointing people at scrapy's `HEAD` won't work, as master will keep changing after the split, and they'll have to guess at what point in time those histories matched.

Maybe write something fancy for the new root commit:
```
Selectors are dead, long live Selectors

This project been split out of scrapy
(https://github.com/scrapy/scrapy).

To resolve the full history in your local copy,
first fetch the remaining history:

	git remote add scrapy git@github.com:scrapy/scrapy.git
	git fetch scrapy

Then add this git-replace ref:

	git replace dafd9f 0c7482
```

And thanks for all the work.

**Comment by umrashrf** [comment] 2015-03-29 16:38
> If I may say, you could drop the whole rewriting and your current root commit.
That's only taking up git-object space from now until forever, when you're deleting most of the files in the next commit anyway.
After someone adds the git-replace ref, the root commit disappears from history, so it could be an empty commit -- I would take your 2nd commit instead, where you cleaned up (removed scrapy stuff but kept selectors stuff) as root.

Are you suggesting something like this?

```
mkdir selectors
pushd selectors 
git init
git commit --allow-emtpy -m "born out of scrapy/scrapy"
popd
cp -r scrapy/* selectors/
```

> And where you have git replace ROOT SCRAPY_HEAD in the commit message, we need actual SHA1 refs, where ROOT is the new root commit (obviously) and SCRAPY_HEAD must be the point in time where you took the code from scrapy. (Ideally that would be last commit before selectors get removed from the scrapy repo.) Just pointing people at scrapy's HEAD won't work, as master will keep changing after the split, and they'll have to guess at what point in time those histories matched.

You're right about SCRAPY_HEAD as it's confusing. I also thought of SCRAPY_TIP but it doesn't sound good also. I am out of ideas for the name :( I had actual SHA there before but I think it is not good for people who don't know about git-replace and naming them gives a hint before looking at the commit itself.

Thanks for the bad-ass commit message!

**Comment by nyov** [comment] 2015-03-29 17:47
@umrashrf, I lost you there on IRC.

This is how I thought it could look like:
https://github.com/nyov/selectors/commits/master

**Comment by umrashrf** [comment] 2015-03-29 18:00
thanks @nyov, it makes sense. My concern was if git-replace will handle the moves like `scrapy/selector/ -> selectors/` and `scrapy/utils -> selectors/utils` without having parent commit. I need to test this and will update the repo shortly.

**Comment by nyov** [comment] 2015-03-29 18:08
Well best don't move the files around in the first two commits.
That makes it cleaner in the history.
But git itself doesn't care, it will show the files as "moved" if they look similar by a certain percentage. Otherwise it will show them as "removed" and "added".
It's not preserved in git history if a file was moved, git doesn't care where the parent commit came from.

**Comment by umrashrf** [comment] 2015-03-29 18:19
I just realized it must not be a problem because if git-diff can do it so can git-replace. If it was the other way around ("removed" and "added") then git-blame would be affected.

**Comment by umrashrf** [comment] 2015-03-29 20:02
@nyov review it when you can https://github.com/umrashrf/selectors/commits/selectors

**Comment by nyov** [comment] 2015-03-29 21:04
This looks good to me!

Now looking at the commits, your new `README.md` should probably be an .rst file, scrapy projects aren't using markdown anywhere else that I know of.

And just maybe you can squash some of these commits,
```
0e5f9d2 added selectors specific python package files
46e7c32 added selectors readme
e00e6a0 removed unnecessary lines from .gitignore
```
could probably all go together. Though I don't want to be nit-picking here.

**Comment by umrashrf** [comment] 2015-03-30 14:07
>Now looking at the commits, your new README.md should probably be an .rst file, scrapy projects aren't using markdown anywhere else that I know of.

Makes sense. I'd migrate to markdown later.

>And just maybe you can squash some of these commits,

I think atomic commits are better. Can you suggest a commit message?

**Comment by nyov** [comment] 2015-03-30 15:18
> Can you suggest a commit message?

Something like "set up Selectors project environment" maybe.

**Comment by umrashrf** [comment] 2015-04-02 11:02
@nyov done those changes. Now only docs are pending.

**Comment by kmike** [comment] 2015-04-02 13:25
Sorry, I don't understand all this git woodoo :) But in https://github.com/umrashrf/selectors/tree/master it is possible to check the history of each file using github interface - it shows all relevant commits, "blame" [works](https://github.com/umrashrf/selectors/blame/master/selectors/unified.py). In "selectors" branch it doesn't [work](https://github.com/umrashrf/selectors/blame/selectors/selectors/unified.py).

**Comment by kmike** [comment] 2015-04-02 13:26
Why should we require users to "set up Selectors project environment"?

**Comment by nyov** [comment] 2015-04-02 14:21
wait, what?
oh no no no, "set up Selectors project environment" was meant as a commit message, not some user instruction. Could also be "shuffling some files around and adding a new README".

**Comment by kmike** [comment] 2015-04-02 15:12
Sorry, I was unclear: why should we require developers who want to use git blame or git history to set up Selectors project environment?

**Comment by nyov** [comment] 2015-04-02 16:30
@kmike, I don't really like to write this again, it already feels like I was pushing for this choice, which wasn't my intent. I wasn't thinking about github's blame not working with this choice.

My reason for suggesting git replace is that I think it keeps the history here clean and honest.
If we include a copy of a rewritten history here, it's a partial duplicate to scrapy's and potentially not quite right (from dropping files in the rewrite).

In summary, if scrapy.git would be rewritten afterwards to remove selectors history, moving it here would feel right, to me. Since it isn't and scrapy.git is sticking around for the foreseeable future, where you can look it up, duplicating some mangled history (other sha1 sums, commit messages not quite fitting since files are missing from commits) felt not quite right, to me.

That is my opinion, which I hoped to explain, nothing else. Feel free to disagree and whatever works best for everyone else is good enough for me.

**Comment by umrashrf** [comment] 2015-04-04 17:51
> Sorry, I don't understand all this git voodoo :) But in https://github.com/umrashrf/selectors/tree/master it is possible to check the history of each file using github interface - it shows all relevant commits, "blame" works. In "selectors" branch it doesn't work.

@kmike what about creating a separate branch at Selectors repo with full history? I mean the result of git-replace. Call that separate branch **history** or anything.

**Comment by kmike** [comment] 2015-04-04 19:28
> My reason for suggesting git replace is that I think it keeps the history here clean and honest.
If we include a copy of a rewritten history here, it's a partial duplicate to scrapy's and potentially not quite right (from dropping files in the rewrite).

> In summary, if scrapy.git would be rewritten afterwards to remove selectors history, moving it here would feel right, to me. Since it isn't and scrapy.git is sticking around for the foreseeable future, where you can look it up, duplicating some mangled history (other sha1 sums, commit messages not quite fitting since files are missing from commits) felt not quite right, to me.

What practical problems are caused by unclean dishonest duplicated history, changed sha1 sums and not-quite-fitting commit messages? Unfitting commit messages may cause some confusion, but IMHO they are better than nothing. Having full history can save some time on tracking the code changes, allow people to use github UI and local git without any setup, it also preserves contribution history.

> @kmike what about creating a separate branch at Selectors repo with full history? I mean the result of git-replace. Call that separate branch history or anything.

I think that a separate branch won't help much once we start making more changes to selectors; one can always use Scrapy repository to see old changes.

**Comment by umrashrf** [comment] 2015-04-04 19:39
> I think that a separate branch won't help much once we start making more changes to selectors; one can always use Scrapy repository to see old changes.

Yes we can write a script which can update that separate branch. The advantage is it gives full selectors history in github UI.

**Comment by kmike** [comment] 2015-04-04 19:56
> Yes we can write a script which can update that separate branch. The advantage is it gives full selectors history in github UI. 

This adds complexity and thus makes maintenance harder. It is better to agree on one of the options, be it "drop history before relocation, but provide instructions on how to get it back" or "provide pseudo-history".

Sorry, I still don't get what is clean about dropping the history and why do you like it :) As @Digenis said, "git blame gives you what you couldn't find in the code comments", and pseudo-history gives you a meaningful git blame - it is a practical advantage. There must be something, because it seems so far there is +2 or +3 ( @umrashrf, @nyov and @Digenis?) for dropping pseudo-history vs +1 (me) for providing it.

**Comment by umrashrf** [comment] 2015-04-04 20:20
> Sorry, I still don't get what is clean about dropping the history and why do you like it :)

I don't like dropping the history and neither do they. git-filter-branch has a good chance to break git-blame usefulness by giving you partial history. I also wondered how and talked this through with @nyov on IRC so I'm just going to paste them here. I was going to paste it before but sorry I got lost in other stuff.

```
nyov: well, assume at some point parts of the file were moved there from a different file. if you run filter-branch, and removing that other file, the source is lost
nyov: or if the file was renamed in the past, but you keep only one filename through the rewrite.
nyov: or, well, look at the history here: https://github.com/umrashrf/selectors/commits/master
nyov: all the commits now have you as the Committer, meaning the historical commit date is lost - not much use for git blame, right?
nyov: it's not so bad if the original Author was the commiter, too. but if they were different that information is lost
nyov: anyway. I see your reason for wanting to keep the history there. I'm very much for not losing history, myself.
nyov: It would make more sense if you rewrite scrapy.git at the same time, removing all references to selectors, ergo splitting repositories. But since this is a duplicate history, I just felt it more a waste of space to keep a modified history as well
```

So based on these points what do you think @kmike?

**Comment by nyov** [comment] 2015-04-04 20:32
ah, that stupid irc log. :p 

@kmike, I disagree on "it also preserves contribution history", at least commit author and dates are overwritten. But count me as +/-0. Both approaches have dis/advantages, I'm not sure which to favor anymore in this case.

**Comment by dangra** [comment] 2015-04-04 20:33
Hi guys, let's draw a hard line stating clear **we are not rewriting Scrapy history** by any chance :)

As for selectors repostory history, I +1 to provide pseudo history and make it clear that the project was part of Scrapy and the exact history can only be found there.

**Comment by nyov** [comment] 2015-04-04 20:38
(AN: the same decision is now open for the new `scrapy-djangoitems` project)

**Comment by dangra** [comment] 2015-04-04 20:38
IMO the pseudo history should retain commit dates and authors

**Comment by nyov** [comment] 2015-04-04 20:44
That's not trivially possible with `git filter-branch` (design decision being: it's been changed by someone, it should state as much). But it can certainly be hacked somehow.

**Comment by kmike** [comment] 2015-04-06 15:04
> I disagree on "it also preserves contribution history", at least commit author and dates are overwritten.

@nyov https://github.com/umrashrf/selectors/commits/master shows right authors and original commit dates ("authored on"), while preserving information about the fact Umair made these commits; https://github.com/umrashrf/selectors/graphs/contributors displays correct contributors and graphs with original ("authored on") commit dates. My git foo is weak, but author/commiter and "authored on"/ "commited on" distinction sounds right, and github supports it well enough.

**Comment by nyov** [comment] 2015-04-06 16:52
Diffing two exerpts from the original log (`git log -- scrapy/selector/`) and the rewritten repo (`git log`), this is the information that changed.

Note how for example the last commit by Paul was authored in November but only actually committed (or amended) in January, and then merged by Pablo some time later.
The merge commit is dropped completely, the actual commit date by Paul is now the rewrite date of Umair. The actual author information is the only one staying intact.
This is what I mean by losing commit author and date information. If we don't care about this secondary info here, that's fine by me.

```diff
$ diff -up original.log rewritten.log 
--- original.log	2015-04-06 16:35:53.987149100 +0000
+++ rewritten.log	2015-04-06 16:36:07.083113844 +0000
@@ -1,59 +1,48 @@
-commit 1f184ed7bf5cd32fb2b19bf42d4260d81d4d1cdd
+commit 931c737b760b034ee122ad70db56abcf6c9eff60
 Author:     Paul Tremberth <paul.tremberth@gmail.com>
 AuthorDate: Wed Jan 15 15:17:18 2014 +0100
-Commit:     Paul Tremberth <paul.tremberth@gmail.com>
-CommitDate: Fri Jan 17 20:33:32 2014 +0100
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     Disable smart strings in lxml XPath evaluations
 
-commit 71ada5476e5b81d9f42e607d5bc0b7e2baa8ef93
-Merge: b9bb9be 827c0cf
-Author:     Pablo Hoffman <pablo@scrapinghub.com>
-AuthorDate: Thu Jan 16 06:32:05 2014 -0800
-Commit:     Pablo Hoffman <pablo@scrapinghub.com>
-CommitDate: Thu Jan 16 06:32:05 2014 -0800
-
-    Merge pull request #472 from redapple/exslt
-    
-    Register EXSLT namespaces by default (resolves #470)
-
-commit b3be6e210de837c54fc50cf62fc9e34a504c705e
+commit f533dd51f000a10ffe9606c20331499cabee3e54
 Author:     Daniel Graña <dangra@gmail.com>
 AuthorDate: Fri Jan 3 17:32:40 2014 -0200
-Commit:     Daniel Graña <dangra@gmail.com>
-CommitDate: Thu Jan 16 09:53:59 2014 -0200
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     warn XPathSelector deprecation on subclassing and direct instance
 
-commit 827c0cf51f47ab87b1de1c517ee7d5095fdb9c32
+commit 1902ec2ab677e12d6f096337df4bd187ef593838
 Author:     Paul Tremberth <paul.tremberth@gmail.com>
 AuthorDate: Wed Jan 15 15:00:25 2014 +0100
-Commit:     Paul Tremberth <paul.tremberth@gmail.com>
-CommitDate: Wed Jan 15 15:00:25 2014 +0100
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     Rename "regexp" prefix to "re"
 
-commit a3eba68aca804e67f9a083c4d9c490da9a243b59
+commit 09ff763d410a3825ddfb6e7cf2c63a8d1781484a
 Author:     Paul Tremberth <paul.tremberth@gmail.com>
 AuthorDate: Wed Jan 15 12:28:25 2014 +0100
-Commit:     Paul Tremberth <paul.tremberth@gmail.com>
-CommitDate: Wed Jan 15 12:28:25 2014 +0100
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     Drop EXSLT strings and math extensions
 
-commit 5df56a975884ed0680283ff6e301f8a4d32f4712
+commit 754663d3a29a6dfdc2fbd3c982dc68f3192bb703
 Author:     Paul Tremberth <paul.tremberth@gmail.com>
 AuthorDate: Wed Jan 8 18:48:20 2014 +0100
-Commit:     Paul Tremberth <paul.tremberth@gmail.com>
-CommitDate: Tue Jan 14 12:49:17 2014 +0100
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     Applying suggestions from previous comments
 
-commit d46534cc547b4da79f9b47b4ccec40a16f1ca3c2
+commit 97e2405a0d61797885fd3cc90b390eb4be630930
 Author:     Paul Tremberth <paul.tremberth@gmail.com>
 AuthorDate: Sun Nov 24 04:41:14 2013 +0100
-Commit:     Paul Tremberth <paul.tremberth@gmail.com>
-CommitDate: Tue Jan 14 12:49:17 2014 +0100
+Commit:     Umair Ashraf <umr.ashrf@gmail.com>
+CommitDate: Wed Mar 18 15:49:24 2015 +0500
 
     Register EXSLT namespaces by default (resolves #470)
 
```

**Comment by nyov** [comment] 2015-04-07 16:57
Let me put the lid on this discussion. It seems I sowed dissent by making my viewpoint known here. For that I am sorry, I shall try to wrap it up.
If taken as a precedent case, this currently looks like a blocker for the `selectors`, `scrapyd-client` and upcoming `scrapy-djangoitem` repos and that is bad. @dangra put his foot down, @kmike agrees, I'll follow. I converted @Digenis and @umrashrf ;) I guess, but I assume they'll follow, too?

@dangra also said to keep commiter stuff (and merges too). That's currently not the case here as I showed, but is possible. That makes part of my argument invalid, so let's do this.
[`scrapy-jsonrpc`](https://github.com/scrapy/scrapy-jsonrpc) seems the actual precedent case with included history (I hadn't noticed before), and it looks like dangra [handled it then](https://github.com/scrapy/scrapy-jsonrpc/commit/d3d2abecd489968a7aba38410ac067a2d7307689), in a way that kept merges and committer information AFAICS.

It's possible using the index filter, my apologies for saying it wouldn't be that trivial -- I must have lost some gitfoo myself. It's only hard to figure out all the right files to keep.
@umrashrf, I feel bad for all the work you did already, if I should pitch in, let me know!
Here's a quick way to kill everything _but_ the files you want to keep, but it requires listing all the possible paths that those files are on, in history (renames and moves included).
```sh
FILES="all the files/to/keep"
git filter-branch -d /tmp/gfb \
	--prune-empty \
	--tag-name-filter cat \
	--index-filter 'git rm --ignore-unmatch --cached -qr -- . && git reset -q $GIT_COMMIT -- '"$FILES" \
	-- --all
```
The inverse, eradicating the listed files from history, can be done like this:
```sh
FILES="all the files/to/kill"
git filter-branch -d /tmp/gfb \
	--prune-empty \
	--tag-name-filter cat \
	--index-filter 'git ls-files -z | grep -z '"$FILES"' | xargs -0 git rm -qr --cached --ignore-unmatch DummyWhichNeverExists' \
	-- --all
```
Using both in tandem, and maybe repeatedly, it's possible to whittle down the tree and commits to only the stuff to keep.

**Comment by umrashrf** [comment] 2015-04-07 17:33
@nyov no no, i'm glad to do it. thanks for teaching me more git!

**Comment by kmike** [comment] 2015-08-12 00:33
Fixed by https://github.com/scrapy/parsel and https://github.com/scrapy/scrapy/pull/1409. Thanks to all people involved!

**Closed by kmike** 2015-08-12 00:33 UTC

**Comment by Digenis** [comment] 2015-08-26 11:19
Are selector tickets being moved from scrapy to parsel?

**Comment by kmike** [comment] 2015-08-26 18:21
@Digenis some of them should, but there is still scrapy.Selector which wraps parsel.Selector. Do you have specific tickets in mind?

**Comment by Digenis** [comment] 2015-08-26 19:06
I don't have specific issues in mind, I am just reminding.
A quick search shows issues #753 #842 #765.
Pull requests will probably require more work than copying the tickets.

**Comment by kmike** [comment] 2015-08-26 19:20
Yeah, we should revisit the tickets, thanks for the reminder.
