### ISSUE TITLE
install scrapy failed on Mac OS X Yosemite

### ISSUE THREAD

**Issue by linus-young** [scrapy/scrapy#1126] opened 2015-04-01 13:17 UTC
I run `pip install scrapy`, and it only gives me the error: 

![screen shot 2015-04-01 at 9 01 34 pm](https://cloud.githubusercontent.com/assets/2557461/6941420/6aebc342-d8b2-11e4-9f6a-b1549981b424.png)

then I realized there is something wrong with `cryptography`, then I found this would be helpful: [Install Cryptography using your own openssl on os x](https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-os-x)

Accroding to the link above, I run the following command:
```
$ brew install openssl
$ env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" pip install cryptography
$ pip install scrapy
```

Then I successfully installed scrapy. 
I  don't know whether it's common for OS X users, if so, I think maybe the installation guide could be more specific for OS X. 

System: OS X Yosemite 10.10.2
Python : 2.7.9

**Comment by MojoJolo** [comment] 2015-07-01 08:43
I also experienced this error. I think this is more of an issue in `cryptography` installation than `scrapy`.

**Comment by MojoJolo** [comment] 2015-07-09 07:05
@linus-young can you provide an update? How's the installation going?

**Comment by curita** [comment] 2015-07-10 09:32
I'm thinking this could be a duplicate of #1342, the trace shows an error in `six` and the only additional dependency in OS X for `cryptography` is `xcode-select`. Not having it gives a pretty descriptive message:
```bash
    ...
    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
    error: command 'clang' failed with exit status 1
```
in any of the libraries that compile things.

@linus-young @MojoJolo could you test if the workaround mentioned in that issue (Here: https://github.com/scrapy/scrapy/issues/1342#issuecomment-120312583, basically running `export PYTHONPATH="/Library/Python/2.7/site-packages"` in your terminal) helps in solving the problem?

**Comment by MojoJolo** [comment] 2015-07-13 14:13
@curita I tried installing Scrapy in a virtualenv and all works well without a problem. All the dependencies are installed properly.

We haven't heard from @linus-young lately. I wonder if he successfully installed Scrapy.

**Comment by curita** [comment] 2015-07-13 14:26
Installing it in a virtualenv should fix the issue too since it automatically changes `$PYTHONPATH`, I'm going to write about that alternative in #1350 later.

> I wonder if he successfully installed Scrapy.

@linus-young said in the issue description:
> Then I successfully installed scrapy.

So no need to press the matter further I think, there are a couple of available workarounds already but I want to close this particular issue and related once the installation docs address the problem.

**Comment by linus-young** [comment] 2015-07-24 09:13
@MojoJolo Sorry mate, I‘ve been busy in taking courses these day. How's it going? Have you solved the problem?

**Comment by MojoJolo** [comment] 2015-07-27 05:18
Looks like it. Check out @curita's reply.

@curita, is it possible to close this already?

**Closed** 2015-08-07 02:07 UTC

**Comment by Trangle91** [comment] 2019-12-11 23:30
Thanks. It's very helpful!
