### ISSUE TITLE
Here is Missing Documentation for Windows

### ISSUE THREAD

**Issue by neosin** [scrapy/scrapy#4938] opened 2020-12-23 03:03 UTC
## Summary

Add to Documentation for windows users that MS VS C++ Dev Bundle required before installing Scrapy.

## Motivation

Experienced issue initially installing scrapy so installed MS VS C++ and second install try worked.
Looked in Scrapy installation documentation for windows and found no reference to this requirement.

**Comment by wRAR** [comment] 2020-12-23 08:39
Duplicate of https://github.com/scrapy/scrapy/issues/4715

**Closed by wRAR** 2020-12-23 08:39 UTC
