### ISSUE TITLE
No module named 'twisted'

### ISSUE THREAD

**Issue by Marsqueenlyy** [scrapy/scrapy#4301] opened 2020-02-05 03:13 UTC
when i import scrapy, it runs like 'Traceback (most recent call last):
  File "E:/python practicing/爬虫/l0205_crawler1.py", line 1, in <module>
    import scrapy
  File "E:\新建文件夹\Python\lib\site-packages\scrapy\__init__.py", line 27, in <module>
    from scrapy import _monkeypatches
  File "E:\新建文件夹\Python\lib\site-packages\scrapy\_monkeypatches.py", line 6, in <module>
    import twisted.persisted.styles  # NOQA
ModuleNotFoundError: No module named 'twisted''
  why?...
  and i downloaded the resourse code from github,  removed this package direclly to ‘\Python\Lib\site-packages’，cause i cant 'pip install' it ,with the same problems related to 'twisted'

**Comment by elacuesta** [comment] 2020-02-05 03:17
Seems like you're running Windows. Have you followed the [Windows installation notes](https://docs.scrapy.org/en/latest/intro/install.html#windows)?

**Comment by Marsqueenlyy** [comment] 2020-02-05 03:23
> Seems like you're running Windows. Have you followed the [Windows installation notes](https://docs.scrapy.org/en/latest/intro/install.html#windows)?

ok i'll check it

**Comment by elacuesta** [comment] 2020-02-05 15:43
Closing since it seems to be caused by not following the installation instructions. Please feel free to reopen if the issue persists.

**Closed by elacuesta** 2020-02-05 15:43 UTC
Labels: Windows, install
