### ISSUE TITLE
Error while using  signals.spider_opened and signals.spider_closed in pipeline.py

### ISSUE THREAD

**Issue by pradhanvickey** [scrapy/scrapy#4315] opened 2020-02-06 20:17 UTC
HI, I am trying to implement below but getting error. Kindly help:-

```python
import pymongo
from scrapy import signals

class MongoPipeline(object):

    collection_name = 'scrapy_items'

    def __init__(self, mongo_uri, mongo_db,crawler):
        self.mongo_uri = mongo_uri
        self.mongo_db = mongo_db
        self.crawler = crawler
        crawler.signals.connect(self.open_spider, signals.spider_opened)
        crawler.signals.connect(self.close_spider, signals.spider_closed)

    @classmethod
    def from_crawler(cls, crawler):
        return cls(
            mongo_uri=crawler.settings.get('MONGO_URI'),
            mongo_db=crawler.settings.get('MONGO_DATABASE', 'items'),
            crawler = crawler
        )

    def open_spider(self, spider):
        self.client = pymongo.MongoClient(self.mongo_uri)
        self.db = self.client[self.mongo_db]

    def close_spider(self, spider,reason):
        self.client.close()

    def process_item(self, item, spider):
        self.db[self.collection_name].insert_one(dict(item))
        return item
```

**Error:**
```
yield self.engine.open_spider(self.spider, start_requests)
TypeError: open_spider() missing 1 required positional argument: 'start_requests'

During handling of the above exception, another exception occurred:

current.result = callback(current.result, *args, **kw)
TypeError: close_spider() missing 1 required positional argument: 'reason'
```
(edited for syntax highlighting)

**Comment by elacuesta** [comment] 2020-02-06 21:17
The [`open_spider` and `close_spider`](https://docs.scrapy.org/en/1.8/topics/item-pipeline.html#writing-your-own-item-pipeline) methods of item pipelines are invoked internally, without relation to signals (see https://github.com/scrapy/scrapy/blob/1.8.0/scrapy/core/scraper.py#L81and https://github.com/scrapy/scrapy/blob/1.8.0/scrapy/core/scraper.py#L87). The second error is produced my a mismatch in the amount of arguments in the calling code and  your defined function, you could solve it by renaming the signal handler. I couldn't reproduce the first error, I think the reason might be in the spider code.

That said, this doesn't seem to be a problem with Scrapy itself so I'm closing the issue. Please use [the `scrapy` tag at StackOverflow](https://stackoverflow.com/questions/tagged/scrapy), see also [Getting help](https://docs.scrapy.org/en/latest/index.html#getting-help).

**Closed by elacuesta** 2020-02-06 21:17 UTC
