### ISSUE TITLE
New Instance of scrapy.Request

### ISSUE THREAD

**Issue by gdomod** [scrapy/scrapy#1987] opened 2016-05-12 14:13 UTC
Hi there,

i want to scraps a board with different users.

i create a subclass from Request but 
`class Test(scrapy.Request):
    def __init__(self, *args, **kwargs):
        super(Test, self).__init__(*args, **kwargs)`

But i didnt get new instance from Request Object, so there i always got same cookies etc.

Can anybody help me please

**Comment by redapple** [comment] 2016-05-12 14:18
@gdomod , by default, `CookieMiddleware` will share the same session for all requests.

If you want to emulate parallel (cookie) sessions, [check the `cookiejar` key in `meta` dict](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html?#multiple-cookie-sessions-per-spider) that you can pass to `Request` instances.

Note the comment on passing the cookiejar key explicitly in subsequent requests:

> Keep in mind that the cookiejar meta key is not “sticky”. You need to keep passing it along on subsequent requests.

**Comment by kmike** [comment] 2016-05-16 11:38
I agree that cookies API can be confusing; it can be improved. If you have ideas feel free to weight in at https://github.com/scrapy/scrapy/issues/1878.

But this feature works as intended, so I'm closing this ticket.

**Closed by kmike** 2016-05-16 11:38 UTC
