### ISSUE TITLE
ERROR:scrapy.core.scraper:Error downloading

### ISSUE THREAD

**Issue by vnmani1** [scrapy/scrapy#3431] opened 2018-09-26 04:33 UTC
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
ValueError: invalid hostname: advisors-dev-mra-2333_profile_update.swarm.cxawsnprd.massmutual.com
ERROR:scrapy.core.scraper:Error downloading <GET https://advisors-dev-mra-2333_profile_update.swarm.cxawsnprd.massmutual.com/shealyn-mcgaffey>

Scrapy    : 1.3.0
lxml      : 4.2.5.0
libxml2   : 2.9.8
cssselect : 1.0.3
parsel    : 1.5.0
w3lib     : 1.19.0
Twisted   : 18.7.0
Python    : 2.7.15rc1 (default, Apr 15 2018, 21:51:34) - [GCC 7.3.0]
pyOpenSSL : 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018)

**Comment by wRAR** [comment] 2018-09-26 06:35
Duplicate of #3321.

**Closed** 2018-10-04 07:14 UTC

**Comment by uyplayer** [comment] 2019-04-02 11:48
i have the same problom ;how can i solve this problom ?

**Comment by Gallaecio** [comment] 2019-04-02 18:37
@uyplayer  There’s not much you can do. To follow progress on fixing this issue, follow the open item #3321.

**Comment by ppp0099s1z** [comment] 2022-11-15 11:29
2022-11-14 20:51:18 [scrapy.core.scraper] ERROR: Error downloading <GET http://antispider7.scrape.center/api/book/?limit=18@offset=9180>
Traceback (most recent call last):
  File "e:\newsproject\venv\lib\site-packages\scrapy\core\downloader\middleware.py", line 41, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "e:\newsproject\venv\lib\site-packages\twisted\internet\defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "E:\scrapy-text\scrapycompositdome\scrapycompositdome\middlewares.py", line 16, in process_request
    response = await client.get(self.accountpool_url)
  File "e:\newsproject\venv\lib\site-packages\aiohttp\client.py", line 467, in _request
    with timer:
  File "e:\newsproject\venv\lib\site-packages\aiohttp\helpers.py", line 700, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
