### ISSUE TITLE
testing implementation

### ISSUE THREAD

**Issue by luisotaviocap98** [scrapy/scrapy#5140] opened 2021-05-10 02:35 UTC
Hello everybody. In a previous issue #5109, @Gallaecio reported that, as a contribution option for a beginner, it would be to make test codes. However, to do tests you need to have knowledge about the structure / architecture of the software. I currently participate in an academic project at the university, where one of my goals is to make a contribution to a free software project. So, I would like to know if it is possible for someone to help / teach me about Scrapy's test codes and if there are any untested modules that are possibly easy to implement your tests.

**Comment by Gallaecio** [comment] 2021-05-10 07:57
> I would like to know […] about Scrapy's test codes

https://docs.scrapy.org/en/latest/contributing.html#tests covers how to run tests. Feel free to suggest improvements.

> I would like to know if […] there are any untested modules that are possibly easy to implement your tests.

You can browse test coverage by file at https://codecov.io/gh/scrapy/scrapy/tree/master/scrapy. But I’m not sure what would be the easiest. You could start with components (spider middlewares, downloader middlewares, and item pipelines) that already have tests but not full coverage.

**Comment by luisotaviocap98** [comment] 2021-05-11 02:22
OK thanks @Gallaecio. Is there any documentation or tutorial on creating test codes? I couldn't understand them, for me, they are not as intuitive as the tests in javascript

**Comment by Gallaecio** [comment] 2021-05-11 07:29
We use mostly standard Python for tests, so the main documentation would be https://docs.python.org/3/library/unittest.html

Beyond that, we do use Twisted’s `unittests` for some tests that need it, but the API should be mostly that of https://docs.python.org/3/library/unittest.html. And we do use https://pytest.org/ features in some cases, but only those compatible with https://docs.python.org/3/library/unittest.html.

If you are already familiar with https://docs.python.org/3/library/unittest.html, and the problem is something else, it would be great if you could be more explicit about what you find confusing, with specific examples.

**Comment by luisotaviocap98** [comment] 2021-05-11 23:54
I am not familiar with python testing. I never got to do tests in javascript, nor in python, but when comparing examples in javascript and the tests created for Scrapy, considering those of javascript more readable.
For example, on the website [codecov](https://codecov.io/gh/scrapy/scrapy/src/master/scrapy/commands/check.py) it says that line 23 is covered, but line 25 is not. I wanted to understand how to know which line is covered or not. Looking at the files [check](https://github.com/scrapy/scrapy/blob/master/scrapy/commands/check.py) and [test_command_check](https://github.com/scrapy/scrapy/blob/master/tests/test_command_check.py), I can't understand where a line/function is being tested.
If you can explain about the tests of [check](https://github.com/scrapy/scrapy/blob/master/tests/test_command_check.py), or the [httpcompression](https://github.com/scrapy/scrapy/blob/ee682af3b06d48815dbdaa27c1177b94aaf679e1/tests/test_downloadermiddleware_httpcompression.py) tests, which is what you suggested that I finish the implementation, I would be very grateful.

**Comment by wRAR** [comment] 2021-05-12 06:55
Tests execute code, they don't test specific lines directly, and most functions aren't tested directly either. In examples like yours the  condition is never successful during tests, because the situation when it is successful never happens, so improving coverage here would require writing a test that reproduces such situation (if it's possible to reproduce it). The same or similar can be said about most other lines not covered by tests.

**Comment by Gallaecio** [comment] 2021-07-14 10:27
Closing since there is no specific issue to be addressed here.

**Closed by Gallaecio** 2021-07-14 10:27 UTC
