### ISSUE TITLE
Page not found!!! """http://doc.scrapy.org/_static/selectors-sample1.html""""

### ISSUE THREAD

**Issue by omi10859** [scrapy/scrapy#2979] opened 2017-10-27 04:33 UTC
Example page under <strong>Using selectors with XPath</strong> link taken for example  "(http://doc.scrapy.org/_static/selectors-sample1.html)" is not working

**Comment by djunzu** [comment] 2017-10-27 14:52
@omi10859 I opened docs for [latest](https://doc.scrapy.org/en/latest/topics/selectors.html), [1.4](https://doc.scrapy.org/en/1.4/topics/selectors.html), [1.3](https://doc.scrapy.org/en/1.3/topics/selectors.html). All three show the same link: http://doc.scrapy.org/en/latest/_static/selectors-sample1.html. This link is working (although you could say the page is broken because the three first image links do not work).

Where did you find this link? http://doc.scrapy.org/_static/selectors-sample1.html

**Comment by omi10859** [comment] 2017-10-28 08:24
OK!! Link is working when we click on the link but it doesn't when we copy paste it!!

**Comment by djunzu** [comment] 2017-10-28 19:03
> OK!! Link is working when we click on the link but it doesn't when we copy paste it!!

If it works one way, it should work the other way. And it does work both ways here. I think the problem is in your end. 
Note that the link you gave does not work, indeed. But the link in docs is slight different.

**Comment by kmike** [comment] 2017-10-31 10:18
I can't reproduce it as well, so I'm closing this ticket for now. Please reopen if you figure out how to make it reproduceable!

**Closed by kmike** 2017-10-31 10:18 UTC
