### ISSUE TITLE
ERROR: Unable to send mail: To=['wgm@163.com'] Cc=[] Subject="Scrapy Error Alarm" Attachs=0- object of type 'module' has no len()

### ISSUE THREAD

**Issue by pattywgm** [scrapy/scrapy#2966] opened 2017-10-18 09:57 UTC
I caught this error when I wanted to send email with scrapy.mail.MailSender.
[twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 995, in lineReceived
    why = self._okresponse(self.code, b'\n'.join(self.resp))
  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1044, in smtpState_to
    return self.smtpState_toOrData(0, b'')
  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1062, in smtpState_toOrData
    self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 179, in quoteaddr
    res = email.utils.parseaddr(addr)
  File "/usr/lib/python2.7/email/utils.py", line 214, in parseaddr
    addrs = _AddressList(addr).addresslist
  File "/usr/lib/python2.7/email/_parseaddr.py", line 457, in __init__
    self.addresslist = self.getaddrlist()
  File "/usr/lib/python2.7/email/_parseaddr.py", line 217, in getaddrlist
    while self.pos < len(self.field):
exceptions.TypeError: object of type 'module' has no len()

## But it was succeed in my own pc with scrapy 1.4.0 , twisted 13.1.0.

**Comment by cathalgarvey** [comment] 2018-02-16 15:27
Hi @pattywgm - Can you provide some example code that triggers this failure, please?

**Comment by cathalgarvey** [comment] 2018-02-21 15:30
Hi @pattywgm - I'm going to close this for now, but please feel free to re-open if you have more information for us. I've seen some other issues here regarding email that turned out to be related more to Twisted than to Scrapy, so I'm not sure whether the bug lies upstream, or not. Especially since your final note suggests that it works in the same Scrapy version, but with an older Twisted version.

Thanks for reporting it; please do come back to us here if you learn more about the cause!

**Closed by cathalgarvey** 2018-02-21 15:30 UTC
Labels: needs more info
