### ISSUE TITLE
Use PEP8

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3781] opened 2019-05-16 06:52 UTC
Scrapy docs recommends using PEP8 coding convention when writing code for inclusion in Scrapy, with the exception of 79 character line length rule . A quick run of `pep8` utility shows me that there are several occurrence of PEP8 violation in the master branch. If given the nod from the maintainers, I would like to work on resolving this.

**Comment by Gallaecio** [comment] 2019-05-16 08:27
I think this is a duplicate of #2144.

**Closed** 2019-05-17 12:37 UTC
