### ISSUE TITLE
User Warning: cookie lib bug!

### ISSUE THREAD

**Issue by gmeans** [scrapy/scrapy#1632] opened 2015-12-09 19:47 UTC
I've had a spider running pretty consistently for over a year now and just recently had the following error pop up:

```
UserWarning: cookielib bug!
    Traceback (most recent call last):
      File "/usr/lib/python2.7/cookielib.py", line 1582, in make_cookies
        parse_ns_headers(ns_hdrs), request)
      File "/usr/lib/python2.7/cookielib.py", line 485, in parse_ns_headers
        v = http2time(_strip_quotes(v))  # None if invalid
      File "/usr/lib/python2.7/cookielib.py", line 266, in http2time
        return _str2time(day, mon, yr, hr, min, sec, tz)
      File "/usr/lib/python2.7/cookielib.py", line 176, in _str2time
        t = _timegm((yr, mon, day, hr, min, sec, tz))
      File "/usr/lib/python2.7/cookielib.py", line 76, in _timegm
        return timegm(tt)
      File "/usr/lib/python2.7/calendar.py", line 613, in timegm
        days = datetime.date(year, month, 1).toordinal() - _EPOCH_ORD + day - 1
    ValueError: year is out of range
     [cookielib.py:1584]
```

The problem is that this error crashes the spider process completely. The spider is running within scrapyd.

Has anyone seen this before? I'm running Scrapy 0.24.4 on this instance due to an SSL issue that prevented me from upgrading.

**Comment by gmeans** [comment] 2015-12-09 20:19
Sorry I misspoke regarding the Scrapy version. We hadn't upgraded due to incompatibilities with Scrapy 1.x and Scrapyd.

**Comment by nramirezuy** [comment] 2015-12-09 20:47
@gmeans It would help to have code to reproduce the error.

**Comment by gmeans** [comment] 2015-12-09 22:41
@nramirezuy I apologize but I don't think I could offer up the code to reliably reproduce it. Its not even reliable within the spider. That stack trace was all I got out of the logs and we have an error callback on the request that handles all exceptions.

I couldn't even tell which URL caused it. 

I'm going to assume its within the Request object since its cookie lib and try catching exceptions there to see if I'm able to find where its occurring.

**Comment by Digenis** [comment] 2015-12-10 07:19
@gmeans, do you use a 32bit kernel?

**Comment by gmeans** [comment] 2015-12-10 12:46
@Digenis I don't believe so. This particular spider is running on an Elastic Beanstalk instance using Amazon Linux. It's running within a docker container using this image:

https://hub.docker.com/r/ceroic/scrapyd/~/dockerfile/

**Comment by Digenis** [comment] 2015-12-21 11:25
It depends on your environment configuration,
`SolutionStackName` should say what kernel architecture you are using.

It can be a python bug, duplicate or not.
See http://bugs.python.org/issue5537
If you are on 32bits, you should report your case there.
If not, I guess you should eventually file a new bug report.

The extend to which this concerns scrapy
is its `http.cookies` module which does no datetime fiddling
but don't close this issue yet. We'd rather know what's happening
and how to reproduce.

**Comment by cathalgarvey** [comment] 2018-02-15 16:23
Hi @Digenis - Any objection to closing this? It's now quite stale and marked non-reproducible since Sep. 2016, we can't get example source code, or a minimal example. It may have been fixed by accident, or it may never have been an issue with Scrapy per-se?

**Comment by Digenis** [comment] 2018-02-19 11:57
We never got a reply about the kernel.
I guess Paul tested it in a 32bit platform when he marked it.
Let's close the issue.

**Closed** 2018-02-20 11:55 UTC
Labels: not reproducible
