### ISSUE TITLE
Scrapy won't follow all Requests, generated by the overridden start_requests method

### ISSUE THREAD

**Issue by Chris8080** [scrapy/scrapy#4063] opened 2019-10-05 19:10 UTC
### Description

I've got a list of 109 URLs (in this test case - can be 200 or 500 or more, and the same issue persists) which is loaded correctly into a list of requests by the start_requests method and returned.

### Steps to Reproduce

1. run the spider

**Expected behavior:** [What you expect to happen]

The crawler should crawl (in this case due to `CONCURRENT_REQUESTS = 150` roughly 150 pages at the same time, create the folders and files.

**Actual behavior:** [What actually happens]

Up to ca. 70 folders are being created / 70 domains are being crawled before the spider eventually stops.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% in my actual spider and in this barebone example.

### Versions

Scrapy       : 1.7.3
lxml         : 4.3.3.0
libxml2      : 2.9.9
cssselect    : 1.0.3
parsel       : 1.5.1
w3lib        : 1.20.0
Twisted      : 19.2.0
Python       : 3.7.3 (default, Aug 20 2019, 17:04:43) - [GCC 8.3.0]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019)
cryptography : 2.6.1
Platform     : Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco

### Additional context

Following the settings.py and the spider.
Maybe I'm doing sth wrong or there is an issue somehow?

```python
# -*- coding: utf-8 -*-

BOT_NAME = 'crawlerscrapy'
SPIDER_MODULES = ['crawlerscrapy.spiders']
NEWSPIDER_MODULE = 'crawlerscrapy.spiders'
USER_AGENT_LIST = "useragents.txt"
ROBOTSTXT_OBEY = False
CONCURRENT_REQUESTS = 150
DOWNLOAD_DELAY = 13
CONCURRENT_REQUESTS_PER_DOMAIN = 1
COOKIES_ENABLED = False

DEFAULT_REQUEST_HEADERS = {
   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
   'Accept-Encoding':'gzip, deflate, sdch',
   'Connection':'keep-alive',
   'Cache-Control':'max-age=0',
   'Accept-Language': 'en',
}
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware':None,
    'random_useragent.RandomUserAgentMiddleware': 400
}
AUTOTHROTTLE_ENABLED = False

# http://doc.scrapy.org/en/latest/topics/broad-crawls.html
SCHEDULER_PRIORITY_QUEUE = 'scrapy.pqueues.DownloaderAwarePriorityQueue' # added for 3
REACTOR_THREADPOOL_MAXSIZE = 20 # added for 2
LOG_LEVEL = 'INFO'
DEPTH_LIMIT = 1
DOWNLOAD_TIMEOUT = 9
SCHEDULER_DEBUG = True
SCHEDULER_DISK_QUEUE = 'scrapy.squeues.PickleFifoDiskQueue'
SCHEDULER_MEMORY_QUEUE = 'scrapy.squeues.FifoMemoryQueue'
RETRY_TIMES = 1
AJAXCRAWL_ENABLED = True
```
```python
# -*- coding: utf-8 -*-
import scrapy
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule
from scrapy import Request

import logging
import sys
import os 
import os.path
from datetime import datetime

from urllib.parse import urlparse
from pathvalidate import sanitize_filename

'''
scrapy crawl spid -s JOBDIR=crawls/2019_09_18 --logfile=log/2019-09-18-complete.log
scrapy crawl spid --logfile=log/2019-10-05-complete.log
'''

class SpidSpider(CrawlSpider):
    name = 'spid'

    allowed_domains = []

    with open("urls.txt", "rt") as f:
        start_urls = [url.strip() for url in f.readlines()]
        allowed_domains = [url.strip() for url in f.readlines()]

    rules = (
        Rule(LinkExtractor(allow=()), callback='parse_item', follow=True),
    )
    
    def __init__(self, *a, **kw):
        super(CrawlSpider, self).__init__(*a, **kw)

    def start_requests(self):
        logging.log(logging.INFO, "======== Starting with start_requests")
        self._compile_rules()

        request_list = []
        line = 1
        for link in self.start_urls:
            o = urlparse(link)
            result = '{uri.netloc}'.format(uri=o)
            self.allowed_domains.append(result)
            logging.log(logging.INFO, "======== in For:")
            logging.log(logging.INFO, link)
            request_list.append ( Request(url=link, callback=self.parse) )
            line+=1 
        
        logging.log(logging.INFO, "======== Amount allowed Domains:")
        logging.log(logging.INFO, len(self.allowed_domains) )
        logging.log(logging.INFO, "======== Amount start URLs:")
        logging.log(logging.INFO, len(self.start_urls) )
        logging.log(logging.INFO, "======== Amount request list:")
        logging.log(logging.INFO, len(request_list) )
        logging.log(logging.INFO, "======== Finished with start_requests")
        
        return ( request_list )


    def parse_item(self, response):
        item = {}
        self.write_html_file ( response )
        return item


    def write_html_file (self, response):
        current_url = response.url
        orootdir = 'out/'

        title = response.xpath('//title/text()').get()
        
        o = urlparse(current_url)
        result = '{uri.netloc}'.format(uri=o)

        if '/de/' in current_url:
            current_url = (current_url.replace('/de/', '')).strip()
        if '/en/' in current_url:
            current_url = (current_url.replace('/en/', '')).strip()
        if current_url.endswith ( "/" ):
            current_url = current_url[:-1]

        page = current_url.split("/")[-1]
        self.check_path ( orootdir + '/' )
        self.check_path ( orootdir + '/' + result )
        
        filename = datetime.today().strftime('%Y-%m-%d') + '__' + title + '.html'
        filename = sanitize_filename ( filename ).replace(' ', '_').strip()
        
        pathfilename = orootdir + '/' + result + '/'
        pathfilename = pathfilename + filename
        
        self.logger.info("Filename to be generated: " + pathfilename)
        
        with open(pathfilename, 'wb') as f:
            f.write(response.body)


    def check_path ( self, path ):
        if not os.path.exists( path ):
            os.makedirs( path )

```

And a list of URLs - works with any.

**Comment by elacuesta** [comment] 2019-10-07 20:07
I cannot reproduce, please include a sample list of URLs and the resulting log file. That said, I suspect this is more of a question for the ["scrapy" tag at StackOverflow](https://stackoverflow.com/questions/tagged/scrapy)

Please note that if a site from the list only includes links to other domains (https://example.org, for instance), those requests will be filtered out by the [Offsite Spider Middleware](https://github.com/scrapy/scrapy/blob/1.7.3/scrapy/spidermiddlewares/offsite.py), and no response from the original domain will reach the `parse_item` callback, which is responsible for writing the HTML to disk.

**Comment by kmike** [comment] 2019-10-08 15:30
There is an issue with start_requests, I'm not sure it is the one you're getting though. Description: https://github.com/scrapy/scrapy/issues/456#issuecomment-247622571. A proposed fix: https://github.com/scrapy/scrapy/pull/3237 (it seems we're going to fix it in Scrapy 2.0 instead, for `async def start_requests`). There are some workarounds showed in the tickets.

**Comment by Chris8080** [comment] 2019-10-10 12:33
@kmike I've removed the start_requests completely for testing and generate all the start URLs in the init. The number is correct (I'm printing the number at the end of init()).
The amount of folders I get is right at the beginning 48 and then stays for a while at 48 - disregarding over 50 other domains. It seems like the same behaviour as with the start_requests method.

@elacuesta 
Please see the following (new) spider, the url list and a piece of the log file.
The log is at the INFO level, since I was hoping, that I've made an obvious mistake somewhere in the settings or similar and the experienced people here would spot it.
Let me know, whether I should provide the DEBUG log as well.

And I'll try it on Stackoverflow now.

The new spider:
`
    
    # -*- coding: utf-8 -*-
    import scrapy
    from scrapy.linkextractors import LinkExtractor
    from scrapy.spiders import CrawlSpider, Rule
    from scrapy import Request
    import logging
    import sys
    import os 
    import os.path
    from datetime import datetime
    from urllib.parse import urlparse
    from pathvalidate import sanitize_filename

    '''
    scrapy crawl spid -s JOBDIR=crawls/2019_09_18 --logfile=log/2019-09-18-complete.log
    scrapy crawl spid --logfile=log/2019-10-05-complete.log
    scrapy crawl spid --logfile=log/2019-10-10-complete.log
    '''

    class SpidSpider(CrawlSpider):
        name = 'spid'

        allowed_domains = []

        with open("urls.txt", "rt") as f:
            start_urls = [url.strip() for url in f.readlines()]
        f.close()

        with open("urls.txt", "rt") as f:
            for url in f.readlines():
                o = urlparse(url.strip())
                result = '{uri.netloc}'.format(uri=o)            
                allowed_domains.append(result)
        f.close()

        rules = (
            Rule(LinkExtractor(allow=()), callback='parse_item', follow=True),
        )
        
        def __init__(self, *a, **kw):
            super(CrawlSpider, self).__init__(*a, **kw)

            self._compile_rules()

            logging.log(logging.INFO, "======== Amount allowed Domains:")
            logging.log(logging.INFO, len(self.allowed_domains) )
            logging.log(logging.INFO, "======== Amount start URLs:")
            logging.log(logging.INFO, len(self.start_urls) )


        def parse_item(self, response):
            item = {}
            
            o = urlparse(response.url)
            result = '{uri.netloc}'.format(uri=o)
            if result in self.allowed_domains:
                self.write_html_file ( response )
            return item


        def write_html_file (self, response):
            current_url = response.url
            orootdir = 'out/'

            title = response.xpath('//title/text()').get()
            
            o = urlparse(current_url)
            result = '{uri.netloc}'.format(uri=o)

            if '/de/' in current_url:
                current_url = (current_url.replace('/de/', '')).strip()
            if '/en/' in current_url:
                current_url = (current_url.replace('/en/', '')).strip()
            if current_url.endswith ( "/" ):
                current_url = current_url[:-1]

            page = current_url.split("/")[-1]
            self.check_path ( orootdir + '/' )
            self.check_path ( orootdir + '/' + result )
            
            filename = datetime.today().strftime('%Y-%m-%d') + '__' + title + '.html'
            filename = sanitize_filename ( filename ).replace(' ', '_').strip()
            
            pathfilename = orootdir + '/' + result + '/'
            pathfilename = pathfilename + filename
            
            self.logger.info("Filename to be generated: " + pathfilename)
            
            with open(pathfilename, 'wb') as f:
                f.write(response.body)


        def check_path ( self, path ):
            if not os.path.exists( path ):
                os.makedirs( path )

`

urls.txt:


https://www.xlmoto.de
https://www.louis.de
https://www.polo-motorrad.de
https://motorradonline.shop
https://www.motoport.de
https://www.fc-moto.de
https://www.motoin.de
https://www.moto24.de
https://www.tecbike.de
https://www.motobike.de
https://shop.held.de
https://www.bekleidung-motorrad.de
https://www.bikeroutfit.de
https://www.motorrad-ersatzteile24.de
https://www.motorradland.net
https://www.mvh-shop.de
https://www.motorradfahrer-shop.de
https://www.procar-bikestore.de
https://www.motomike.eu
https://www.motocard.com
https://www.shop-waldmann.de
https://www.wunderlich.de
https://shop.touratech.de
https://www.motorradshop-streifeneder.de
https://www.motea.com
https://www.revzilla.com
https://www.motostorm.it
https://www.gearbest.com
https://www.motardinn.com
https://www.tomtop.com
https://www.xlmoto.eu
https://www.hepco-shop.de
https://www.motocard.com
https://www.moto24.org
https://www.moto-gear.eu
https://www.mcas.com.au
https://petrolettes.com
https://www.bikebandit.com
https://www.shopbmwmotorcycle.com
https://motofever.com
https://www.motorsportsuperstore.com
https://www.webike.in
https://www.dainese.com
https://www.lindtriumph.co.uk
https://www.teammotorcycle.com
https://www.helmexpress.com
https://www.denniskirk.com
https://www.sportsbikeshop.co.uk
https://www.cyclegear.com
https://www.dock66.de
https://www.louis-moto.co.uk
https://www.bobber-store.com
https://www.motorbikemaniac.com
https://en.tenkateshop.com
https://www.bts-motorradteile.de
https://www.triumphworld.de
https://www.alphamotorcycles.co.uk
https://www.euronetbike.net
https://www.jpcycles.com
https://www.zeusmotorcyclegear.com
https://safexbikes.com
https://www.lazyassbikers.com
https://www.staccatocycle.com
https://htrzmodz.com
https://www.gearup.store
https://www.bikerwolke.com
https://www.husqvarnamotorcyclepartsonline.com
https://bikehouse-motorrad.com
https://www.motorsportgoetz.com
https://www.shopbmwmotorcycles.com
https://www.innomotocycleparts.com
https://www.24helmets.de
https://alhaweemotors.com
https://www.getgeared.co.uk
https://www.btosports.com
https://www.chapmoto.com
https://www.biketeile-service.de
https://www.vdmparts.com
https://www.bikestop.co.uk
https://ktmdirect.co.uk
https://zodiac.nl
https://gpbikes.com
https://www.jsaccessories.co.uk
https://www.bigtwin-motorcycles.de
https://www.outletmoto.eu
https://www.wunderlichamerica.com
https://motorcyclestuff.com.au
https://www.discount-motorcycle-parts.net
https://www.highnoteperformance.com
https://www.kuryakyn.com
https://www.caferacerwebshop.com
https://www.wemoto.com
https://www.ridersdiscount.com
https://www.thevisorshop.com
https://blackfootonline.ca
https://a2z-motorcycle-superstore.com
https://bandidospitstop.com
https://www.motorcycleshop.ie
https://recraftmoto.com
https://www.petes-superbike.com
https://gpbikes.com
https://www.kimpex.com
https://www.twistedthrottle.ca
https://blackfootonline.ca
https://dreamcyclescanada.com
https://www.royaldistributing.com
https://www.riderschoice.ca
https://motostarz.ca
https://www.dualsportplus.com


logfile:

`
	2019-10-10 14:29:46 [scrapy.utils.log] INFO: Scrapy 1.7.3 started (bot: crawlerscrapy)
	2019-10-10 14:29:46 [scrapy.utils.log] INFO: Versions: lxml 4.3.3.0, libxml2 2.9.9, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 19.2.0, Python 3.7.3 (default, Oct  7 2019, 12:56:13) - [GCC 8.3.0], pyOpenSSL 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019), cryptography 2.6.1, Platform Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco
	2019-10-10 14:29:46 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'crawlerscrapy', 'CONCURRENT_REQUESTS': 150, 'CONCURRENT_REQUESTS_PER_DOMAIN': 1, 'COOKIES_ENABLED': False, 'DEPTH_LIMIT': 1, 'DOWNLOAD_DELAY': 13, 'DOWNLOAD_TIMEOUT': 9, 'LOG_FILE': 'log/2019-10-10-complete.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'crawlerscrapy.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 20, 'RETRY_TIMES': 1, 'SCHEDULER_DEBUG': True, 'SCHEDULER_DISK_QUEUE': 'scrapy.squeues.PickleFifoDiskQueue', 'SCHEDULER_MEMORY_QUEUE': 'scrapy.squeues.FifoMemoryQueue', 'SCHEDULER_PRIORITY_QUEUE': 'scrapy.pqueues.DownloaderAwarePriorityQueue', 'SPIDER_MODULES': ['crawlerscrapy.spiders']}
	2019-10-10 14:29:46 [scrapy.extensions.telnet] INFO: Telnet Password: 10c16fb04c4f55af
	2019-10-10 14:29:46 [scrapy.middleware] INFO: Enabled extensions:
	['scrapy.extensions.corestats.CoreStats',
	 'scrapy.extensions.telnet.TelnetConsole',
	 'scrapy.extensions.memusage.MemoryUsage',
	 'scrapy.extensions.logstats.LogStats']
	2019-10-10 14:29:46 [root] INFO: ======== Starting with start_requests
	2019-10-10 14:29:46 [root] INFO: ======== Amount allowed Domains:
	2019-10-10 14:29:46 [root] INFO: 109
	2019-10-10 14:29:46 [root] INFO: ======== Amount start URLs:
	2019-10-10 14:29:46 [root] INFO: 109
	2019-10-10 14:29:46 [root] INFO: ======== Finished with start_requests
	2019-10-10 14:29:46 [scrapy.middleware] INFO: Enabled downloader middlewares:
	['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
	 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
	 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
	 'random_useragent.RandomUserAgentMiddleware',
	 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
	 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
	 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
	 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
	 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
	 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
	 'scrapy.downloadermiddlewares.stats.DownloaderStats']
	2019-10-10 14:29:46 [scrapy.middleware] INFO: Enabled spider middlewares:
	['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
	 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
	 'scrapy.spidermiddlewares.referer.RefererMiddleware',
	 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
	 'scrapy.spidermiddlewares.depth.DepthMiddleware']
	2019-10-10 14:29:46 [scrapy.middleware] INFO: Enabled item pipelines:
	[]
	2019-10-10 14:29:46 [scrapy.core.engine] INFO: Spider opened
	2019-10-10 14:29:46 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
	2019-10-10 14:29:46 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
	2019-10-10 14:29:48 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for hostname "www.motorbikemaniac.com"; VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'www.motorbikemaniac.com'))])
	2019-10-10 14:29:55 [spid] INFO: Filename to be generated: out//www.louis.de/2019-10-10__Bekleidung,_Helme_und_Motorradzubehör__Louis_Motorrad_&_Freizeit.html
	2019-10-10 14:29:55 [spid] INFO: Filename to be generated: out//www.lindtriumph.co.uk/2019-10-10__Sign_in.html
	2019-10-10 14:29:56 [spid] INFO: Filename to be generated: out//www.helmexpress.com/2019-10-10__Helm_Shop_-_Sicherheit_für_Ihren_Kopf__HELMEXPRESS.html
	2019-10-10 14:29:57 [spid] INFO: Filename to be generated: out//www.motobike.de/2019-10-10__MOTOBIKE_Frank_Jörger_e.K.-_Ihr_Motorrad_Händler_in_Offenburg.html
	2019-10-10 14:29:58 [spid] INFO: Filename to be generated: out//www.denniskirk.com/2019-10-10__Shipping_&_Returns__Dennis_Kirk.html
	2019-10-10 14:29:58 [spid] INFO: Filename to be generated: out//www.wunderlich.de/2019-10-10__Wunderlich_Wunderlich_-_complete_your_BMW_Motorrad_.html
	2019-10-10 14:29:58 [spid] INFO: Filename to be generated: out//www.hepco-shop.de/2019-10-10__Motorradzubehör_von_Hepco&Becker_-_Offizieller_Online_Shop.html
	2019-10-10 14:29:58 [spid] INFO: Filename to be generated: out//www.moto24.de/2019-10-10__moto24__Motorradbekleidung,_Helme_&_Motorradzubehör.html
	2019-10-10 14:29:59 [spid] INFO: Filename to be generated: out//www.moto-gear.eu/2019-10-10__Moto_gear,_motorcycle_parts,_online_shop__moto-gear.eu.html
	2019-10-10 14:29:59 [spid] INFO: Filename to be generated: out//www.shopbmwmotorcycle.com/2019-10-10____BMW_Motorcycle_Parts__Accessories__Clothing__Gear__Helmets__OEM_–_Sierra_BMW_Motorcycle__.html
	2019-10-10 14:29:59 [spid] INFO: Filename to be generated: out//www.mvh-shop.de/2019-10-10__News_from_MVH_-_Motorradteilevertrieb_Hamburg_GmbH.html
	2019-10-10 14:29:59 [spid] INFO: Filename to be generated: out//www.dock66.de/2019-10-10__Privacy.html
	2019-10-10 14:30:00 [spid] INFO: Filename to be generated: out//www.motorradland.net/2019-10-10__Zahlung_und_Versand__Motorradland.net.html
	2019-10-10 14:30:00 [spid] INFO: Filename to be generated: out//www.motorrad-ersatzteile24.de/2019-10-10__Rabatt_Clean_and_Care__Motorrad_Ersatzteile_24____.html`

**Comment by Chris8080** [comment] 2019-10-11 11:48
I've simply added batches via arguments, and it's working now.
For that, I have to start 3 spiders, CPU can handle it easily at the same time and all 106 folders are created within seconds.
It would still be nice to find out, why Scrapy didn't work with or without start_requests() for me.

`
        batch = int ( kw.get('batch') ) or 1

        if batch == 1:
            self.start_urls = start_urls[0:49]
            self.allowed_domains = allowed_domains[0:49]
        elif batch == 2:
            self.start_urls = start_urls[50:99]
            self.allowed_domains = allowed_domains[50:99]
        elif batch == 3:
            self.start_urls = start_urls[100:149]
            self.allowed_domains = allowed_domains[100:149]
`

**Comment by Gallaecio** [comment] 2019-11-11 09:30
This does look like the same as what @kmike linked. You said it did not look like it because it also happens when using `start_urls` instead, but `start_urls` is basically the same as `start_requests` (when you don’t define `start_request`, a default implementation of it is used which reads URLs from `start_urls`).

Shall we close this in favor of the previously reported issues?

**Comment by Chris8080** [comment] 2019-11-13 20:19
I wasn't able to get it working the way "it's supposed to" but this mentioned workaround is working fine here. You can go ahead and close this if you want to.

**Closed** 2019-11-13 20:36 UTC
Labels: needs more info
