### ISSUE TITLE
[Bug] 1.7.1 not support 1.6.0 script

### ISSUE THREAD

**Issue by Kenith** [scrapy/scrapy#3893] opened 2019-07-22 03:48 UTC
Hello All,

My spider is created by scrapy 1.6.0.
These days, the scrapy updated to 1.7.1, and we found that it cannot support the code build by 1.6.0.

Here is the error:
```
Traceback (most recent call last):
  File "/usr/bin/scrapy", line 6, in <module>
    from scrapy.cmdline import execute
  File "/usr/lib64/python2.7/site-packages/scrapy/cmdline.py", line 10, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/usr/lib64/python2.7/site-packages/scrapy/crawler.py", line 11, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/usr/lib64/python2.7/site-packages/scrapy/core/engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "/usr/lib64/python2.7/site-packages/scrapy/core/scraper.py", line 18, in <module>
    from scrapy.core.spidermw import SpiderMiddlewareManager
  File "/usr/lib64/python2.7/site-packages/scrapy/core/spidermw.py", line 13, in <module>
    from scrapy.utils.conf import build_component_list
  File "/usr/lib64/python2.7/site-packages/scrapy/utils/conf.py", line 4, in <module>
    import configparser
ImportError: No module named configparser
```

Would you please take time to check the issue?

Appreciate for your help in advance.

Thank you.

**Comment by elacuesta** [comment] 2019-07-22 15:41
Hello @Kenith, this has been reported already at #3889 
As I commented there, if you can install additional dependencies you can work around the issue by installing the backported version (https://pypi.org/project/configparser/).
If you don't mind, please consider closing this issue as it is a a duplicate of #3889. Thanks!

**Comment by Kenith** [comment] 2019-07-23 05:45
Hello @elacuesta , really appreciate for your time and effort.
I closed the issue. Thank you.

**Closed** 2019-07-23 05:45 UTC
