### ISSUE TITLE
large response causes scrapy to hang

### ISSUE THREAD

**Issue by rjbks** [scrapy/scrapy#2658] opened 2017-03-16 23:59 UTC
I have tried stackoverflow but haven't received any answers for this as of yet.

[scrapy hangs on large response](http://stackoverflow.com/questions/42822010/scrapy-hanging-on-api-call-which-returns-large-json-object)

Summary:

Using scrapy to make thousands of API calls, all of them work fine except for 1 which returns a response of around 2GB (takes roughly 4 mins to complete using requests library). I have increased or disabled the related settings which may limit download size or timeout (DOWNLOAD_MAXSIZE DOWNLOAD_TIMEOUT). The logs show a 200 response then the warning for download size (which I left enabled just to indicate some form of progress) I then get 3 consecutive INFO logs from the stat tracker (1 minute apart), then it just hangs. I have left it running for up to 30 mins then I had to force quit (control-c does not work). Based on that, it would seem to hang after roughly 3 minutes after initiating that API call without any more logging whether I leave the download_timeout enable (for either 6.5 or 7 minutes when several attempts with requests package yields results in about 4 minutes) or disabled. Any ideas what could be causing this?

**Comment by redapple** [comment] 2017-03-20 14:34
hi @rjbks ,
I was able to download a large file with Scrapy [from MusicBrainz](http://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/20170315-001454/mbdump.tar.bz2) with `-s DOWNLOAD_TIMEOUT=100000 -s DOWNLOAD_MAXSIZE=0`
https://gist.github.com/redapple/42e800de71eaf663e3fcbfb02fa3a606

I have patched Scrapy to get more feedback during the download:
```
$ git diff
diff --git a/scrapy/core/downloader/handlers/http11.py b/scrapy/core/downloader/handlers/http11.py
index 6a0c6e4..44ef274 100644
--- a/scrapy/core/downloader/handlers/http11.py
+++ b/scrapy/core/downloader/handlers/http11.py
@@ -427,9 +427,10 @@ class _ResponseReader(protocol.Protocol):
                             'request': self._request})
         if self._warnsize:
             if self._bytes_received > ((self._warnsize / 10) * (self._warnsize_times + 1)):
+                from humanize import naturalsize
                 self._warnsize_times = self._bytes_received // (self._warnsize / 10)
-                logger.debug("Received (%(bytes)s) bytes",
-                             {'bytes': self._bytes_received})
+                logger.debug("Received %(bytes)10s",
+                             {'bytes': naturalsize(self._bytes_received)})
     def connectionLost(self, reason):
         if self._finished.called:
             return
```

I could not cancel the download with `Control-C`, while the download is indeed cancelled when the download timeout kicks in (not in the gist above).
I'll try and dig this week.

**Comment by milescrawford** [comment] 2017-03-22 20:59
Same issue here, I see: 

```2017-03-22 20:20:44 [scrapy.core.downloader.handlers.http11] WARNING: Received more bytes than download warn size (33554432) in request <GET http://nlp.cs.berkeley.edu/downloads/train_abstracts_standoff.tgz>.```

After which Scrapy does nothing. Attaching `strace` shows that it is messing around with memory in a tight loop:
```
mmap(NULL, 253456384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f67af73e000
munmap(0x7f67913dc000, 253448192)       = 0
mmap(NULL, 253464576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f67a0585000
munmap(0x7f67af73e000, 253456384)       = 0
mmap(NULL, 253472768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f67913ca000
munmap(0x7f67a0585000, 253464576)       = 0
mmap(NULL, 253480960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f67af738000
munmap(0x7f67913ca000, 253472768)       = 0
mmap(NULL, 253489152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f67a0579000
munmap(0x7f67af738000, 253480960)       = 0

etc etc forever...
```

**Comment by rjbks** [comment] 2017-03-22 22:28
One other piece of information:

These spiders are scheduled through scrapyd and when one of them hangs because of large downloads (I will see the same info in the logs as described in my original post except when run from scrapyd and left to run indefinitely the spider itself will eventually shut down but after 8-10 hours) I see this in scrapyd's logs:

`2017-03-22T15:53:19-0400 [-] Timing out client: IPv4Address(TCP, '127.0.0.1', 36830)`

That will show repeatedly in non-uniform intervals with different port numbers after the spider hangs and that timeout logging persists after the spider is shut down. Is there a way to tell what resource scrapyd is trying to reach with those requests which are showing as timed-out?

**Comment by rjbks** [comment] 2017-03-23 20:30
@redapple 
I didn't notice your last sentence until now. The download timeout doesn't kick in at all in my example, the spider seems to hang before that, usually within 3 minutes or so.

**Comment by ashkulz** [comment] 2017-11-08 16:52
This is reproducible and the root cause seems to be [`HttpCompressionMiddleware`](https://github.com/scrapy/scrapy/blob/b8870ee8a10360aaa74298324d97c823b88ec5c6/scrapy/downloadermiddlewares/httpcompression.py#L53) -- when you have a 1GB file to decompress, the system is definitely going to freeze.

Webserver:
```python
#!/usr/bin/env python3
from zlib        import compressobj, DEFLATED, MAX_WBITS
from http.server import HTTPServer, BaseHTTPRequestHandler
from random      import sample
from string      import ascii_lowercase

def sentence(len, spaces):
    return ''.join(sample(len*(list(ascii_lowercase)+(spaces*[' '])), len))

class GzipRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-Type', 'text/plain; encoding=utf-8')
        self.send_header('Content-Encoding', 'gzip')
        self.end_headers()
        data = compressobj(wbits=MAX_WBITS|16)
        text = '\n'.join(sentence(100, 10) for _ in range(100)).encode('utf-8')
        for chunk in range(100000):
            self.wfile.write(data.compress(text))
        self.wfile.write(data.flush())
        self.wfile.flush()

def main():
    address = ('0.0.0.0', 8000)
    httpd   = HTTPServer(address, GzipRequestHandler)
    httpd.serve_forever()

if __name__ == '__main__':
    main()
```

Running curl doesn't seem to create a problem:

```bash
$ time curl -sS --compressed -o /dev/null http://localhost:8000

real	0m5.071s
user	0m1.064s
sys	0m0.020s
```

On the other hand, scrapy seems to just hang and even Ctrl-C doesn't work as C code is being executed:

```bash
$ time scrapy shell http://localhost:8000 -s DOWNLOAD_MAXSIZE=0 
2017-11-08 21:56:05 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: scrapybot)
2017-11-08 21:56:05 [scrapy.utils.log] INFO: Overridden settings: {'DOWNLOAD_MAXSIZE': '0', 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'LOGSTATS_INTERVAL': 0}
2017-11-08 21:56:05 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.memusage.MemoryUsage']
2017-11-08 21:56:05 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-11-08 21:56:05 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-11-08 21:56:05 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-11-08 21:56:05 [scrapy.core.engine] INFO: Spider opened

```

The solution seems to be using Twisted's [ContentDecoderAgent](https://twistedmatrix.com/documents/current/api/twisted.web.client.ContentDecoderAgent.html) which does the decompression incrementally (as the data is being received) instead of at the end. Not sure what the performance difference will be, and there's no place to inject it in [ScrapyAgent](https://github.com/scrapy/scrapy/blob/b8870ee8a10360aaa74298324d97c823b88ec5c6/scrapy/core/downloader/handlers/http11.py#L231) as of now.

A simple workaround seems to be to set `COMPRESSION_ENABLED` to False.

**Comment by GeorgeA92** [comment] 2023-01-16 17:37
It looks like this issue is not reproducible after merge https://github.com/scrapy/scrapy/pull/3281
Counting this I propose to:
1. close this issue as completed.
2. and close https://github.com/scrapy/scrapy/pull/3270 in favor of already merged https://github.com/scrapy/scrapy/pull/3281

**Closed** 2023-01-17 08:59 UTC
Labels: bug
