### ISSUE TITLE
Image read issue..

### ISSUE THREAD

**Issue by VinuAbraham** [scrapy/scrapy#4787] opened 2020-09-14 11:43 UTC
I am using image pipeline to download some images from a sit. I think the image is getting downloaded. Some error is happening when pillow is trying to read the downloaded image..

```
2020-09-14 16:43:42 [scrapy.pipelines.files] DEBUG: File (downloaded): Downloaded file from <GET https://37300fab1c6470e21bd3-a8e5cce4c77b7c72b39d8ea638763d06.ssl.cf1.rackcdn.com/1VWAA7A31LC021393/d92b4ef57fd41f302e9af361e69fc9fc.jpg> referred in <None>
2020-09-14 16:43:42 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://37300fab1c6470e21bd3-a8e5cce4c77b7c72b39d8ea638763d06.ssl.cf1.rackcdn.com/1VWAA7A31LC021393/d92b4ef57fd41f302e9af361e69fc9fc.jpg> referred in <None>
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/scrapy/lib/python3.8/site-packages/scrapy/pipelines/files.py", line 496, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "/home/shiva/anaconda3/envs/scrapy/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 108, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "/home/shiva/anaconda3/envs/scrapy/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 112, in image_downloaded
    for path, image, buf in self.get_images(response, request, info):
  File "/home/shiva/anaconda3/envs/scrapy/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 125, in get_images
    orig_image = Image.open(BytesIO(response.body))
  File "/home/shiva/.local/lib/python3.8/site-packages/PIL/Image.py", line 2930, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f68ef621630>

```
spider.py
```
`import scrapy
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule
from scrapy.loader import ItemLoader
from ggcar.items import GgcarItem

from scrapy_selenium import SeleniumRequest
from scrapy.utils.response import open_in_browser


class VwoffreeholdSpider(CrawlSpider):
    name = 'vwoffreehold'
    allowed_domains = ['www.vwoffreehold.com']
    start_urls = ['https://www.vwoffreehold.com/new-vehicles/']

    rules = (


        Rule(LinkExtractor(restrict_xpaths="//a[contains(@class,'hit-link')]",
                           unique=True), callback='image_load', follow=False),

    )

    def image_load(self, response):

        image_loader = ItemLoader(
            item=GgcarItem(), response=response
        )

        vins = response.xpath(
            ".//span[contains(@id,'vin')]/text()").get()

        link = response.xpath(
            ".//div[contains(@class,'swiper-slide swiper-slide-next')]/img[contains(@class,'swiper-lazy swiper-lazy-loaded loaded')]/@src").extract()



        yield GgcarItem(image_urls=link, vin=[vins])`
```

middlewares.py

```
class SeleniumMiddleware(object):
    def __init__(self):

        self.driver = webdriver.Firefox(
            executable_path=r'/root/ggcar/geckodriver')  # , options=self.options)

    def process_request(self, request, spider):

        self.driver.get(request.url)

        body = self.driver.page_source
        return HtmlResponse(self.driver.current_url, body=body, encoding='utf-8', request=request)


```
settings.py

```
BOT_NAME = 'ggcar'

SPIDER_MODULES = ['ggcar.spiders']
NEWSPIDER_MODULE = 'ggcar.spiders'


#
DOWNLOADER_MIDDLEWARES = {
    'ggcar.middlewares.SeleniumMiddleware': 543,
}
DOWNLOAD_TIMEOUT = 120
ROBOTSTXT_OBEY = True
```

items.py

```
import scrapy
from scrapy.loader.processors import MapCompose, TakeFirst
class GgcarItem(scrapy.Item):

    
    vin = scrapy.Field(
        input_processor=MapCompose(),
        output_processor=TakeFirst()

    )
    
     image_urls = scrapy.Field(

    )
     images = scrapy.Field()


@elacuesta```

**Comment by elacuesta** [comment] 2020-09-15 18:07
Please, follow [the guidelines](https://docs.scrapy.org/en/latest/contributing.html#reporting-bugs) when opening an issue. Specifically, include a [Minimal and Reproducible Example](https://stackoverflow.com/help/mcve) to allow us to reproduce it.

**Comment by VinuAbraham** [comment] 2020-09-24 06:24
@elacuesta Hope this is all the code needed for reproduce the issue

**Comment by elacuesta** [comment] 2020-09-24 13:20
The updated code is far from _minimal_, and I see no mention of the [images pipeline](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#scrapy.pipelines.images.ImagesPipeline). Furthermore, you seem to be using Selenium, which may affect the results and it's out of the scope of this issue tracker. At it currently stands, this is a support question, not a bug report for Scrapy itself, so I'm closing it and recommending you to refer to other channels such as the ["scrapy" tag at StackOverflow](https://stackoverflow.com/tags/scrapy). See also [Getting help](https://docs.scrapy.org/en/latest/#getting-help).

**Closed by elacuesta** 2020-09-24 13:20 UTC
Labels: needs more info
