### ISSUE TITLE
Error when resuming a crawler

### ISSUE THREAD

**Issue by jbinfo** [scrapy/scrapy#1178] opened 2015-04-19 18:01 UTC
Can someone show me how to correct this issue when resuming the crawler, below the log file
```
2015-04-19 10:54:38-0700 [my_spider_name] INFO: Spider opened
2015-04-19 10:54:50-0700 [my_spider_name] INFO: Resuming crawl (5403830 requests scheduled)
2015-04-19 10:54:50-0700 [my_spider_name] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-04-19 10:54:51-0700 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-04-19 10:54:51-0700 [scrapy] DEBUG: Web service listening on 127.0.0.1:6080
2015-04-19 10:54:51-0700 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 93, in start
        self.start_reactor()
      File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 130, in start_reactor
        reactor.run(installSignalHandlers=False)  # blocking call
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(*call.args, **call.kw)
      File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/reactor.py", line 41, in __call__
        return self._func(*self._a, **self._kw)
      File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 107, in _next_request
        if not self._next_request_from_scheduler(spider):
      File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 134, in _next_request_from_scheduler
        request = slot.scheduler.next_request()
      File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scheduler.py", line 64, in next_request
        request = self._dqpop()
      File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scheduler.py", line 94, in _dqpop
        d = self.dqs.pop()
      File "/usr/local/lib/python2.7/dist-packages/queuelib/pqueue.py", line 43, in pop
        m = q.pop()
      File "/usr/local/lib/python2.7/dist-packages/scrapy/squeue.py", line 18, in pop
        s = super(SerializableQueue, self).pop()
      File "/usr/local/lib/python2.7/dist-packages/queuelib/queue.py", line 157, in pop
        self.f.seek(-size-self.SIZE_SIZE, os.SEEK_END)
    exceptions.IOError: [Errno 22] Invalid argument
```

**Comment by kmike** [comment] 2015-04-19 18:09
I think it is the same issue as https://github.com/scrapy/scrapy/issues/845.

**Comment by jbinfo** [comment] 2015-04-19 18:18
@kmike Yup it's same issue

**Comment by kmike** [comment] 2015-04-19 18:21
I'm not sure how to debug it. Maybe the only way is to read https://github.com/scrapy/queuelib code carefully, trying to understand when and why can it fail.

**Comment by jbinfo** [comment] 2015-04-19 18:30
I will check it and back to you, thank you @kmike :)

**Comment by dangra** [comment] 2015-04-29 05:25
closing as dupe of #845

**Closed by dangra** 2015-04-29 05:25 UTC
