### ISSUE TITLE
Pyinstaller+Python3.4+Scrapy1.4 Failed to bundled exe (ImportError:No module named "XXXX")

### ISSUE THREAD

**Issue by Caleb-Wade** [scrapy/scrapy#3073] opened 2018-01-12 12:30 UTC
I have tried to bundle my spider .py into .exe, but weeks pasted, I didn't make it. It pointed that some modules were missing. Even I used --hidden-import to put the missing modules into my bundled exe, it still didn't work. It's amazing that I can see the modules in the HTML document under build file. Pls help me ,Thks!

**Comment by cathalgarvey** [comment] 2018-02-21 17:11
Mostly a duplicate of #3074 - Unsupported packaging method that would be interesting to better-support, but I don't think the information we need is here. If someone solves this and writes up what about Scrapy makes this difficult, perhaps we can make it easier? I suspect the packaging problems have more to do with our C-heavy upstream dependencies, however.

**Closed by cathalgarvey** 2018-02-21 17:11 UTC
