### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by extesy** [scrapy/scrapy#263] opened 2013-03-06 22:48 UTC
Python 3 is several years old and most of packages now support it (even django!). It would be really nice to support it in scrapy as well.

**Comment by ianozsvald** [comment] 2015-03-18 10:11
+1 for Python 3.4 support. After a year using Python 3 (mainly sklearn, numpy, Anaconda, matplotlib, networkx etc) this is the first blocker I've had forcing me to downgrade. 

The only other Python2.7-only project that I'm lightly using is Apache Spark and 3.4+ support is scheduled for their next release. In their issue tracker I posted some stats for Python 3 adoption - roughly speaking it is ">40%" (accepting the self-selected group of survey participants):
https://issues.apache.org/jira/browse/SPARK-4897?focusedCommentId=14303154&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14303154

**Comment by kmike** [comment] 2015-03-18 18:18
@ianozsvald we are working on it, it is a priority :) 

Scrapy is the worst kind of project to port to Python 3 - it depends on Twisted (which is not ported to Python 3 yet - some subset of Twisted works though), and it works at outside world / python world boundary, so there are many questions about unicode. "Outer World" Scrapy works with is wild - there is no a well-defined encoding we can decode/encode data from/to. Encoding rules are sometimes crazy - e.g. browsers (which Scrapy aims to emulate) can use different charsets for different *parts* of a single URL, e.g. cp1251 for /path and utf-8 for GET parameter values. I've ported a lot of code to Python 3 (including most of NLTK and tens of other Python packages), but still getting porting details wrong for Scrapy (e.g. https://github.com/scrapy/scrapy/pull/837 is wrong).

Some parts of Scrapy are already ported to Python 3. We're running tests for Python 3.3 on Travis to prevent regressions; ~240 tests pass in 3.3, out of ~1000. There is a GSoC project to port Scrapy to Python 3.x; I think we should make a good progress this summer.

**Comment by kmike** [comment] 2015-03-18 18:22
There is also https://github.com/mitmproxy/mitmproxy Scrapy dependency which doesn't have Python 3 support yet, but it is used only in tests.

**Comment by ianozsvald** [comment] 2015-03-19 10:12
@kmike Hey Mikhail! You are a man of many projects :-) Glad to hear it is being worked on, I didn't get that impression from the early parts of this thread and couldn't see any other porting docs. I quite agree that this project (just like Flask et al.) is going to be hard, dealing with the interface to the outside world is horrid. I certainly didn't know that URLs themselves could have mixed encodings :-(
Given the continual migration to Python 3 for personal projects (50/50 according to the survey I linked vs Python 2.7) and >40% for work, the need for scrapy's Py3 support is only going to get stronger. Bon chance!

**Comment by pbronez** [comment] 2015-03-23 22:19
+1 for Python 3 support! Thanks for the hard work you guys are putting into it, hope GSoC goes well.

**Comment by nuschk** [comment] 2015-04-20 13:03
:+1: as well, would really love to be able to use python 3 with scrapy! And many thanks your effort!

**Comment by vmarkovtsev** [comment] 2015-05-19 13:10
You can use my patches with ported twisted.web.client.Agent and friends from [my fork](https://github.com/vmarkovtsev/twisted).

**Comment by nyov** [comment] 2015-07-14 14:38
Are there still outside blockers for porting to python3? (twisted libs, etc.?)
Would love to see a list of those, if one has been made.

Also, in the name of eventual portability (e.g. asyncio?) how do people feel about dropping dependencies on twisted for the web/downloader part? I recall there was a gsoc idea for this?
Would be interesting to see if a downloader using pycurl bindings might work with twisted here.
(Though pycurl has no cffi bindings at this time, so no pypy support.)

**Comment by curita** [comment] 2015-07-14 16:29
There's a comprehensive status of the twisted dependencies in Berker's proposal. @berkerpeksag, would you mind if we put it up on our wiki for reference?

**Comment by berkerpeksag** [comment] 2015-07-14 16:44
Sure, but that list is a bit outdated. For example, `twisted.web.static` has already been [ported to Python 3](https://github.com/twisted/twisted/commit/ab110cc815c31eed17bb5ef06f1037a8ede0b395). You may want to check `twisted/python/dist3.py` first.

**Comment by curita** [comment] 2015-07-14 17:07
Will do, thanks!

**Comment by curita** [comment] 2015-07-14 17:58
Here's the updated list: https://github.com/scrapy/scrapy/wiki/PY3%3A-Twisted-Dependencies.

**Comment by nyov** [comment] 2015-07-14 18:02
Thank you both!

**Comment by tonal** [comment] 2015-07-15 05:33
https://twistedmatrix.com/trac/ticket/7540 closed

**Comment by curita** [comment] 2015-07-15 13:32
That's great news, thanks for reporting! I just updated the wiki.

**Comment by ianozsvald** [comment] 2015-07-23 08:56
Hello all. I've got a Lightning Talk on Python3.5 at my next PyDataLondon meet (200+ data scientists in the room). Someone is bound to ask about scrapy/twisted on Python 3.4+, could someone comment on the current state? It isn't clear to me from the links above if enough of `twisted` has been ported for `scrapy` to run on Python 3 (or will soon)?

**Comment by curita** [comment] 2015-07-25 03:29
Hi @ianozsvald, glad to hear about the interest in python3 support!

Currently scrapy doesn't run in python3, not even a meaningful subset of it, but twisted support isn't the only issue holding us back. Most of the twisted modules used in scrapy are already ported, and in some cases the features that use them could be deactivated, like telnet or mail (well, extensions that use mail could be deactivated or changed to not use mail in python3 for instance). `twisted.web.client.Agent` is a problem anyhow, but this can be patched in our side.

We stopped the python3 integration for some time because we couldn't agree on the type we should use to represent urls but thankfully that matter was resolved, though it hasn't been coded yet.

So, there aren't any big stoppers (not that I know of), just the time to get around it.

We haven't defined a deadline yet but it's something we want to see before the end of the year. On top of that, this weekend some scrapinghubbers will hold a sprint to accelerate the support, so maybe there'll be news sooner than expected :wink:

**Comment by ianozsvald** [comment] 2015-07-27 12:26
Hi @curita, thanks for the note. For my data science audience I think scrapy is the only non-python-3.4 package that matters, everything else that they (and I) use is already running with Python 3.4. I wish you all luck in the conversion, knowing the data science stack is almost fully 3.4 compliant really helps when planning larger-scale projects.

**Comment by darkrho** [comment] 2015-07-29 13:37
Is there any plan to replace `mitmproxy` requirement for tests?

**Comment by kmike** [comment] 2015-07-29 13:38
@darkrho I don't know; I was thinking about porting it, not replacing. Are there alternatives?

**Comment by kmike** [comment] 2015-07-29 13:53
@ianozsvald I know your pain; Scrapy is the only reason I'm using Python 2 now :) At EuroPython me and @dangra tried to unblock the further porting - the bottleneck was in Request and Response objects, and they are ported now in https://github.com/scrapy/scrapy/pull/1384. It is still a long road to full Python 3 support, but we're in a much better shape now - 480 tests are passing in Python 3, compared to 267 before the sprint. Working Request and Response objects open a gate for other's contributions, so I expect Python 3 Scrapy support to get more love soon.

**Comment by ianozsvald** [comment] 2015-07-29 15:08
@kmike hey, that's lovely to hear (and Graham Markall [of Continuum] told me about the sprint), we'll certainly note this when we talk next week. Cheers!

**Comment by kmike** [comment] 2015-08-05 12:27
For anyone interested in contributing I've created a wiki page (https://github.com/scrapy/scrapy/wiki/Python-3-Porting) with some information & guidelines.

**Comment by stonebig** [comment] 2015-11-29 20:51
apparantly, twisted for python 3 is out ... https://twitter.com/hawkieowl/status/670885245328166912

**Comment by stonebig** [comment] 2015-11-29 21:06
I don't understand, I suppose examples are not rewritten for Python3:
- I can dowload and install Spyder on Python 3.4
- but this fails:
````
import scrapy 


class MySpider(scrapy.Spider):
    name = 'example.com'
    allowed_domains = ['example.com']
    start_urls = [
        'http://www.example.com/1.html',
        'http://www.example.com/2.html',
        'http://www.example.com/3.html',
    ]

    def parse(self, response):
        self.logger.info('A response from %s just arrived!', response.url)
        
````
with this error
````
>>> ================================ RESTART ================================
>>> 
Traceback (most recent call last):
  File "D:/WinPython/basedir34/buildBarebone/winpython-3.4.3/notebooks/scrapy.py", line 1, in <module>
    import scrapy
  File "D:/WinPython/basedir34/buildBarebone/winpython-3.4.3/notebooks\scrapy.py", line 4, in <module>
    class MySpider(scrapy.Spider):
AttributeError: 'module' object has no attribute 'Spider'
>>> 
````

Any idea how it should be written in Python 3 ?

**Comment by kmike** [comment] 2015-11-29 21:10
Hey @stonebig,

There are Scrapy parts which work in Python 3, but Scrapy as a framework is not usable for end users in Python 3 yet. Please wait or help us :)

**Comment by kmike** [comment] 2015-11-29 21:12
Apart from that, `Spyder` has nothing to do with Scrapy, and you're trying to import from your scrapy.py module, not from scrapy. There are other channels to get support - we're using http://stackoverflow.com (ask a question with Scrapy tag); there is also [scrapy-users](https://groups.google.com/forum/?fromgroups#!forum/scrapy-users) google group.

**Comment by stonebig** [comment] 2015-11-29 21:17
ok. I'll go to the user group. Sorry for the noise.

**Comment by tonal** [comment] 2015-12-01 06:47
https://twistedmatrix.com/trac/ticket/7407 fixed
https://twistedmatrix.com/trac/ticket/6197 fixed

**Comment by nyov** [comment] 2015-12-01 13:33
and updated [in the wiki](https://github.com/scrapy/scrapy/wiki/PY3:-Twisted-Dependencies#partly-ported-client)

**Comment by redapple** [comment] 2016-01-27 13:36
Basic support is planned for v1.1
And we plan to make it more robust for v1.2

**Comment by vmarkovtsev** [comment] 2016-01-27 15:08
:+1:

**Comment by stonebig** [comment] 2016-01-27 17:35
Great ! Is there a document that describe the rough timeline of these two milestones ? spring 2016 and summer 2016 ?

**Comment by redapple** [comment] 2016-01-27 17:38
@stonebig , we plan on releasing Scrapy 1.1 officially by the end of February 2016 (with a candidate release at least in the next few days)
Scrapy 1.2 would be a couple of months after that (we hope)

**Comment by stonebig** [comment] 2016-01-27 17:44
thanks a lot for this information, @redapple !

**Comment by KeremTubluk** [comment] 2016-02-02 18:40
It has gone and past six days, @redapple! 

:)

**Comment by redapple** [comment] 2016-02-02 18:42
@KeremTubluk , we're not quite there yet: https://github.com/scrapy/scrapy/milestones/v1.1

**Comment by manugarri** [comment] 2016-02-04 19:28
aand its official now. http://doc.scrapy.org/en/stable/news.html#id1

**Comment by ABSmiLT** [comment] 2016-02-29 05:59
it seems that the twisted already supports py3.3+

**Comment by d0ugal** [comment] 2016-02-29 10:07
> it seems that the twisted already supports py3.3+

@ABSmiLT Yeah, AFAICT Twisted only recently supported 3 well enough for Scrapy. Hence all the discussion above and in the docs.

**Comment by kmike** [comment] 2016-02-29 10:12
@ABSmiLT we've released scrapy 1.1rc1 with alpha-level Python 3 support about a month ago. 1.1rc2 will be released soon; it fixes several Python 3 compatibility issues we've found while testing 1.1rc1.

**Comment by ABSmiLT** [comment] 2016-03-18 09:04
thanks for informing, @kmike @d0ugal 
looking forward to the new stable version compatible with py3

**Comment by redapple** [comment] 2016-05-11 18:52
[Scrapy 1.1.0](https://pypi.python.org/pypi/Scrapy/1.1.0) is on PyPI, with Python 3 support (finally).
> What took you so long?

See [release notes](http://doc.scrapy.org/en/1.1/news.html).

Have fun!

**Closed by redapple** 2016-05-11 18:52 UTC
Labels: python3-port

**Comment by nyov** [comment] 2016-05-11 19:59
Are we there yet? are we there yet are wethereyetarewethere — :boom: ...eh, WHAT?
:sob: _finally_!

Congrats. Great job there keeping up the backports, @redapple. (Probably made a nice bang there, punching that "close"- button just then, right?)
And Thanks, everyone.

**Comment by fish-ball** [comment] 2016-05-12 02:53
Congratulations!!!!

**Comment by ABSmiLT** [comment] 2016-05-16 08:49
@redapple FINALLY!
thanks @all 

btw, the "PY3 95%" label is now out of date?
![image](https://cloud.githubusercontent.com/assets/8147261/15284790/1f83da08-1b86-11e6-9c9e-e657838406e8.png)

**Comment by kmike** [comment] 2016-05-16 08:51
@ABSmiLT no, it means 95% tests are passing in Python 3. There is a couple of features not ported yet (e.g. telnet console), and some tests are skipped. If we'd have PY2 badge it also won't be 100% according to this metric because some tests are also skipped in Python 2 :)

**Comment by mmccullar** [comment] 2016-05-17 13:39
So glad to see Python 3 support. Currently writing an automation/web crawling system in Ruby but may  switch to Python with the help of Scrapy!

**Comment by dangra** [comment] 2016-05-18 00:36
It has been a long road, great work!

**Comment by ABSmiLT** [comment] 2016-05-20 08:52
@kmike thanks a lot~ :100:

**Comment by AverHLV** [comment] 2016-05-21 18:40
But what about Twisted? I can`t run my Scrapy project cause of Twisted import error (no win32api).

**Comment by rolando** [comment] 2016-05-21 19:39
@AverHLV Twisted can run on python 3 but not on windows because `_win32stdio` has not been ported yet. See:

* https://twistedmatrix.com/trac/wiki/Plan/Python3#Details
* https://twistedmatrix.com/trac/ticket/8018

**Comment by kmike** [comment] 2016-05-21 19:47
Yeah, there is an issue in Scrapy bug tracker about that: https://github.com/scrapy/scrapy/issues/1998

**Comment by ABSmiLT** [comment] 2016-05-26 08:03
oops...am using python 3.5...so i have to continue waiting...loooooool

**Comment by ABSmiLT** [comment] 2016-05-26 08:05
i wish i can contribute to this project ASAP...still a newbie now...

**Comment by dangra** [comment] 2016-05-26 22:25
hey @ABSmiLT, try the ~~hack~~ suggestion in https://github.com/scrapy/scrapy/issues/1998#issuecomment-220849511 and share your experience.

**Comment by ABSmiLT** [comment] 2016-05-28 03:38
@dangra okay, thanks a lot~
