### ISSUE TITLE
AttributeError("Response content isn't text") -- linkextractor tries to extract PDF files when PDF is in deny_extension

### ISSUE THREAD

**Issue by leeprevost** [scrapy/scrapy#6159] opened 2023-11-27 22:38 UTC
### Description
I'm using a standard linkextractor with default "deny_extensions" which include PDF in the DENY_EXTENSIONS list.

But, in cases where the URL link is redirected to a PDF, I get an AttributeError("Response content isn't text")

Log examples:

```
<html>
<body>
<!--StartFragment-->
61: | 2023-11-27 22:03:56 | ERROR | [scrapy.core.scraper] Spider error processing <GET https://www.thearcoftexas.org/wp-content/uploads/Making-My-Own-Choices-SDM-plain-lang-guide-mar-2018.pdf> (referer: https://www.malakoffisd.org/274501_2) More
-- | -- | -- | --
62: | 2023-11-27 22:04:06 | ERROR | [scrapy.core.scraper] Spider error processing <GET https://www.hhs.texas.gov/sites/default/files/documents/laws-regulations/legal-information/guardianship/pub395-guardianship.pdf> (referer: https://www.malakoffisd.org/274501_2) More
63: | 2023-11-27 22:04:07 | ERROR | [scrapy.core.scraper] Spider error processing <GET https://tea.texas.gov/academics/special-student-populations/review-and-support/sd-updates-faq-oct-2021.pdf> (referer: https://www.malakoffisd.org/274501_2) More

<!--EndFragment-->
</body>
</html>
```
Here's the full stack trace ...
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/[defer.py](http://defer.py/)", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/[python.py](http://python.py/)", line 350, in __next__
    return next([self.data](http://self.data/))
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/[python.py](http://python.py/)", line 350, in __next__
    return next([self.data](http://self.data/))
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/usr/local/lib/python3.11/site-packages/sh_scrapy/[middlewares.py](http://middlewares.py/)", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/usr/local/lib/python3.11/site-packages/scrapy/spidermiddlewares/[offsite.py](http://offsite.py/)", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/usr/local/lib/python3.11/site-packages/scrapy/spidermiddlewares/[referer.py](http://referer.py/)", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/usr/local/lib/python3.11/site-packages/scrapy/spidermiddlewares/[urllength.py](http://urllength.py/)", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/usr/local/lib/python3.11/site-packages/scrapy/spidermiddlewares/[depth.py](http://depth.py/)", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 106, in process_sync
    for r in iterable:
  File "/tmp/unpacked-eggs/__main__.egg/edtech/spiders/[edcrawler.py](http://edcrawler.py/)", line 117, in parse
    ex_links = external_le.extract_links(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/linkextractors/[lxmlhtml.py](http://lxmlhtml.py/)", line 239, in extract_links
    base_url = get_base_url(response)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/utils/[response.py](http://response.py/)", line 26, in get_base_url
    text = response.text[0:4096]
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scrapy/http/response/__init__.py", line 137, in text
    raise AttributeError("Response content isn't text")
AttributeError: Response content isn't text
```

### Steps to Reproduce

1. STandard broad crawl spider that has a link extractor to crawl links

```
internal_le = LinkExtractor(
            deny = (r'.*\.pdf$', r'.*\.jpg$'),  #fixed cases for redirects to PDFs
            allow_domains=tld_t, # try to stay on domain I started on.
            unique=True,  # de-dup
            #deny_extensions=self.deny_extensions
        )
```
(Note that I've tried some regex in deny to further avoid?

2. crawl a url with many redirects to PDF docs:  eg: https://www.malakoffisd.org/
3. errors are produced

**Expected behavior:**  Dont' crawl PDFs even if redirected.

**Actual behavior:** PDFs downloaded and crawl error produced

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Scrapy 2.11.0
Zyte Crawl Hosting
Zyte smart proxies

**Comment by GeorgeA92** [comment] 2023-11-28 07:37
Duplicate of https://github.com/scrapy/scrapy/issues/2303

**Closed** 2023-11-28 07:50 UTC

**Comment by leeprevost** [comment] 2023-12-05 15:35
See #2303 for resolution.  Solved with custom middleware.
