### ISSUE TITLE
pip3 install scrapy failed with python3.7

### ISSUE THREAD

**Issue by zc1024** [scrapy/scrapy#3330] opened 2018-07-10 13:38 UTC
I use pip3 to install scrapy with python3.7.But it failed.
It showed that the twisted install failed.
I am not sure about if scrapy can works with python3.7.
Please. Thank you!

**Comment by lopuhin** [comment] 2018-07-10 13:40
@zc1024 indeed, currently scrapy does not work with python 3.7, we're working on fixing this. Closing this as a duplicate of #3143

**Closed by lopuhin** 2018-07-10 13:40 UTC
