### ISSUE TITLE
can't export to json file when use JsonWriterPipeline

### ISSUE THREAD

**Issue by danbao** [scrapy/scrapy#1864] opened 2016-03-15 16:15 UTC
**Scrapy 1.0.5
Python 2.7.11**

pipelines.py
```python
# -*- coding: utf-8 -*-

# Define your item pipelines here
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: http://doc.scrapy.org/en/latest/topics/item-pipeline.html

import codecs
import json


class JsonWriterPipeline(object):
    def __init__(self):
        self.file = codecs.open('items.json', mode = 'wb', encoding = 'utf-8')

    def process_item(self, item, spider):
        line = json.dumps(dict(item)) + "\n"
        self.file.write(line.decode('unicode_escape'))
        return item
```

Error information
```bash
2016-03-16 00:03:39 [scrapy] ERROR: Error processing {'records': [{'en_kicker': u'Sinosphere'}]}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/linzhen/OneDrive/Source/newsCrawler/newsCrawler/pipelines.py", line 17, in process_item
    line = json.dumps(dict(item)) + "\n"
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File 
![qq20160316-0 2x](https://cloud.githubusercontent.com/assets/4090783/13784812/a6394e30-eb0b-11e5-9753-4fb1bfd3530b.png)
"/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {'en_kicker': u'Sinosphere'} is not JSON serializable
```

![item variables](https://cloud.githubusercontent.com/assets/4090783/13784830/b4108b9a-eb0b-11e5-81ce-709205b24f97.png)

**Comment by kmike** [comment] 2016-03-29 22:02
This is weird because `json.dumps({'en_kicker': u'Sinosphere'})` works fine for me. What is in your items, do they have additional fields which are not in a traceback?

Either way, it doesn't look like a Scrapy bug, so I'm closing this issue; you may have better luck getting help at http://stackoverflow.com/ (use "scrapy" tag for your question).

**Closed by kmike** 2016-03-29 22:02 UTC

**Comment by peter-wang-wsl** [comment] 2017-03-14 06:57
@kmike i think if you try json.dumps({'records': [{'en_kicker': u'Sinosphere'}]}), then you will get the same error

**Comment by peter-wang-wsl** [comment] 2017-03-14 07:56
@kmike json.dumps({'records': [{'en_kicker': u'Sinosphere'}]}) is ok, but if {'records': [{'en_kicker': u'Sinosphere'}]} as a item(for example json.dumps(RecodeItem)),then get the error

**Comment by kmike** [comment] 2017-03-14 09:50
@peter-wang-wsl could you please provide a full example?

**Comment by peter-wang-wsl** [comment] 2017-03-14 09:57
@kmike 
example
===================================
file: item.py
class QAMainItem(scrapy.Item):
    title = scrapy.Field()
    type = scrapy.Field()
    ask_time = scrapy.Field()
    asker = scrapy.Field()
    question_content = scrapy.Field()
    answer_num = scrapy.Field()
    answers = scrapy.Field()
class QAAnswerItem(scrapy.Item):
    answer = scrapy.Field()
    answer_type = scrapy.Field()
    answer_time = scrapy.Field()
    answer_content = scrapy.Field()
--------------------------------------------
file:spider.py
    def store_item(self, question, title, type):
        ask_time = question.xpath("div[1]/h1/b/text()").re(r'\d+/\d+/\d+ \d+:\d+:\d+')[0]
        asker = question.xpath("div[1]/h1/span/text()").extract_first()
        question_content = question.xpath("div[1]/p/text()").extract_first().strip()
        answer_num = question.xpath("div[1]/p/span/text()").re(r'\d+')[0]
        question_item = QAMainItem()
        question_item['ask_time'] = ask_time
        question_item['asker'] = asker
        question_item['question_content'] = question_content
        question_item['answer_num'] = answer_num
        question_item['title'] = title
        question_item['type'] = type

        answer_list = []
        for index, qa in enumerate(question.xpath("div")):
            if 0 == index:
                pass
            else:
                answer_item = QAAnswerItem()
                answer_item['answer'] = qa.xpath("h2/text()").re(r'\w+')[0]
                answer_item['answer_type'] = qa.xpath("h2/strong/text()").extract_first()
                answer_item['answer_time'] = qa.xpath("h2/b/text()").extract_first()
                answer_item['answer_content'] = qa.xpath("p/text()").extract_first().strip()
                answer_list.append(answer_item)
        question_item['answers'] = answer_list
        yield question_item
----------------------------------------------------
file:pipeline.py  class:JsonWriterPipeline
    def process_item(self, item, spider):
        line = json.dumps(dict(item), indent=4) 
        self.file.write(line.decode("unicode_escape") + ',' + "\n")
        return item

**Comment by peter-wang-wsl** [comment] 2017-03-14 12:32
@kmike @danbao i get the solution! it is use defaut in json.dumps().
example
1.item.py
change QAAnswerItem to class QAAnswer(object)
2.pipeline.py class:JsonWriterPipeline
use json.dumps(dict(item), indent=4, default=self.answer2dict)

    def answer2dict(self, std):
        return {
                    'answer':std.answer,
                    'answer_type':std.answer_type,
                    'answer_time':std.answer_time,
                    'answer_content':std.answer_content
               }

**Comment by kmike** [comment] 2017-03-14 17:22
Aha, I think the problem is that 

1. you're using json.dumps which is not aware of Scrapy items;
2. your data has nested Scrapy items, so dict(item) doesn't convert everything to plain dicts;
3. by default Scrapy items have repr which is the same as dict, so it is not easy to spot the issue.

Scrapy's built-in json export utilities use ScrapyJSONEncoder which supports scrapy Items and a few other objects - see https://github.com/scrapy/scrapy/blob/master/scrapy/utils/serialize.py. You can do the same: create an encoder and use it in 'json.dumps':

```py
from scrapy.utils.serialize import ScrapyJSONEncoder
encoder = ScrapyJSONEncoder()
# ...
json.dumps(..., cls=encoder)
```

Also, I think `line.decode('unicode_escape')` is not correct; use `ensure_ascii=False` json.dumps argument if you want non-ascii data to be unescaped.

**Comment by peter-wang-wsl** [comment] 2017-03-15 00:17
@kmike thanks your answer and suggestion

**Comment by peter-wang-wsl** [comment] 2017-03-15 00:42
@kmike I try it.And your sample need to be changed like below.

from scrapy.utils.serialize import ScrapyJSONEncoder
json.dumps(..., cls=ScrapyJSONEncoder)
