### ISSUE TITLE
invalid hostname

### ISSUE THREAD

**Issue by qq703048949** [scrapy/scrapy#3747] opened 2019-04-17 03:03 UTC
when I request http://tjw_161130192022480.company.qihuiwang.com/
return  this:    invalid hostname: tjw_161130192022480.company.qihuiwang.com,
I don't know how to solve this question ! 
hlep me !

**Comment by Gallaecio** [comment] 2019-04-17 04:27
I can reproduce this issue as well.

**Comment by Gallaecio** [comment] 2019-04-17 04:28
This is a duplicate of #3321.

**Closed by Gallaecio** 2019-04-17 04:28 UTC
Labels: bug
