### ISSUE TITLE
Cannot override default Connection header

### ISSUE THREAD

**Issue by RavenHustler** [scrapy/scrapy#3093] opened 2018-01-26 07:46 UTC
Cannot override the default `Connection: close` header of scrapy requests. I want to scrape a site for which I need to send `Connection: keep-alive` headers and remove the default `Connection: close` header.

Tried using custom settings, custom headers and default headers to change `Connection: close` to `Connection: keep-alive` but it instead merges and sends two `Connection` headers.

It works in scrapy shell but not when used in a spider.

I used Fiddler to check the headers scrapy was sending. Please use Fiddler or any other packet sniffing tool to check the headers as it works fine in scrapy shell.

Below is the different things I tried:
Using custom settings:
```
custom_settings = {
        'DEFAULT_REQUEST_HEADERS': {
            'Connection': 'keep-alive'
        }
    }
```

Using custom headers:
```
headers = {"Connection": "keep-alive"}

for url in urls:
        yield scrapy.Request(url=url, callback=self.parse, headers=headers)
```

Changing default header settings:
```
DEFAULT_REQUEST_HEADERS = {
  'Connection': 'keep-alive',
}
```

**Comment by cathalgarvey** [comment] 2018-02-20 13:25
Related issue, which I marked as Non-Reproducible a few days back and we closed: #2970. If this is affecting some people, verifiable with packet sniffers, but not others, then there's definitely something strange going on.

Could you help me debug this by providing the following?

- [ ] Your OS platform
- [ ] Your scrapy version
- [ ] Source code for a spider that replicates this bug

Thank you!

**Comment by abitduck** [comment] 2018-09-25 10:03
I found the problem with [eventlet](https://github.com/eventlet/eventlet/blob/77bccbe48d4d9a46982b2e0503e76784e76b066a/eventlet/wsgi.py#L485). eventlet's connection header is independent with app' s header.

With duplicate header is OK? we can refer [this](https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable)

**Comment by Gallaecio** [comment] 2019-08-14 09:26
Closing due to a lack of feedback from the original author.

**Closed by Gallaecio** 2019-08-14 09:26 UTC
Labels: bug, needs more info
