### ISSUE TITLE
Unhelpful traces when there's an error in the pipeline

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#2362] opened 2016-10-26 15:37 UTC
I had a pretty basic error in my pipeline (i'd forgotten to `import os`).
However, rather than get the customary `NameError: name 'os' is not defined`, I instead receive a long, drawn-out Twisted error:

```
2016-10-26 16:34:15 [scrapy] INFO: Closing spider (shutdown)
Unhandled error in Deferred:
2016-10-26 16:34:15 [twisted] CRITICAL: Unhandled error in Deferred:


Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scrapy\commands\crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "C:\Python27\lib\site-packages\scrapy\crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "C:\Python27\lib\site-packages\scrapy\crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Python27\lib\site-packages\scrapy\crawler.py", line 87, in crawl
    yield self.engine.close()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 100, in close
    return self._close_all_spiders()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 340, in _close_all_spiders
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 298, in close_spider
    dfd = slot.close()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 44, in close
    self._maybe_fire_closing()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.
2016-10-26 16:34:15 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Python27\lib\site-packages\scrapy\crawler.py", line 87, in crawl
    yield self.engine.close()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 100, in close
    return self._close_all_spiders()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 340, in _close_all_spiders
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 298, in close_spider
    dfd = slot.close()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 44, in close
    self._maybe_fire_closing()
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
AssertionError: Tried to stop a LoopingCall that was not running.

```

Without useful traceroutes this is going to make it _very_ difficult to develop a spider using pipelines.

Could scrapy be made to more transparently handle failures in pipelines please? Thanks.

Scrapy 1.2

**Comment by redapple** [comment] 2016-10-26 16:30
Thanks for your feedback @mohmad-null !
We're always looking for new contributors.
Do you want to us improve its tracebacks?

**Comment by mohmad-null** [comment] 2016-11-02 13:19
@redapple  - its taken me several weeks just to get a basic scraper working; I wouldn't have the faintest notion where to begin trying to resolve this.

**Comment by redapple** [comment] 2016-11-04 14:17
@mohmad-null , I cannot reproduce this behavior on Linux, with scrapy 1.2 and Python 2.7 or 3.5.
If I include statements using `os` without importing it:
- either in pipeline `process_item` or 
- or in spider `__init__`, `start_requests` or callback methods

I can always see `NameError: name 'os' is not defined` in my console.

Can you tell us in which component or component's method you had this missing import issue so we can try reproducing it?
Also, the output of `scrapy version -v` can help.
What are you using to run your crawls? `scrapy crawl`? scrapyd? a script?

Examples of what I see:
```
$ scrapy crawl example
2016-11-04 15:05:22 [scrapy] INFO: Scrapy 1.2.1 started (bot: cryptictracebacks)
2016-11-04 15:05:22 [scrapy] INFO: Overridden settings: {'SPIDER_MODULES': ['cryptictracebacks.spiders'], 'BOT_NAME': 'cryptictracebacks', 'ROBOTSTXT_OBEY': True, 'NEWSPIDER_MODULE': 'cryptictracebacks.spiders'}
2016-11-04 15:05:22 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole']
Unhandled error in Deferred:
2016-11-04 15:05:22 [twisted] CRITICAL: Unhandled error in Deferred:

2016-11-04 15:05:22 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/twisted/internet/defer.py", line 1260, in _inlineCallbacks
    result = g.send(result)
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/home/paul/cryptictracebacks/cryptictracebacks/spiders/example.py", line 11, in __init__
    dir_path = os.path.dirname(os.path.realpath(__file__))
NameError: name 'os' is not defined
```
or
```
$ scrapy crawl example
2016-11-04 15:12:03 [scrapy] INFO: Scrapy 1.2.1 started (bot: cryptictracebacks)
2016-11-04 15:12:03 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'cryptictracebacks.spiders', 'SPIDER_MODULES': ['cryptictracebacks.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'cryptictracebacks'}
2016-11-04 15:12:03 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-11-04 15:12:03 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-11-04 15:12:03 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-11-04 15:12:03 [scrapy] INFO: Enabled item pipelines:
['cryptictracebacks.pipelines.CryptictracebacksPipeline']
2016-11-04 15:12:03 [scrapy] INFO: Spider opened
2016-11-04 15:12:03 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-11-04 15:12:03 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-11-04 15:12:03 [scrapy] DEBUG: Crawled (404) <GET https://www.example.com/robots.txt> (referer: None)
2016-11-04 15:12:03 [scrapy] DEBUG: Crawled (200) <GET https://www.example.com> (referer: None)
2016-11-04 15:12:04 [scrapy] ERROR: Spider error processing <GET https://www.example.com> (referer: None)
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 649, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/paul/cryptictracebacks/cryptictracebacks/spiders/example.py", line 20, in parse
    dir_path = os.path.dirname(os.path.realpath(__file__))
NameError: global name 'os' is not defined
2016-11-04 15:12:04 [scrapy] INFO: Closing spider (finished)
2016-11-04 15:12:04 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 436,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 1899,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/404': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 11, 4, 14, 12, 4, 172305),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'response_received_count': 2,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/NameError': 1,
 'start_time': datetime.datetime(2016, 11, 4, 14, 12, 3, 181381)}
2016-11-04 15:12:04 [scrapy] INFO: Spider closed (finished)
```

**Comment by redapple** [comment] 2016-11-04 14:47
I found a way to reproduce this:
if a pipeline `open_spider` method raises an exception, for example this bogus one:

```
$ cat cryptictracebacks/pipelines.py
# -*- coding: utf-8 -*-

class CryptictracebacksPipeline(object):

    def open_spider(self, spider):
        a = int(spider)/0

    def process_item(self, item, spider):
        return item

```

you get this exception back:
```
$ scrapy crawl example
2016-11-04 15:39:06 [scrapy] INFO: Scrapy 1.2.1 started (bot: cryptictracebacks)
(...)
2016-11-04 15:39:06 [scrapy] INFO: Enabled item pipelines:
['cryptictracebacks.pipelines.CryptictracebacksPipeline']
2016-11-04 15:39:06 [scrapy] INFO: Spider opened
2016-11-04 15:39:06 [scrapy] INFO: Closing spider (shutdown)
Unhandled error in Deferred:
2016-11-04 15:39:06 [twisted] CRITICAL: Unhandled error in Deferred:

2016-11-04 15:39:06 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/crawler.py", line 87, in crawl
    yield self.engine.close()
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 100, in close
    return self._close_all_spiders()
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 340, in _close_all_spiders
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 298, in close_spider
    dfd = slot.close()
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 44, in close
    self._maybe_fire_closing()
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
AssertionError: Tried to stop a LoopingCall that was not running.

```

**Comment by kmike** [comment] 2016-11-04 18:14
@redapple out of curiosity, does it print the actual exception (maybe not as the last one) if executed in Python 3?

**Comment by kmike** [comment] 2016-11-04 18:16
See also: https://github.com/scrapy/scrapy/issues/2011, it looks like these issues are the same.

**Comment by redapple** [comment] 2016-11-07 13:55
@kmike , in Python 3; you get a bit more info but not the actual problematic line it seems:

```
$ scrapy crawl example
2016-11-07 14:52:46 [scrapy] INFO: Scrapy 1.2.1 started (bot: cryptictracebacks)
(...)
2016-11-07 14:52:47 [scrapy] INFO: Enabled item pipelines:
['cryptictracebacks.pipelines.CryptictracebacksPipeline']
2016-11-07 14:52:47 [scrapy] INFO: Spider opened
2016-11-07 14:52:47 [scrapy] INFO: Closing spider (shutdown)
Unhandled error in Deferred:
2016-11-07 14:52:47 [twisted] CRITICAL: Unhandled error in Deferred:

2016-11-07 14:52:47 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/crawler.py", line 74, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'ExampleSpider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/crawler.py", line 87, in crawl
    yield self.engine.close()
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 100, in close
    return self._close_all_spiders()
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 340, in _close_all_spiders
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 340, in <listcomp>
    dfds = [self.close_spider(s, reason='shutdown') for s in self.open_spiders]
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 298, in close_spider
    dfd = slot.close()
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 44, in close
    self._maybe_fire_closing()
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/scrapy/core/engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "/home/paul/.virtualenvs/scrapy12.py35/lib/python3.5/site-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
AssertionError: Tried to stop a LoopingCall that was not running.
```

**Comment by redapple** [comment] 2016-11-08 12:33
Fixed in https://github.com/scrapy/scrapy/pull/2382

**Closed by redapple** 2016-11-08 12:33 UTC
Labels: bug, help-wanted
