### ISSUE TITLE
Logging can't format stack trace with non-ascii chars on Python 2

### ISSUE THREAD

**Issue by tlinhart** [scrapy/scrapy#3161] opened 2018-03-09 07:28 UTC
Hi,

I experience the same issue as described in #1602. However, I'm not using Django.

The stats look like this:

```
{'downloader/request_bytes': 47621,
 'downloader/request_count': 103,
 'downloader/request_method_count/GET': 103,
 'downloader/response_bytes': 1162618,
 'downloader/response_count': 103,
 'downloader/response_status_count/200': 101,
 'downloader/response_status_count/302': 2,
 'dupefilter/filtered': 2,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 3, 9, 2, 3, 15, 748633),
 'httpcache/firsthand': 72,
 'httpcache/hit': 31,
 'httpcache/miss': 72,
 'httpcache/store': 72,
 'item_scraped_count': 48,
 'log_count/DEBUG': 215,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'memusage/max': 121434112,
 'memusage/startup': 69783552,
 'mongodb/item_stored_count': 48,
 'request_depth_max': 3,
 'response_received_count': 101,
 'scheduler/dequeued': 102,
 'scheduler/dequeued/memory': 102,
 'scheduler/enqueued': 102,
 'scheduler/enqueued/memory': 102,
 'spider_exceptions/AttributeError': 1,
 'start_time': datetime.datetime(2018, 3, 9, 2, 0, 52, 510449)}
```

But there's no mention about `AttributeError` (or any other error) in the log.

I'm executing the spiders on Scrapyd instances running in Docker container. This is the first two lines of the log showing components' versions:

```
2018-03-09 02:00:52 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: realestate)
2018-03-09 02:00:52 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.7, cssselect 1.0.3, parsel 1.3.1, w3lib 1.18.0, Twisted 17.9.0, Python 2.7.12 (default, Nov 20 2017, 18:23:56) - [GCC 5.4.0 20160609], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial
```

There's nothing special in the `settings.py`, but I can provide it if needed.

**Comment by ayushmankoul** [comment] 2018-03-14 13:36
Hey, @cathalgarvey @kmike I am interested in solving this bug.Please help me to fix this bug.Any guidance would be surely helpful to me.Thank You

**Comment by cathalgarvey** [comment] 2018-03-15 14:25
Hi @ayushmankoul - Without understanding the problem, I don't think any of us can point to where it needs a fix. :)

@tlinhart - This is an interesting problem, but replicating it 'blind' would be very difficult. Is it possible for you to share your spider code, whether here or privately, so we can try and reduce it to a minimal failure case? Thanks!

**Comment by tlinhart** [comment] 2018-03-15 17:06
@cathalgarvey Sure, I can provide you with the spider code and complete log. Though, I'd prefer to share it privately. What's the best way to do it?

**Comment by cathalgarvey** [comment] 2018-03-16 10:27
Hey @tlinhart - could you send a copy to opensource@scrapinghub.com and reference this issue, please? We'll see whether we can debug it and minimise it, and I promise not to release any of your source code or include revealing details about its contents. :)

**Comment by tlinhart** [comment] 2018-03-16 11:13
Hi @cathalgarvey , I've just sent the email.

As I already stated, we execute spiders via Scrapyd in production. However, I've tried to run the spider from command line and here's the output:

```
$ scrapy crawl XXXXX -s ITEM_PIPELINES='{}' -s EXTENSIONS='{}' -s DUPEFILTER_DEBUG=1 -s HTTPCACHE_ENABLED=1 -s HTTPCACHE_EXPIRATION_SECS=38800 -o items.json --logfile XXXXX.log
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 874, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1229: ordinal not in range(128)
Logged from file scraper.py, line 158
```

I think this might be related to the issue.

**Comment by dangra** [comment] 2018-03-16 18:56
Thanks for sharing the code that causes the issue @tlinhart 

I managed to reproduce it with the following minimal spider:

```python
# -*- coding: utf-8 -*-
import scrapy


class Spider(scrapy.Spider):
    name = 'bug3161'
    start_urls = [
        "https://scrapy.org"
    ]

    def parse(self, response):
        u'příprav' in None.lower()
```

```$ scrapy runspider myspider.py --logfile foo.log
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 882, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 404: ordinal not in range(128)
Logged from file scraper.py, line 158```

```$ scrapy runspider myspider.py
2018-03-16 15:54:21 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-03-16 15:54:21 [scrapy.utils.log] INFO: Versions: lxml 4.2.0.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 2.7.10 (default, Jul 15 2017, 17:16:57) - [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Darwin-17.4.0-x86_64-i386-64bit
2018-03-16 15:54:21 [scrapy.crawler] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True}
2018-03-16 15:54:21 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2018-03-16 15:54:21 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-03-16 15:54:21 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-03-16 15:54:21 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-03-16 15:54:21 [scrapy.core.engine] INFO: Spider opened
2018-03-16 15:54:21 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-16 15:54:21 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-03-16 15:54:21 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://scrapy.org> (referer: None)
2018-03-16 15:54:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://scrapy.org> (referer: None)
Traceback (most recent call last):
  File "/Users/daniel/envs/test-scrapy-bug-JRmRrwNr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daniel/myspider.py", line 12, in parse
    u'příprav' in None.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
2018-03-16 15:54:21 [scrapy.core.engine] INFO: Closing spider (finished)
2018-03-16 15:54:21 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 209,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 14583,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 3, 16, 18, 54, 21, 734389),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 48529408,
 'memusage/startup': 48529408,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/AttributeError': 1,
 'start_time': datetime.datetime(2018, 3, 16, 18, 54, 21, 180960)}
2018-03-16 15:54:21 [scrapy.core.engine] INFO: Spider closed (finished)```

@ayushmankoul if you want to help, above is a starting point. thanks

**Comment by dangra** [comment] 2018-03-16 19:07
The problem is clearly that the non-ascii char can't be formatted in the stack trace. It can be a bug in Twisted or Python logger. 

The relevant part of Scrapy that triggers the bug is at https://github.com/scrapy/scrapy/blob/6cc6bbb5fc5c102271829a554772effb0444023c/scrapy/core/scraper.py#L154-L159

**Comment by dangra** [comment] 2018-03-16 22:18
As a note, it is only reproducible on Python 2.

It works fine under Python 3.6.4

```
~$ scrapy runspider myspider.py --logfile py3.log
~$ cat py3.log
2018-03-16 19:17:24 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-03-16 19:17:24 [scrapy.utils.log] INFO: Versions: lxml 4.2.0.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.4 (default, Mar  9 2018, 23:15:03) - [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Darwin-17.4.0-x86_64-i386-64bit
2018-03-16 19:17:24 [scrapy.crawler] INFO: Overridden settings: {'LOG_FILE': 'py3.log', 'SPIDER_LOADER_WARN_ONLY': True}
2018-03-16 19:17:24 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2018-03-16 19:17:24 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-03-16 19:17:24 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-03-16 19:17:24 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-03-16 19:17:24 [scrapy.core.engine] INFO: Spider opened
2018-03-16 19:17:24 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-16 19:17:24 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-03-16 19:17:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://scrapy.org> (referer: None)
2018-03-16 19:17:24 [scrapy.core.scraper] ERROR: Spider error processing <GET https://scrapy.org> (referer: None)
Traceback (most recent call last):
  File "/Users/daniel/envs/scrapy3/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daniel/myspider.py", line 12, in parse
    u'příprav' in None.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
2018-03-16 19:17:24 [scrapy.core.engine] INFO: Closing spider (finished)
2018-03-16 19:17:24 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 209,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 14584,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 3, 16, 22, 17, 24, 711239),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 49725440,
 'memusage/startup': 49725440,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/AttributeError': 1,
 'start_time': datetime.datetime(2018, 3, 16, 22, 17, 24, 196146)}
2018-03-16 19:17:24 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by ayushmankoul** [comment] 2018-03-17 04:08
Hey, @dangra Thank You for simplifying the problem.I will spend some time to fix this bug and come back to you.

**Comment by ayushmankoul** [comment] 2018-03-17 08:53
# Quick Fix for users
```# -*- coding: utf-8 -*-
import scrapy
import sys
reload(sys)
sys.setdefaultencoding('utf8')

class Spider(scrapy.Spider):
    name = 'bug3161'
    start_urls = ["https://scrapy.org"]
  
     def parse(self, response):
        u'příprav' in None.lower()

```
Hey, @dangra using the above code I was able to resolve the issue by making default encoding in the scripts and it successfully runs in Python 2.7.The other approach could be to change the encoding of the returned message in the scrapy library as suggested by you.I am working on it hopefully will resolve asap.Please look into the code and guide me if I am going in the wrong direction.Thank You

**Comment by tlinhart** [comment] 2018-03-17 10:13
That is weird. I have `PYTHONIOENCODING=utf_8` set in my profile but experience the issue. Or is that a different thing?

**Comment by ayushmankoul** [comment] 2018-03-18 03:52
Hey, @tlinhart Were you able to regenerate the same error using my code which has default encoding?

**Comment by cathalgarvey** [comment] 2018-03-21 14:08
As I understand things, then; this is a source-encoding issue? That seems strange, as the original failure case didn't seem to have any ambiguous non-ascii characters?

If it is an encoding issue, is there a way for Scrapy, as a framework, to enforce UTF-8 when loading spiders? I'm aware of the sys/reload method, and it's [widely discouraged](https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script#3828742).. but now that Python 2 is nearly dead (and encoding issues like this will die with it), perhaps a "bad" solution like `sys.setdefaultencoding` isn't out of the question?

**Comment by tlinhart** [comment] 2018-03-21 14:15
Well, saying that Python 2 is nearly dead is a daring statement :-) If I'm correct, it will be dead in around 20 months which is still quite a lot of time (not talking that only support will end, no real death).

**Comment by cathalgarvey** [comment] 2018-03-21 15:48
@tlinhart - Having a 20 month timeline for Python 2 does change how we view support and fixes, though. If you asked me if we should implement a brittle monkey-patch to temporarily solve an issue like this on a modern version of Python, I would of course refuse. But if it would temporarily make the problem go away for legacy code, until it's basically defunct, then I'd strongly consider it.

This all supposes that Scrapy continues to support Python 2 out to the actual EOL of Python 2, which hasn't been decided AFAIK. A quick monkey-patch, versus a planned real-fix that ends up overrunning whatever deprecation deadline we might set, is definitely preferable in my opinion.

**Comment by tlinhart** [comment] 2018-03-21 15:56
@cathalgarvey I understand your point, of course, don't take my upper note too seriously :-)

**Comment by kmike** [comment] 2018-03-21 20:45
I agree with @dangra that this is likely a bug in Twisted or Python logging - it looks like there is an implicit encoding/decoding somewhere, probably in a string formatting, and in such cases Python uses default encoding (which is very often ascii). A real fix is to make encoding/decoding explicit in a right place.

Calling `sys.setdefaultencoding` overrides this implicit encoding globally; it is a hack, not a proper solution, as it affects unrelated code. But that's good there is a workaround.

Not having `# encoding: utf-8` set in Python 2 when file is UTF-8 and contain non-ascii symbols is a bug in user code. I'm not sure Scrapy should enforce anything here. Having file encoded to cp1251 and marked with `# encoding: cp1251` is not a bug (though probably not a good idea either); not having an encoding defined at the top of the file and using system encoding is also not a bug (though not a good idea as well).

31 Dec 2019 (~ 19 months from now) not only support for Python 2 ends, but there won't be security updates from the Python team as well, even in the source form. Some distributions may choose to keep 2.x secure for a bit longer, but overall this time it looks like a real death sentence :)

Anyways, I'm not sure we should enforce "utf8-only!" rules at spider load time or suggest `sys.setdefaultencoding('utf8')` workaround "officially". The fix probably belongs to Twisted, or to Python stdlib in a worst case.

**Comment by tlinhart** [comment] 2018-03-22 05:35
Just one note - `# encoding: utf-8` was set at the top of the spider code in this case.

**Comment by Gallaecio** [comment] 2020-04-16 13:54
Closing given Python 2 support has been dropped.

**Closed by Gallaecio** 2020-04-16 13:54 UTC
Labels: Python 2, bug
