### ISSUE TITLE
Is noconnect really deprecated? https request over https proxy times out. http request over https proxy works as expected.

### ISSUE THREAD

**Issue by yash-fn** [scrapy/scrapy#5433] opened 2022-03-02 02:30 UTC
### Description
Possibly similar to #5286?

Following Curl commands:
```bash
$ curl --proxy 'https://user:pass@sub.domain.com:port' https://ipinfo.io/ip # https over https proxy
# yields proxy_ip
$ curl --proxy 'https://user:pass@sub.domain.com:port' http://ipinfo.io/ip # http over https proxy
# yields proxy_ip
$ curl http://ipinfo.io/ip # http
# yields home_ip
$ curl https://ipinfo.io/ip # https
# yields home_ip

```
Using Scrapy Shell
```python
fetch(scrapy.Request('https://ipinfo.io/ip', meta={'download_timeout': 5, 'proxy': 'https://user:pass@sub.domain.com:port'})) # https over https proxy
# Times out or hangs indefinitely if no timeout specified
fetch(scrapy.Request('http://ipinfo.io/ip', meta={'download_timeout': 5, 'proxy': 'https://user:pass@sub.domain.com:port'})) # http over https proxy
# yields proxy_ip
fetch(scrapy.Request('http://ipinfo.io/ip', meta={'download_timeout': 5})) # http
# yields home_ip
fetch(scrapy.Request('https://ipinfo.io/ip', meta={'download_timeout': 5})) # https
# yields home_ip
```

### Steps to Reproduce

1. fetch https request using https proxy

**Expected behavior:** response received

**Actual behavior:** scrapy hangs indefinitely or times out if timeout specified

**Reproduces how often:** 100%

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
```
Scrapy       : 2.4.1
lxml         : 4.7.1.0
libxml2      : 2.9.12
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:29:00) [GCC 9.4.0]
pyOpenSSL    : 22.0.0 (OpenSSL 1.1.1f  31 Mar 2020)
cryptography : 36.0.0
Platform     : Linux-5.4.0-100-generic-x86_64-with-glibc2.31
```
### Additional context
Conda environment.yml
```conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9.0
  - scrapy
  - brotlipy
  - zstandard
  - rich 
  - genanki
  - imagemagick
  - apsw
  - pip
  - pip:
    - m3u8
    - switch

```
<details>
<summary>`conda env export` output</summary>

```
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - apsw=3.37.0.r1=py310h4988143_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=21.4.0=pyhd8ed1ab_0
  - automat=20.2.0=py_0
  - bcrypt=3.2.0=py310h6acc77f_2
  - brotlipy=0.7.0=py310h6acc77f_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha00ac49_1009
  - cffi=1.15.0=py310h0fdd8cc_0
  - chevron=0.14.0=pyhd3deb0d_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - commonmark=0.9.1=py_0
  - constantly=15.1.0=py_0
  - cryptography=36.0.0=py310h9ce1e76_0
  - cssselect=1.1.0=py_0
  - dataclasses=0.8=pyhc8e2a94_3
  - expat=2.4.4=h9c3ff4c_0
  - fftw=3.3.10=nompi_h77c792f_102
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=ha180cfb_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.3.0=py310h6acc77f_1
  - future=0.18.2=py310hff52083_4
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - genanki=0.13.0=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h36c2ea0_2
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.50.0=h85b4f2f_1
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=3.3.1=hb4a5f5f_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagemagick=7.1.0_23=pl5321hb118871_0
  - incremental=21.3.0=pyhd8ed1ab_0
  - itemadapter=0.4.0=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h7f98852_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.8=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgd=2.3.3=h3cfcdeb_1
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libglib=2.70.2=h174f98d_2
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - librsvg=2.52.5=hc3c00ef_1
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h885dcf4_1
  - libxslt=1.1.33=h0ef7038_3
  - libzlib=1.2.11=h36c2ea0_1013
  - lxml=4.7.1=py310ha5446b1_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.3=h9c3ff4c_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - pango=1.48.10=h54213e6_2
  - parsel=1.6.0=py_0
  - pcre=8.45=h9c3ff4c_0
  - perl=5.32.1=1_h7f98852_perl5
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydispatcher=2.0.5=py_1
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - python=3.10.2=hc74c709_3_cpython
  - python_abi=3.10=2_cp310
  - pyyaml=6.0=py310h6acc77f_3
  - queuelib=1.6.2=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - rich=11.1.0=pyhd8ed1ab_0
  - scrapy=2.4.1=py310h06a4308_0
  - service_identity=18.1.0=py_0
  - setuptools=60.7.1=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - twisted=21.7.0=py310h6acc77f_1
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - w3lib=1.22.0=pyh9f0ad1d_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.11=h36c2ea0_1013
  - zope.interface=5.4.0=py310h6acc77f_1
  - zstandard=0.17.0=py310h6acc77f_0
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - iso8601==1.0.2
    - m3u8==1.0.0
    - switch==1.1.0
```

</details>

**Comment by yash-fn** [comment] 2022-03-02 14:56
Running proxy with `?noconnect` as follows:
```python
fetch(scrapy.Request('https://ipinfo.io/ip', meta={'download_timeout': 5, 'proxy': 'https://user:pass@sub.domain.com:port?noconnect'}))
```
Works as expected. i.e. I can run https request over https proxy. But I get following warning:
```python
ScrapyDeprecationWarning: Using HTTPS proxies in the noconnect mode is deprecated. 
If you use Crawlera, it doesn't require this mode anymore, so you should update scrapy-crawlera 
to 1.3.0+ and remove '?noconnect' from the Crawlera URL.
  warnings.warn("Using HTTPS proxies in the noconnect mode is deprecated. "
```

Thus users following those instructions get an unworkable proxy, where using noconnect solves the problem. Therefore, should noconnect really be marked deprecated?

**Comment by Gallaecio** [comment] 2022-03-02 15:17
Interesting.

I was under the impression that this option was only necessary for an old version of Crawlera (Zyte Smart Proxy Manager, nowadays).

The fact that Crawlera stopped needing this quite a while ago makes me wonder whether this is something we need to maintain, or it is really the proxy provider that needs to make changes on their end to not require this.

**Comment by wRAR** [comment] 2022-03-02 16:18
Last time we checked this, if I recall correctly, we found that noconnect was added to support old Crawlera and probably never used outside that, and also that nobody we asked really understands how would "true" HTTPS proxies (ones that don't use CONNECT but presumably keep two separate HTTPS connections?) work, or knows where is that documented and if these proxies actually exist. E.g. `mitmproxy` which we use in the test suite doesn't seem to support anything like that.

As I've never used the proxy providers mentioned in these reports I don't know how do they work, whether we need special support for that and whether this is related to that noconnect code. I agree that if there are real use cases for something we don't support we should research that and add support if possible.

**Comment by yash-fn** [comment] 2022-03-02 16:37
I am also not a proxy expert and am only able to repeat what I find on the internet. From what I gathered, 
```
http proxy with http url -> everyone understands
https proxy with http url -> traffic to proxy encrypted but proxy to host standard http
https proxy with https url -> must use connect. only way to keep client to host communications secure.
http proxy with https url -> must use connect. Initial request is standard http but afterwards is secured tls stream being forwarded unmodified.
```
The proxy scheme only specifies whether the client to proxy stream is encrypted. But otherwise http and https proxy work same. https over https proxy thus would double encrypt traffic between proxy and host whereas http proxy would only have single encrypted traffic as per host parameters. if target url is https, connect is a must. 

If the above is true, then could it possibly be that scrapy's connect tunneling is redundant to the underlying twisted request methods? i.e. twisted already automatically implements connect if target url is https since that is only way to achieve result. When scrapy attempts to add its own connect on top it is really sending a connect to host, which doesn't know what to do with it? Because when I directed the proxy url to a server I control with noconnect added, the proxy reports making a connect anyways. So even if scrapy is not adding a connect, something else is. But I also don't really know if I am interpreting this scenario correctly, so take with grain of salt.

**Comment by yash-fn** [comment] 2022-03-02 16:49
Also, not sure if this code is still relevant, but it appears here that some prior (or possibly still current?) code for crawlera-tools was adding the noconnect if not present.

https://github.com/scrapinghub/crawlera-tools/commit/f817503218a0d3c831ba9c761193b6459b966828

**Comment by Gallaecio** [comment] 2022-03-02 18:54
I can only say that Scrapy does the same thing when you use `http://` in the proxy URL and when you use `?noconnect` instead: https://github.com/scrapy/scrapy/blob/c316ca45a5b1b19622c96049c9378d8c45adba60/scrapy/core/downloader/handlers/http11.py#L292-L314

If you use `https://`, it goes the `CONNECT` way. `?noconnect` allows to keep the HTTPS protocol in the client-proxy connection while not using the `CONNECT` approach, so I am starting to think it makes sense to keep that option around, i.e. undeprecate it, given as it seems that there are proxies out there that only support that.

But I would like to know whether or not it is normal for the no-CONNECT HTTPS option to be supported by proxies, and if there is a way that this could be elegantly negotiated between Scrapy and the proxy, so that things work as expected without users needing to append `?noconnect` to the proxy URL. On the other hand, maybe the `?noconnect` approach is less secure (maybe it exposes all data to the proxy server?), in which case it is better to force users to include this in the URL, and to cover in the documentation about this option any security information users need to know when using this type of proxy connection.

**Comment by yash-fn** [comment] 2022-03-03 01:48
Oh nice. Thanks for the code reference. I'll experiment with it to see if I can learn anything more. Let's leave this open for like a week or so and see if anyone more experienced with this adds their two cents. If no one objects, then I'd say let's go ahead undeprecate it. I'm gonna be running a larger project soon with these proxies so if anything goes wrong I should see it. If it works fine, then probably safe enough. It'd also be nice to hear back from that torguard guy you referenced to see if his proxies also require noconnect. I'll also try and read some more documentation on how ssl proxies work to see if I can find a more definitive answer. Will keep you updated if I find/learn something. :-)

**Comment by yash-fn** [comment] 2022-03-03 02:02
I ran curl with -v to see how it negotiates the connect method with the commercial proxy:
```bash 
curl -v --proxy 'https://user:pass@sub.proxy.com:port' https://ipinfo.io/ip
```
<details>
<summary>Output</summary>

```
*   Trying xxx.xxx.xxx.xxx:port...
* Connected to sub.proxy.com (xxx.xxx.xxx.xxx) port port (#0)
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Proxy certificate:
*  subject: CN=*.proxy.com
*  subjectAltName: host "sub.proxy.com" matched cert's "*.proxy.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
* allocate connect buffer!
* Establish HTTP proxy tunnel to ipinfo.io:443
* Proxy auth using Basic with user 'USERDIGEST'
> CONNECT ipinfo.io:443 HTTP/1.1
> Host: ipinfo.io:443
> Proxy-Authorization: Basic AUTHDIGEST
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=ipinfo.io
*  start date: Feb 24 17:48:03 2022 GMT
*  expire date: May 25 17:48:02 2022 GMT
*  subjectAltName: host "ipinfo.io" matched cert's "ipinfo.io"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1681b20)
> GET /ip HTTP/2
> Host: ipinfo.io
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< access-control-allow-origin: *
< content-type: text/html; charset=utf-8
< content-length: 12
< date: Thu, 03 Mar 2022 01:52:58 GMT
< x-envoy-upstream-service-time: 0
< via: 1.1 google
< alt-svc: clear
< 
* Connection #0 to host sub.proxy.com left intact
PROXY_IP_ADDRESS
```

</details>

**Comment by Gallaecio** [comment] 2022-03-04 09:05
What happens if you set the `DOWNLOADER_CLIENT_TLS_METHOD` Scrapy setting to 'TLSv1.3'? (even if it does not work either, please see if the logs show any new error)

**Comment by yash-fn** [comment] 2022-03-06 03:36
Sorry for delay. I had a deadline that I needed to meet. But here are the results of your request:

```python
2022-03-05 21:33:07 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/__init__.py", line 52, in _load_handler
    dh = create_instance(
  File "/conda-env/lib/python3.10/site-packages/scrapy/utils/misc.py", line 167, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/http11.py", line 76, in from_crawler
    return cls(crawler.settings, crawler)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/http11.py", line 46, in __init__
    self._sslMethod = openssl_methods[settings.get('DOWNLOADER_CLIENT_TLS_METHOD')]
KeyError: 'TLSv1.3'
2022-03-05 21:33:07 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/__init__.py", line 52, in _load_handler
    dh = create_instance(
  File "/conda-env/lib/python3.10/site-packages/scrapy/utils/misc.py", line 167, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/http11.py", line 76, in from_crawler
    return cls(crawler.settings, crawler)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/http11.py", line 46, in __init__
    self._sslMethod = openssl_methods[settings.get('DOWNLOADER_CLIENT_TLS_METHOD')]
KeyError: 'TLSv1.3'
2022-03-05 21:33:08 [scrapy.core.scraper] ERROR: Error downloading <GET https://ipinfo.io/ip>
Traceback (most recent call last):
  File "/conda-env/lib/python3.10/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/conda-env/lib/python3.10/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 45, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/conda-env/lib/python3.10/site-packages/scrapy/utils/defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "/conda-env/lib/python3.10/site-packages/scrapy/core/downloader/handlers/__init__.py", line 74, in download_request
    raise NotSupported(f"Unsupported URL scheme '{scheme}': {self._notconfigured[scheme]}")
scrapy.exceptions.NotSupported: Unsupported URL scheme 'https': 'TLSv1.3'
```

**Comment by Gallaecio** [comment] 2022-03-07 09:05
Right, [we don’t seem to have support for that](https://docs.scrapy.org/en/latest/topics/settings.html#downloader-client-tls-method). Maybe that is the issue, that we need support for TLS 1.3.

**Comment by Gallaecio** [comment] 2022-03-07 09:14
Does cURL work if you force TLS 1.2? `curl --tlsv1.2 --tls-max 1.2 …`

**Comment by Gallaecio** [comment] 2022-03-08 09:21
> possibly some proxy providers are moving to only support new tls standard?

Sounds like it. Let us close this issue and track work on TLS 1.3 support instead. Thank you for your feedback!!!

Duplicate of #4821.

**Closed by Gallaecio** 2022-03-08 09:21 UTC
