### ISSUE TITLE
sos  filepipelines 302

### ISSUE THREAD

**Issue by fengfangqian** [scrapy/scrapy#2656] opened 2017-03-16 10:27 UTC
hi

    when i setting file_urls "http://m.baidu.com/api?action=redirect&token=kpyysd&from=1014090y&type=app&dltype=new&refid=2650327114&tj=soft_5845028_88031597_%E8%AF%AD%E9%9F%B3%E6%90%9C%E7%B4%A2&refp=action_search&blink=da5b687474703a2f2f7265736765742e39312e636f6d2f536f66742f436f6e74726f6c6c65722e617368783f616374696f6e3d646f776e6c6f61642674706c3d312669643d34313034393931c658&crversion=1"
    
   this url redirect 3  times so when i use scrap download it  the scrapy retrun 302  how can i setting  it can working ? please help me!
![qq 20170316182328](https://cloud.githubusercontent.com/assets/3350372/23991950/1795e90a-0a76-11e7-9b19-4128bfdb3914.png)

**Comment by kmike** [comment] 2017-03-16 10:34
Hey @fengfangqian,

There is a bug in media pipelines - redirects are considered failures. It is fixed in Scrapy master. You can either update to scrapy master now, or wait for 1.4 release. I'm closing it as a duplicate of https://github.com/scrapy/scrapy/issues/2004.

**Closed by kmike** 2017-03-16 10:34 UTC

**Comment by fengfangqian** [comment] 2017-03-17 06:17
Hey @kmike 
Thank you for your reply, I updated to scrapy master now, but why repeat the same link will always be downloaded, and the file name is very strange
![2](https://cloud.githubusercontent.com/assets/3350372/24031211/4a721f6e-0b1c-11e7-9a0b-4e6846de80c3.png)
![1](https://cloud.githubusercontent.com/assets/3350372/24031217/59656ddc-0b1c-11e7-8c83-bc2d6b2e438f.png)
