### ISSUE TITLE
Use twisted default resolver instead of ThreadedResolver to support IPv6

### ISSUE THREAD

**Issue by heroesm** [scrapy/scrapy#3528] opened 2018-12-11 15:02 UTC
twisted.internet.base.ThreadedResolver currently (18.9.1.dev0) uses socket.gethostbyname to do DNS resolution, which does not support IPv6.

Meanwhile, scrapy currently (1.5.0) uses ThreadedResolver to do DNS resolution, thus unable to crawl host name with IPv6 address only or pure IPv6 ip address.

https://github.com/scrapy/scrapy/blob/1fd1702a11a56ecbe9851ba4f9d3c10797e262dd/scrapy/resolver.py

Script to reproduce the scrapy exception:

```shell
if [ ! -d testvenv ]; then virtualenv -p python testvenv ; fi
. testvenv/bin/activate
pip install -q scrapy  # or install twisted and scrapy from source repository

python -m scrapy shell http://ipv6.google.com
# raises:
# twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: ipv6.google.com.

python -m scrapy shell http://[::1]  # no need for existing web server in [::1]:80
# raises:
# twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: ::1.
```

But the default resolver in recent twisted supports IPv6 well.

Delete `reactor.installResolver(self._get_dns_resolver())` in 
https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L289
and test again:
```
python -m scrapy shell http://ipv6.google.com
python -m scrapy shell http://[::1]
```
it works and no DNSLookupError exception raised.

Although CachingThreadedResolver is used to cache DNS query, I think that compatibility with IPv6 outweigh the requirement of in process DNS cache, or we can reimplement DNS cache using middleware. At least, how about supply a option for user to explicitly enable IPv6 support in case the `DNSCACHE_ENABLED = False`?
Regarding the timeout option in getHostByName, I think there should be other approaches to set DNS query timeout (I'm not familiar with twisted).

In deed, I tried creating PR to twisted to make `ThreadedResolver.getHostByName` use `getaddrinfo` to support IPv6, but after discussing with cdunklau in irc://freenode/twisted-dev , I realised it's a backward incompatible change and is unlikely to be accepted, then concluded that the best option is to use the the default IPv6 compatible resolver in twisted instead of antiquated `ThreadedResolver.getHostByName`.

(note: to use the new default resolver which is IPv6 compatible, the required Twisted version should also be updated)

**Comment by heroesm** [comment] 2018-12-11 15:04
related:
https://github.com/scrapy/scrapy/issues/1031
https://github.com/scrapy/scrapy/pull/1104
https://twistedmatrix.com/trac/ticket/9567
https://github.com/twisted/twisted/pull/1093/files

**Comment by heroesm** [comment] 2018-12-28 11:20
@kmike 
The default resolver now is `twisted.internet._resolver.GAIResolver`:

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/base.py#L1007

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/_resolver.py#L71

**Comment by Gallaecio** [comment] 2019-08-14 11:30
Closing as a duplicate of #1031

**Closed by Gallaecio** 2019-08-14 11:30 UTC
