### ISSUE TITLE
CrawlerRunnerTestCase.test_deprecated_attribute_spiders is flaky

### ISSUE THREAD

**Issue by s-sanjay** [scrapy/scrapy#4047] opened 2019-10-01 13:52 UTC
### Description

[test_deprecated_attribute_spiders is flaky it fails randomly in different environments.
see https://travis-ci.org/scrapy/scrapy/jobs/590415988 ]

### Steps to Reproduce

1. [just run the test in travis ci environment build]
2. [re trigger the build and you can see the test being flaky]

**Expected behavior:** [the test should pass reliably ]

**Actual behavior:** [test is flaky]

**Reproduces how often:** [for me it happened twice in 3 times but I don't have a concrete number. I see it happening in other pulls as well]

### Versions

1.7.0

**Comment by elacuesta** [comment] 2019-10-01 14:06
Closing as duplicate of #4014

**Closed by elacuesta** 2019-10-01 14:06 UTC
