### ISSUE TITLE
request_to_dict error when executing enqueue_request (Scheduler)

### ISSUE THREAD

**Issue by rafaelcapucho** [scrapy/scrapy#1990] opened 2016-05-14 06:36 UTC
Hello,

I was trying to implement the scrapy-redis, the problem was discussed over there but after some debugging I see that the problem could be in scrapy.

The redis_scheduler is simple: https://github.com/rolando/scrapy-redis/blob/master/scrapy_redis/scheduler.py

They use a simple queue.push(request):

```
    def enqueue_request(self, request):
        if not request.dont_filter and self.df.request_seen(request):
            return
        if self.stats:
            self.stats.inc_value('scheduler/enqueued/redis', spider=self.spider)
        self.queue.push(request)
```

After that, the request pass through 2 method:

```
    def push(self, request):
        """Push a request"""
        self.server.lpush(self.key, self._encode_request(request))

    def _encode_request(self, request):
        """Encode a request object"""
        return pickle.dumps(request_to_dict(request, self.spider), protocol=-1)
```

I have added 3 prints into scrapy `request_to_dict` to understand the inputs:

```
def request_to_dict(request, spider=None):
    """Convert Request object to a dict.

    If a spider is given, it will try to find out the name of the spider method
    used in the callback and store that as the callback.
    """
    cb = request.callback
    print('callback: ', cb)
    print('request: ', request)
    print('spider: ', spider)

    if callable(cb):
        cb = _find_method(spider, cb)
    eb = request.errback
    if callable(eb):
        eb = _find_method(spider, eb)
    d = {
        'url': to_unicode(request.url),  # urls should be safe (safe_string_url)
        'callback': cb,
        'errback': eb,
        'method': request.method,
        'headers': dict(request.headers),
        'body': request.body,
        'cookies': request.cookies,
        'meta': request.meta,
        '_encoding': request._encoding,
        'priority': request.priority,
        'dont_filter': request.dont_filter,
    }
    return d
```

Running the shell command It return:

```
callback: <bound method Deferred.callback of <Deferred at 0x7f3e13b69358>> 
request: <GET http://www.epocacosmeticos.com.br/any-url-goes-here>
spider: <EpocaCosmeticosSpider 'epocacosmeticos.com.br' at 0x7f3e13032d30>
```

This is the error that I found when running the shell command with the scrapy-redis scheduler:

`ValueError: Function <bound method Deferred.callback of <Deferred at 0x7f3e13b69358>> is not a method of: <EpocaCosmeticosSpider 'epocacosmeticos.com.br' at 0x7f3e13032d30>`

The error is generated by `_find_method`

```
def _find_method(obj, func):
    if obj:
        try:
            func_self = six.get_method_self(func)
        except AttributeError:  # func has no __self__
            pass
        else:
            if func_self is obj:
                return six.get_method_function(func).__name__
    raise ValueError("Function %s is not a method of: %s" % (func, obj))
```

The request is created by the shell command, why it can't be used into `request_to_dict`?

Using python 3.5.1 - scrapy 1.1.0,
Thank you

**Comment by rafaelcapucho** [comment] 2016-05-14 06:47
Probably, the request queued by shell into the scheduler should have a not callable callback value. 

But the value is actually:
`<bound method Deferred.callback of <Deferred at 0x7f3e13b69358>>`

But obviously, this callback isn't method member of my spider :-1:

**Comment by kmike** [comment] 2016-05-16 11:26
@rafaelcapucho right; scrapy currently supports only spider methods as callbacks if persistent request queue is used. So the issue is that persistent request queues can't be used with scrapy shell, right? 

Scrapy itself doesn't fail in this case: if request fail to serialize to on-disk queue it is kept in in-memory queue. I wonder if scrapy-redis should do the same.

**Comment by kmike** [comment] 2016-05-16 11:30
Let's say you managed to serialize this request and store it in scrapy-redis. What happens if this request is fetched by another process? How would it be able to resolve the Deferred and return control to the scrapy shell?

**Comment by kmike** [comment] 2016-05-19 08:45
I'm closing this ticket because it doesn't look like something we can fix in Scrapy. Feel free to reopen if you have ideas about how to do that.

**Closed by kmike** 2016-05-19 08:45 UTC
