### ISSUE TITLE
Scrapy logs [partial] when proxy is used

### ISSUE THREAD

**Issue by pawneetdev** [scrapy/scrapy#2086] opened 2016-07-04 04:10 UTC
Scrapy logs [partial] when using proxy to scrape and does not return any data. I am using proxymesh.

>  middleware.py

```
import base64

class ProxyMiddleware(object):
    process_request(self, request, spider):
    request.meta['proxy'] = "http://......"

    proxy_user_pass = "username:password"

    encoded_user_pass = base64.encodestring(proxy_user_pass)
    request.headers['Proxy-Authorization'] = 'Basic ' + encoded_user_pass
```

> settings.py

```
DOWNLOADER_MIDDLEWARES = {
    'scrapy.contrib.downloadermiddleware.httpproxy.HttpProxyMiddleware': 1,
    'mcaScrapy.middlewares.ProxyMiddleware': 100,
}
```

> Output

```
2016-05-02 11:30:06 [scrapy] DEBUG: Crawled (200) <GET http://example.com/....> (referer: http://example.com/....) ['partial']
2016-05-02 11:30:06 [scrapy] DEBUG: Crawled (200) <POST http://example.com/....> (referer: http://example.com/....) ['partial']
2016-05-02 11:30:06 [scrapy] DEBUG: Crawled (200) <POST http://example.com/....> (referer: http://example.com/....) ['partial']
```

**Comment by nyov** [comment] 2016-07-04 12:21
'partial' may mean potential dataloss on the connection. It doesn't imply a bug.
I've seen this flag for a long time on a local proxy, but never had any partial responses.
Maybe your proxy is simply dead? Investigate the on-the-wire data with tcpdump.

What `PotentialDataLoss` (`partial`) means is determined by twisted:

    PotentialDataLoss may be raised by a transfer encoding decoder's
    noMoreData method to indicate that it cannot be determined if the
    entire response body has been delivered.  This only occurs when making
    requests to HTTP servers which do not set Content-Length or a
    Transfer-Encoding in the response because in this case the end of the
    response is indicated by the connection being closed, an event which may
    also be due to a transient network problem or other error.

**Comment by pawneetdev** [comment] 2016-07-04 14:39
I tried using proxymesh with selenium, it worked fine. I am having a problem with scrapy.

**Comment by nyov** [comment] 2016-07-04 15:05
Can you add some debugging data?
Scrapy shell session with `response` object dumps, Wireshark pcap logs or dumps.
Otherwise it'll be impossible to debug.

**Comment by aorzh** [comment] 2016-09-09 21:09
any luck with this?

**Comment by pawneetdev** [comment] 2016-09-12 15:04
You can use other proxy services than proxymesh as proxymesh returns a pool of proxies. That's why I think it is causing problem. Works fine with any other proxy. You can disguise some sites by switching the rotating the user agent also.

**Comment by cathalgarvey** [comment] 2018-02-15 16:31
Hi folks, there's not enough information here I think, for us to figure out if it's a bug in Scrapy. A 'partial' response may indicate some mismatch between the length-related headers in the response, and the data returned by the proxy. Perhaps the proxy fails to send empty lines at the end of documents? Perhaps their compression code silently corrupts things?

Without a reproducible case, and no movement since 2016, I'll close this for now. But feel free to give us more information here and re-open it if something new would help us to find a bug or improve scrapy.

Thank you for contributing to Scrapy! :)

**Closed by cathalgarvey** 2018-02-15 16:31 UTC
Labels: not reproducible
