### ISSUE TITLE
UnicodeDecodeError from scraper.py 

### ISSUE THREAD

**Issue by pilgrim2go** [scrapy/scrapy#1588] opened 2015-11-09 04:11 UTC
Hi,

I'm using scrapy 1.0.3 in OSX and have following error when fetching.

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)
Logged from file scraper.py, line 237

```

Comment this line  in scrapyer.py removed the error.
```
            #logger.log(*logformatter_adapter(logkws), extra={'spider': spider})
```

What the issue is and how to solve it?

Thanks,
Van

**Comment by kalombos** [comment] 2016-01-18 07:02
That is what i found when i got the same error. When scrapy formats log mesaage it uses pprint module for items fields. Something like this:
 ```python
 u"Some unicode %s" % args.  # msg = msg % self.args actually
```
The problem is in the processing objects by pprint module which uses **repr** function for any objects that should be printed. If we would use unicode object then all would be fine:
```python
from pprint import pformat
print pformat(u'Это юникод')
print u'Formated string: %s' % pformat(u'Это юникод')

>>>u'\u042d\u0442\u043e \u044e\u043d\u0438\u043a\u043e\u0434'
>>>Formated string: u'\u042d\u0442\u043e \u044e\u043d\u0438\u043a\u043e\u0434'
```
But in my case i used django model in some fields of scrapy items and **repr** functions does not return unicode string for django model but returns just string:
```python
from pprint import pformat
class Test(models.Model):
    field = models.CharField(max_length=255)
    def __unicode__(self):
        return self.field
t = Test()
t.field = u'Это юникод'
print pformat(s)
print u'Formated string: %s' % pformat(s)

>>> <Test:  - Это юникод>
>>>Traceback (most recent call last):
  File "test.py", line 129, in <module>
    print u'Formated string: %s' % pformat(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 21: ordinal not in range(128)
```
Unfortunately I have not found any solution how to fix it.

**Comment by Digenis** [comment] 2016-01-19 08:57
@kalombos,

`repr()` and `pformat()` are meant to return string (bytes) in python 2 and unicode in python 3.
The problem is that django's `Model.__repr__` in python2 is returning 'utf8'-encoded strings
instead of safe 'unicode_escape'-encoded.
It does indeed return bytes but unsafe bytes. The print statements above only work because your terminal is set to utf8.

You can work around it by overriding the `__repr__` method:
```python
class Test(models.Model):
    def __repr__(self):
        return super(self.__class__, self).__repr__().decode('utf8').encode('unicode_escape')
```

**Comment by kalombos** [comment] 2016-01-19 09:12
@Digenis, thank for you snippet, i will use it in my project, but when i talked about solution i meant a solution for scrapy. I think it is wrong when scrapy just throws an error in output and can log nothing about the error.

**Comment by kmike** [comment] 2016-01-19 09:14
Well, yeah, I believe it is a django bug. In 2012 I tried to [point](https://groups.google.com/forum/#!searchin/django-developers/mikhail$20korobov/django-developers/_UN_4hBtJRI/2ajESIItEVoJ) these problems to django devs, but they were not keen to fixing them. utf-8 in `__repr__` works better than ascii when console encoding is utf-8, but breaks when it's not; it looks like django devs were more interested in providing nice experience for people with utf-8 system than supporting non-utf8 consoles.

**Comment by kmike** [comment] 2016-01-19 09:18
By the way, six library has the [same](https://bitbucket.org/gutworth/six/pull-requests/48/add-python_2_unicode_comaptible-from/diff) problematic `python_2_unicode_compatible` decorator implementation which defaults to utf-8 for `__repr__`.

**Comment by Digenis** [comment] 2016-01-19 10:22
@pilgrim2go, try this patch https://github.com/Digenis/scrapy/commit/dc15c12ba372f4cf1a5619e4fca8efe1ac4fa65d and run scrapy with --pdb.
Then tell us the types and values of `self.args`.
(See https://pymotw.com/2/pdb/#controlling-the-debugger
 if you can't work with the debugger)

**Comment by redapple** [comment] 2016-02-18 12:08
@pilgrim2go , did you get a chance to try @Digenis 's patch?

**Comment by redapple** [comment] 2016-09-19 10:57
As I understand this, it's a Django bug,
and there's a patch for it from @Digenis https://github.com/scrapy/scrapy/issues/1588#issuecomment-172779831
Thus, I'm closing it.

**Closed by redapple** 2016-09-19 10:57 UTC
