### ISSUE TITLE
ImportError: cannot import name log

### ISSUE THREAD

**Issue by natea** [scrapy/scrapy#942] opened 2014-11-08 19:56 UTC
I'm trying to ue scrapy with django-dynamic-scraper, and getting this error when I start up the Django server:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 102, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/nateaune/Dropbox/code/moocminder/moocminder/moocscraper/models.py", line 3, in <module>
    from scrapy.contrib.djangoitem import DjangoItem
  File "/usr/local/lib/python2.7/site-packages/scrapy/__init__.py", line 56, in <module>
    from scrapy.spider import Spider
  File "/usr/local/lib/python2.7/site-packages/scrapy/spider.py", line 6, in <module>
    from scrapy import log
ImportError: cannot import name log
```

**Comment by yasoob** [comment] 2015-03-20 14:38
Hey @kmike I guess it's fine to close this issue for now. The problem is probably solved and was in a previous release. If it occurs again we can reopen this issue. :+1:

**Closed** 2015-05-04 21:58 UTC

**Comment by rachelroll** [comment] 2019-07-19 05:34
@kmike Hi, I just installed the latest version of scrapy, but there is not log.py in  "/usr/local/lib/python3.7/site-packages/scrapy". So I still got the error: ImportError: cannot import name 'log' from 'scrapy' (/usr/local/lib/python3.7/site-packages/scrapy/__init__.py). Could you pls help with it.
I appreciate that very much.

**Comment by kmike** [comment] 2019-07-19 11:19
@rachelroll scrapy.log module has been removed in 1.7 version, after a long deprecation period. Please switch to stdlib logging.
