### ISSUE TITLE
MailSender fails silently

### ISSUE THREAD

**Issue by xiaohan2012** [scrapy/scrapy#730] opened 2014-05-23 12:59 UTC
I am using `scrapy.mail.MailSender` to send emails. The SMTP server I will use to send mails is not actually running. However, MailSender just fail silently.

It is better to give some messages to the developer if SMTP service is not available.

**Comment by tonal** [comment] 2017-02-27 04:49
https://github.com/twisted/twisted/pull/509/files

**Comment by sergiobellon** [comment] 2017-07-21 13:03
After many trials, I don't manage to make Scrapy Mail work. This is the exception encountered:

`
2017-07-21 14:58:51 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
    why = self._okresponse(self.code, b'\n'.join(self.resp))
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 1556, in esmtpState_challenge
    self._authResponse(self._authinfo, resp)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 1572, in _authResponse
    self.sendLine(base64.b64encode(resp))
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
builtins.TypeError: a bytes-like object is required, not 'str'`

This might relate to https://github.com/scrapy/scrapy/issues/950

**Comment by redapple** [comment] 2017-07-21 13:36
@sergiobellon , there a few open points to make Scrapy MailSender work on Python3.

- @rodrigc has a open PR to fix MailSender (#2671)
- I also found a couple of issues in Twisted (see https://github.com/scrapy/scrapy/issues/2375#issuecomment-299226510) that I needed to make it work.

One of the issues looks fixed (https://github.com/twisted/twisted/commit/7561226ba6b0f99ed9d6c89797a69c00429a27f8#diff-a9855c2d814357a59c3c09448f62c2ce) in Twisted trunk (but this fix is not in the latest released Twisted -- 17.5)

The other problem I found looks the same as yours. I'll need to test again against Twisted trunk to check if #2671 would fix it with next official Twisted.

**Comment by sergiobellon** [comment] 2017-07-21 15:05
I tested the Trunk branch of Twisted and I still get the same issue. @redapple do you recommend another library to send emails in Python 3.5?

**Comment by kmike** [comment] 2017-07-21 15:26
@sergiobellon until issues are fixed, you can use sync libraries from stdlib to send emails in Python 3; just make sure sending is fast (see https://github.com/scrapy/scrapy/issues/2375#issuecomment-261478617).

**Comment by sergiobellon** [comment] 2017-07-21 21:28
thanks @kmike, I got around with stdlib. Good luck with the fixes

**Comment by redapple** [comment] 2017-07-28 16:16
FTR, I commented on Twisted bug tracker: https://twistedmatrix.com/trac/ticket/9180#comment:5

**Comment by rodrigc** [comment] 2017-08-07 22:48
@redapple can you provide a scrapy config file which enables SMTP support
and reproduces the problem?
In this function: https://github.com/twisted/twisted/blob/trunk/src/twisted/mail/smtp.py#L1560

it looks like scrapy is using a class which implements `IClientAuthentication`
whose `challengeResponse` method returns `unicode` on Python 3,
but needs to return `bytes`.

I can't figure out which authenticator scrapy is using.  The `PLAINAuthenticator`
in Twisted returns bytes, so is scrapy using something else?

**Comment by redapple** [comment] 2017-08-08 13:34
I can reproduce the error with Python 3.6.1, using an SMTP server with TLS on port 587.
Scrapy in this case is using
```
factory = ESMTPSenderFactory(self.smtpuser, self.smtppass, self.mailfrom, \
            to_addrs, msg, d, heloFallback=True, requireAuthentication=False, \
            requireTransportSecurity=True)
```
Below are some debug prints in Twisted trunk:
```
esmtpState_challenge(code=334, resp=b'VXNlcm5hbWU6')
_authResponse(auth=<twisted.mail._cred.LOGINAuthenticator object at 0x7f2bdcf1b940>, challenge=b'VXNlcm5hbWU6')
resp(='***@****.com') = auth.challengeResponse('***********', b'Username:')
Unhandled Error
Traceback (most recent call last):
  File "/home/paul/src/twisted/src/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/paul/src/twisted/src/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/paul/src/twisted/src/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/paul/src/twisted/src/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/paul/src/twisted/src/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/paul/src/twisted/src/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/home/paul/src/twisted/src/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/paul/src/twisted/src/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/paul/src/twisted/src/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/paul/src/twisted/src/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/paul/src/twisted/src/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/paul/src/twisted/src/twisted/mail/smtp.py", line 996, in lineReceived
    why = self._okresponse(self.code, b'\n'.join(self.resp))
  File "/home/paul/src/twisted/src/twisted/mail/smtp.py", line 1558, in esmtpState_challenge
    self._authResponse(self._authinfo, resp)
  File "/home/paul/src/twisted/src/twisted/mail/smtp.py", line 1576, in _authResponse
    self.sendLine(base64.b64encode(resp))
  File "/home/paul/.virtualenvs/scrapy14.twistedtrunk.py3/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
builtins.TypeError: a bytes-like object is required, not 'str'

```

`twisted.mail._cred.LOGINAuthenticator` is used with login and password as native `str`

**Comment by redapple** [comment] 2017-08-08 13:55
@rodrigc , so sending mail is working in Scrapy with my use case, provided:
- username and password are passed as bytes,
- and that the message is also passed as bytes, like in your #2671 
We may need to document passing credentials as bytes or convert them internally before passing them to Twisted.

**Comment by rodrigc** [comment] 2017-08-16 20:03
@redapple do you have any users who have configured e-mail notification in Scrapy but have tried to use a *From:* address with non-ASCII characters?  I am testing a fix for this in Twisted and would appreciate feedback.

You can get the fix by doing:

```
python -m pip install --upgrade git+https://github.com/twisted/twisted@9250-rodrigc-mail
```

and report feedback at https://github.com/twisted/twisted/pull/867

**Comment by redapple** [comment] 2017-08-21 12:32
@rodrigc , I don't know. Maybe @xiaohan2012 , @sergiobellon can provide feedback.

**Comment by sergiobellon** [comment] 2017-08-22 15:48
@rodrigc I'll give it a try by the end of this week. I can't earlier because I don't have access to my pc.

**Comment by sergiobellon** [comment] 2017-08-27 16:02
`2017-08-27 18:00:36 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 1006, in lineReceived
    why = self._okresponse(self.code, b'\n'.join(self.resp))
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 1567, in esmtpState_challenge
    self._authResponse(self._authinfo, resp)
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/site-packages/twisted/mail/smtp.py", line 1583, in _authResponse
    self.sendLine(base64.b64encode(resp))
  File "/Users/ser/anaconda/envs/linkio/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
builtins.TypeError: a bytes-like object is required, not 'str'
`

@rodrigc I still get the same error

**Comment by redapple** [comment] 2017-08-27 16:04
@sergiobellon , thanks for the feedback.
Did you integrate the latest commits from https://github.com/scrapy/scrapy/pull/2671/commits ?
especially the converting of username and password to bytes?

**Comment by sergiobellon** [comment] 2017-08-27 17:00
@redapple thanks, before I only updated twisted. With #2671 it works!! well done

By the way, I just sent the PR #2901 to be able to send html emails with attachments.

**Comment by cathalgarvey** [comment] 2018-02-20 16:27
Hi folks, is this issue now resolved?

**Closed as completed** 2023-01-29 20:43 UTC
Labels: enhancement, help wanted, upstream issue
