### ISSUE TITLE
Problem using proxy with scrapy

### ISSUE THREAD

**Issue by Nizarazo** [scrapy/scrapy#3875] opened 2019-07-13 16:54 UTC
Hi

I am having problem using proxy with Scrapy, I have private proxy with HTTPS supported.

I tried with simplest spider without proxy with the following extensions:
EXTENSIONS = {
    'scrapy.extensions.telnet.TelnetConsole': None,
}
SPIDER_MIDDLEWARES = {
    'scrapy_splash.SplashDeduplicateArgsMiddleware': 100,
}
DOWNLOADER_MIDDLEWARES = {
    'scrapy_splash.SplashCookiesMiddleware': 723,
    'scrapy_splash.SplashMiddleware': 725,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
}

It worked fine 200 ok response

Then I configured the proxy as suggested in the documenation:
https://docs.scrapy.org/en/latest/topics/downloader-middleware.html?highlight=proxy#module-scrapy.downloadermiddlewares.httpproxy

1.
added this to the middle ware:
DOWNLOADER_MIDDLEWARES  = {
...
'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 1
...
}

2. I added the meta key proxy per each request as follows:
request = SplashRequest(url='https://www.example.com', callback=self.parse, endpoint='execute',
                        args={'wait': 1,
                              'lua_source': login_script,
                              'timeout':90,
                              }
                        )
request.meta['proxy'] = proxy
yield request

where proxy = 'https://username:password@proxyip:proxyport'

I am getting the error below when running scrapy:
2019-07-19 16:11:29 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.example.com via http://127.0.0.1:8050/execute> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL rout
ines', 'ssl3_get_record', 'wrong version number')]>]

I tried to fix by using the values of DOWNLOADER_CLIENT_TLS_METHOD such as:
'TLSv1.0' 'TLSv1.1' 'TLSv1.2' 'SSLv3' 
but it didn't change anything same error.

Thanks

**Comment by Gallaecio** [comment] 2019-07-15 13:00
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by Nizarazo** [comment] 2019-07-15 13:07
Hi Gallaecio

I couldn't find an answer to my question even I searched for a solution over google widely.
Can you help me out?

**Comment by Gallaecio** [comment] 2019-08-01 09:07
@Nizarazo May this be a duplicate of #1855?

**Comment by Nizarazo** [comment] 2019-08-03 22:01
Hi 

I tried the to solution described in #1855 it didn't solve the problem plus I tried the following solution described here:
https://support.scrapinghub.com/support/solutions/articles/22000219743-using-a-custom-proxy-in-a-scrapy-spider

I get the same error with wrong version number

I tried to use curl with the proxy I get the following:
curl -x https://username:password@proxyip:proxyport -L https://www.website.com

curl: (4) Unsupported proxy 'https://username:password@proxyip:proxyport', libcurl is built without the HTTPS-proxy support.

Any help is appreciated.

**Comment by Gallaecio** [comment] 2019-08-08 08:05
Does your HTTPS proxy require CONNECT headers? (see #3329)

**Comment by Gallaecio** [comment] 2019-09-17 06:43
Closing due to a lack of feedback.

**Closed by Gallaecio** 2019-09-17 06:43 UTC
Labels: bug
