### ISSUE TITLE
Where the tracebacks at?

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/scrapy#1229] opened 2015-05-13 18:06 UTC
run the spider with `scrapy runspider`, it also happens on `parse` and `crawl`.
https://gist.github.com/nramirezuy/65faa56c7eab1e117d77

**Comment by dangra** [comment] 2015-05-13 23:34
boto trying to read ec2 metadata :(

**Comment by nramirezuy** [comment] 2015-05-14 14:32
@dangra I added a test without boto installed and have no pipelines enabled.

**Comment by kmike** [comment] 2015-05-14 16:10
It seems the switch to Python logging made https://github.com/scrapy/scrapy/issues/1054 more visible.

**Comment by kmike** [comment] 2015-05-14 16:12
Is it a duplicate of https://github.com/scrapy/scrapy/issues/1099?

**Comment by nramirezuy** [comment] 2015-05-14 17:41
I'm not reporting the boto error, thats already reported on #1099. I'm reporting the missing traceback from the spider.

**Closed** 2015-05-15 18:00 UTC
