### ISSUE TITLE
Email throwing issue

### ISSUE THREAD

**Issue by Tanya312** [scrapy/scrapy#3758] opened 2019-04-25 13:02 UTC
Was trying to send email through scrapy.
Settings I used are:-
#settings for mail
MAIL_FROM = '...@gmail.com'
MAIL_HOST = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USER = '...@gmail.com'
MAIL_PASS = 'xxxxxxx'
MAIL_TLS = True
MAIL_SSL = False
 
Email was sent successfully. But the following exception is thrown;
2019-04-25 18:10:15 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/lib/python3.6/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/lib/python3.6/site-packages/twisted/protocols/tls.py", line 300, in _flushReceiveBIO
    self._flushSendBIO()
  File "/lib/python3.6/site-packages/twisted/protocols/tls.py", line 252, in _flushSendBIO
    bytes = self._tlsConnection.bio_read(2 ** 15)
builtins.AttributeError: 'NoneType' object has no attribute 'bio_read'

**Comment by heylouiz** [comment] 2019-04-25 15:45
Duplicate of #3478

**Comment by Gallaecio** [comment] 2019-04-26 10:02
@Tanya312 Please, close this issue or let us know how it differs from #3478.

**Closed** 2019-04-30 08:08 UTC
