### ISSUE TITLE
Error with pip install scrapy

### ISSUE THREAD

**Issue by d3prof3t** [scrapy/scrapy#1485] opened 2015-09-08 06:50 UTC
I ran the following command on my py2.7.10-devel ; pip install scrapy.
It didn't run completely and throwed errors as follows:

Failed building wheel for wheel
Failed building wheel for cryptography
Failed building wheel for lxml
Failed building wheel for cffi

I'm posting a paste of my error log, check it here: http://pastie.org/10404586

**Comment by Granitas** [comment] 2015-09-08 07:36
You seem to be missing some dependancies for those packages. 
Refer to: http://doc.scrapy.org/en/latest/intro/install.html

in your log you can see lines like `fatal error: ffi.h: No such file or directory` that means ffi.h is missing on your system. You should look for package `libffi` in your system repository (i.e. `apt` for ubuntu based systems) and download, would be something like `sudo apt-get install libffi4`.

**Comment by d3prof3t** [comment] 2015-09-08 09:45
I am using Fedora 22 and I do have libffi-3.1-7.fc22.x86_64 installed. So, I guess there is something more missing.

**Comment by kmike** [comment] 2015-09-08 10:53
@d3prof3t do you have development versions of the required packages installed? I.e. it is not enough to have libffi or libxml2 installed, you also need libffi-dev and libxml2-dev (or whatever names these packages use in Fedora).

**Comment by d3prof3t** [comment] 2015-09-13 14:19
@kmike Hey, I am actually trying to now port to python 3.4 and I did pip install scrapy, and the issue is bogus compiler found. Full error log here:-> http://pastie.org/10416881

**Comment by kmike** [comment] 2015-09-13 14:44
Hey @d3prof3t,

I think you need something like python3-dev and build-essential to make it work (package names are for Debian/Ubuntu).

Please note that Scrapy doesn't work in Python 3 yet; there is an ongoing effort to port it, but it is not yet usable for end users.

We don't have install instructions for Fedora / CentOS / RHEL because AFAIK no core developer use these distributions, and nobody from community contributed the instructions. 

Scrapy itself is a pure-Python package, so it should be pip installable on any OS. But it has dependencies like cffi and lxml which require a working build toolchain and specific system libraries installed. We document how to get them for some common environments (http://doc.scrapy.org/en/master/intro/install.html), but this is not Scrapy-specific: you need a working build environment for a lot of other packages (so this is a general Python question), and there are install instructions for Scrapy requirements available in requirements' docs themselves. See e.g. http://lxml.de/installation.html and http://cffi.readthedocs.org/en/latest/installation.html. Hope this helps. 

I'm closing this issue because it seems nobody is up to contributing and maintaining Fedora-specific instructions to Scrapy docs. I think you may get a better answer at http://stackoverflow.com/questions/tagged/scrapy.

**Closed by kmike** 2015-09-13 14:44 UTC

**Comment by AndrewMcSwain** [comment] 2017-07-17 19:41
too bad... i'm having this problem in busybox/termux =(

**Comment by redapple** [comment] 2017-07-17 21:14
@AndrewMcSwain , this issue is quite old and refers to Python 3, which wasn't supported back then. This has changed since Scrapy 1.1.
So you may want to create a new issue with your current situation.

**Comment by JohnnyQQQ** [comment] 2017-08-15 17:21
I'm trying to install it on python 3.6.1 getting the same error

**Comment by redapple** [comment] 2017-08-21 12:43
@JohnnyQQQ , you may want to open a new issue is this is reproducible with the [current recommended installation instructions](https://docs.scrapy.org/en/latest/intro/install.html).
