### ISSUE TITLE
signal spider_closed won't fire

### ISSUE THREAD

**Issue by chiyuan-goh** [scrapy/scrapy#1001] opened 2015-01-02 09:35 UTC
Have been trying to register my function to the signal spider_closed either from within my middleware or from the main function. So far, only spider_opened works. Scrapy==0.24.4 twisted==14.0.2
```
def abc():
    print 'works!'
```

```
class IgnoreDuplicatesMiddleware(object):
    @classmethod
    def from_crawler(cls, crawler):
        crawler.signals.connect(abc, signal=signals.spider_closed)
        crawler.signals.connect(abc, signal=signals.spider_opened)

    def on_spider_closed(self):
        self.conn.executemany("insert into crawled_urls(url) VALUES(?)", [(url) for url in self.fresh_meat])
        self.conn.close()
        print("Spider closed. Saving %s new urls to already-crawled db."%len(self.fresh_meat))

    def __init__(self):
        self.crawled_urls = set()
        self.fresh_meat = set()

        db = os.path.join(os.path.dirname(os.path.abspath(__file__)),  'scrapy.db')
        print db

        self.conn= sqlite3.connect(db)
        cur = self.conn.cursor()
        cur.execute("""SELECT url from crawled_urls;""")
        self.crawled_urls.update(i[0] for i in cur.fetchall())

        log.msg("There are %s already-crawled links." %len(self.crawled_urls), level=log.INFO)
        SignalManager(dispatcher.Any).connect(abc, signals.spider_closed)

    def process_request(self, request, spider):
        if request.url in self.crawled_urls:
            raise IgnoreRequest()
        else:
            self.crawled_urls.add(request.url)
            self.fresh_meat.add(request.url)
```

```
if __name__ == '__main__':
        spider = AlphaSpider()
        from scrapy.conf import settings
        settings.set('DOWNLOADER_MIDDLEWARES', {'download.healthscraper.middlewares.IgnoreDuplicatesMiddleware': 543,},
                        'cmdline')

        crawler = Crawler(settings)
        crawler.signals.connect(abc, signal=signals.spider_closed)
        crawler.configure()
        crawler.crawl(spider)
        crawler.start()

        py_observer = PythonLoggingObserver()
        py_observer.start()
        reactor.run()
```

**Comment by Curita** [comment] 2015-01-02 22:13
Hi @chiyuan-goh, there's a couple of issues with the code you provided. First of all, I'll assume you added a `log.start()` after the `crawler.start()` line otherwise the issue you pointed out is not reproducible (it works as it should). Testing if a signal is fired with a print statement is a little bit tricky, and it's actually the cause of the problem here, since the logger is closed on a `spider_closed` signal too. If you do something else, like raising an Exception on abc, you'll see that is actually fired.

You can start the logger with `log.start(logstdout=False)` or `log.start_from_crawler(crawler)` (since LOG_STDOUT is set to False by default) which will keep the standard output separated from the logger, and it will print regardless the logger's been closed.

Another issue with the code that's probably contributing to the misconception that the `spider_closed` signal is not fired is that the from_crawler method on the middleware should return an instance of that class. If a from_crawler is present its output will be used to obtain new instances, instead of `__new__`. Because of that, you're actually dealing with a middleware instance that is None (your from_crawler doesn't return anything) and none of its methods are called. You could fix that by returning `cls()` on from_crawler.

Hope this helps, I'll close this issue since it seems it's not a Scrapy problem, it's just been used wrongly, but feel free to open it again if that's not the case (and attach the spider so we can revise it). For usage concerns please refer to the support forum instead.

**Closed** 2015-01-02 22:20 UTC

**Comment by chiyuan-goh** [comment] 2015-01-05 09:28
@Curita, I tested it out using your recommendations to raising an exception instead of print. Also, I took moved the signal connection code from from_crawler to __init__.

I am still  having this problem. However, I forgot to clarify this problem occurred when **CTRL-C is issued**. So far, using the sample code from the documentations does not fire the signal handler.

```
spider = AlphaSpider()
settings = get_project_settings()
crawler = Crawler(settings)
crawler.signals.connect(reactor.stop, signal=signals.spider_closed)
crawler.configure()
crawler.crawl(spider)
crawler.start()
log.start( crawler=crawler,loglevel='DEBUG')
reactor.run()
``` 

However, when I used CrawlerProcess instead of crawler and reactor directly (took this code from ```scrapy.command.crawl.Command```), the signal handler is fired. 

```
spider = AlphaSpider()
settings = get_project_settings()
crawler_process = CrawlerProcess(settings)
crawler = crawler_process.create_crawler()
crawler.crawl(spider)
crawler_process.start()
```

**Comment by Curita** [comment] 2015-01-05 15:14
That's actually the excepted behavior since CrawlerProcess intercepts the CTRL-C, Twisted's reactor closes immediately otherwise. CrawlerProcess is an internal helper of Scrapy since this kind of manipulation of signals and the reactor is intrusive for a custom script, but is reasonable on a stand-alone framework. I have my doubts on documenting this class, but we should discuss it on a new issue.
