### ISSUE TITLE
[suggest ] `response.follow` should raise a exception when called on None or an empty string, instead of crawling the current page again

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3128] opened 2018-02-16 23:38 UTC
`response.follow` will raise a exception when url='' or none in stead of crawl the (base) page itself again.

none will use follow to crawl the source(base) page again right? all parsers will be passed without warning if that way.

thanks

**Comment by cathalgarvey** [comment] 2018-02-20 12:06
Hi @NewUserHa - I re-worded the title, to more clearly match what I _think_ you're suggesting. Can you confirm that I understood you correctly?

This does look like an odd behaviour, and I can think of plenty of ways that a `None` could creep in there in normal circumstances, sadly. I don't think this should be the expected behaviour; maybe for special pseudo-URLs like "#" or ".", but not IMO for the empty string or None?

**Comment by kmike** [comment] 2018-02-20 13:12
If url is '', Scrapy should follow the same page, this is an intended behavior. Doing otherwise would be non-standard, and can break a lot of things.

When is url None? Could you please give an example?

**Comment by cathalgarvey** [comment] 2018-02-20 13:20
Hi @kmike, take this contrived example:

```python
In [1]: fetch("http://httpbin.org/html")
2018-02-20 13:18:40 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://httpbin.org/html> (referer: None)

In [2]: response.css("a[href]::attr(href)").extract_first() is None
Out[2]: True

In [3]: fetch(response.follow(response.css("a[href]::attr(href)").extract_first()))
2018-02-20 13:18:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://httpbin.org/html> (referer: None)
```

Dupefilter should catch these cases, probably. But if Dupefilter is disabled for some reason and custom logic enabled, then it's possible for this to cause unexpected behaviour.

Good to know about empty-string being expected behaviour.

**Comment by kmike** [comment] 2018-02-20 13:42
Right, I would expect response.follow to raise an exception if None is passed, +1 to fix that. From docs:

```
        Return a :class:`~.Request` instance to follow a link ``url``.
        It accepts the same arguments as ``Request.__init__`` method,
        but ``url`` can be not only an absolute URL, but also
        
        * a relative URL;
        * a scrapy.link.Link object (e.g. a link extractor result);
        * an attribute Selector (not SelectorList) - e.g.
          ``response.css('a::attr(href)')[0]`` or
          ``response.xpath('//img/@src')[0]``.
        * a Selector for ``<a>`` or ``<link>`` element, e.g.
          ``response.css('a.my_link')[0]``.
```

^^ None is not one of accepted values.

**Comment by NewUserHa** [comment] 2018-02-20 14:49
@cathalgarvey yeah thanks.
@kmike it may be intended. but in the most situation, I suppose none intense to crawl the current page again just because of extract_first() return an empty string/link. and it's redundancy if check if it's empty every time I believe. ( even if the dupefilter works well, but it will hide the un-except result since few ppl will only check error message beside dupe message. PLUS the doc/tutorial never mention this problem)
thanks if you also fix empty string or note in doc

**Comment by cathalgarvey** [comment] 2018-02-20 14:59
Hey @NewUserHa - are you interested in contributing a fix for the issue? I might also mark it as "Good First Issue" otherwise, because I think this should be an easy enough fix:

1. Add a test case for passing `None` as an argument to `Response.follow`, expect it to throw a TypeError
1. Write code to check for None and throw that error when it happens in `Response.follow`. Or, better still, write a check for all expected types, and throw TypeError on any other type. e.g. `isinstance(url, (str, Selector, Link))`.

**Comment by kmike** [comment] 2018-02-20 15:42
@cathalgarvey currently response.follow throws ValueErrors for bad url argument; it makes sense for unsupported Selectors, though I'm not sure throwing it for SelectorList is the way to go.

**Comment by cathalgarvey** [comment] 2018-02-20 15:47
I assumed from the above paste, that SelectorList is an unsupported Type, so I reckon that's a `TypeError` (even though I see how that might confuse some users because its API is so similar to Selector). But, throwing a ValueError for Selectors that can't reasonably be "followed" makes sense.

Though, that raises questions like "Should we allow things with `src` attributes to be followed, not just `a[href]` elements?"

**Comment by kmike** [comment] 2018-02-20 16:44
> Though, that raises questions like "Should we allow things with src attributes to be followed, not just a[href] elements?"

Right - we started conservative, only with `<a>` elements at first, then added `<link>` elements in next Scrapy version. Following anything with `src` requires more discussion, and this discussion haven't started. I can see some disadvantages, e.g. a selector doesn't select `<a>` explicitly, a website uses an image for missing links, and selector selects this image, image URL would be followed instead of a link. It can be also more common to use file or media pipeline to download content linked via src attribute. So ideally, it should start with a use case from a real project, where code can be simplified if response.follow supports selectors with src.

**Comment by NewUserHa** [comment] 2018-02-21 00:30
@cathalgarvey thanks, and I created two pull requests.
#3131 #3132

**Comment by cathalgarvey** [comment] 2018-02-21 15:21
Hi @NewUserHa - We might as well keep the implementation and the tests together, could you merge one patch into the other patch? Thanks, will review these shortly. :)

**Comment by NewUserHa** [comment] 2018-02-21 16:20
@cathalgarvey done. #3131

**Comment by kmike** [comment] 2018-02-21 22:38
Fixed by https://github.com/scrapy/scrapy/pull/3131.

**Closed by kmike** 2018-02-21 22:38 UTC
Labels: bug, good first issue, help wanted

**Comment by NewUserHa** [comment] 2018-02-22 10:14
hmm, can the empty string url be discussed again?

**Comment by kmike** [comment] 2018-02-22 10:23
@NewUserHa from my point of view, it is clear that we shouldn't raise an exception for empty URLs in response.follow or response.urljoin. Clicking on a link with empty URL redirects you to the same page in browsers, and joining with an empty URL is a perfectly standard operation. Doing otherwise would be non-standard. 

The only argument so far against current way of handling "" is that response.follow will return a request to the same page. But I see it as an expected behavior, and something which can be desired. For example, you may do a POST request to submit a form to the same page. Or a website may require to re-send a request with different cookies. Or you may be using scrapy-splash, where URL fragment matters, and "" is not really the same page as a current page. Or you really want to send the request twice, e.g. to check if page changes. If we start raising an error for an empty string, it'd break al these use cases.

**Comment by NewUserHa** [comment] 2018-02-22 10:38
ok, the latter examples do make sense.
but there's a situation,
what if a detail page has few subpages and they are chained to on item(parser1, paser2..), and if one herf of a middle page between them missed, the parsers after that will process the previous page(the same one) silently.
thanks

**Comment by NewUserHa** [comment] 2018-02-22 10:58
well, the latter examples do make sense.
also, the None is the unexcepted behavior reason of what I wanted to say.
thanks

**Comment by NewUserHa** [comment] 2018-02-22 12:30
oh, I meant "It's None that the bad guy caused a situation what I wanted to say"
and thanks for the explanation from the rest part of your reply
