### ISSUE TITLE
scrapy.Request doesnt wait for loop

### ISSUE THREAD

**Issue by theduman** [scrapy/scrapy#3067] opened 2018-01-10 19:09 UTC
I fetch url and other parameters from database and use them in for loop and pass to scrapy.request() function but when i run the code i succesfully pass first element only. Scrapy can't get other elements of list. Here is my code

```py
class QuotesSpider(scrapy.Spider):
    name = "quotes"
    custom_settings = {
        'CONCURRENT_REQUESTS': 1,
    }
    def start_requests(self):
        sourceArr = []
        connection = db.connect()
        try:
            with connection.cursor() as cursor:
                # Read a single record
                sql = "SELECT `code`, `url`, `target`,`next` FROM `source`"
                cursor.execute(sql)
                result = cursor.fetchall()
        finally:
            connection.close()
        print(result)
        for i in result:
            source = Source(i['code'], i['url'], i['target'], i['next'])
            sourceArr.append(source)
        print(sourceArr)
        #for url in urls:
           #yield scrapy.Request(url=url, callback=self.parse)
        for s in sourceArr:
            print(s.target)
            yield scrapy.Request(url=s.url, meta={'target': s.target, 'next': s.next})
            print("slept")


    def parse(self, response):
        titlearr = []
        count = 0
        print(response.meta)
        for title in response.css(response.meta['target']):
            count += 1
            titlearr.append(title.css('p a::text').extract_first())
            #yield {'title': title.css('p a::text').extract_first()}
        print("total count " + str(count))
        print(titlearr)
        for next_page in response.css(response.meta['next']):
            yield response.follow(next_page, self.parse)
```

When i print response.meta i got target and next values for only first item. List contains more than 1 item. How can i make scrapy.Request() function wait for the next element to run?

**Comment by kmike** [comment] 2018-01-10 20:29
Hey @theduman,

I'm not sure what the problem is, because the example is not self-contained, and it is not clear for me from the issue description what you expected and what you've got. Could you please provide an example which shows a Scrapy bug? If you don't know if that's a bug or not, consider using https://stackoverflow.com/ instead (use tag "scrapy") - this is one of our official support channels.

**Comment by cathalgarvey** [comment] 2018-02-21 15:27
Hi @theduman - I'm closing this for now, but if you can confirm it's a bug please do reopen it. If you can confirm it, please try to provide a minimum example spider that shows how the bug works, so we can help fix it.

Thank you!

**Closed by cathalgarvey** 2018-02-21 15:27 UTC
Labels: needs more info

**Comment by tomkeegan** [comment] 2019-12-16 10:21
I'm running into the same issue right now. Did you ever find an explanation for why this was happening?

**Comment by theduman** [comment] 2019-12-16 11:00
@tomkeegan I don't remember exactly but it was related with `yield` somehow

**Comment by theshahzaibc** [comment] 2020-03-16 13:29
Don't send request in a loop. As you're using for loop. Just make one request and than the next request at the end of function parse.
I hope it will help you.
