### ISSUE TITLE
Bring back docstring comments in CrawlSpider

### ISSUE THREAD

**Issue by sseyboth** [scrapy/scrapy#2727] opened 2017-05-06 06:08 UTC
Can we please bring back the docstring comments in CrawlSpider that were removed in https://github.com/scrapy/scrapy/commit/e2290a5359ee80c75d8bcf8de8b6894e61fad83a? The code has zero comments now. Just spent two hours pulling my hair out trying to pass extra params down the crawler. Until I found the removed docstrings in this commit that where hugely helpful :) Thanks!

**Comment by kmike** [comment] 2017-05-06 08:28
Yep, +1 to fix it. See https://github.com/scrapy/scrapy/issues/713. So far nobody had found time to do it though, so pull requests are welcome.

**Comment by kanav-raina** [comment] 2018-02-21 21:10
hello  ,
Should i only have to add  this as a heading in crawling rules in scrapy/docs/topics/spiders.rst?

class:: Rule(link_extractor, callback=None, cb_kwargs=None, follow=None, process_links=None, process_request=None)

and define the process request and process_links .

**Comment by kanav-raina** [comment] 2018-02-22 07:54
When I visit   scrapy/docs/topics/spiders.rst , there is no .. class:: Rule(link_extractor, callback=None, cb_kwargs=None, follow=None, process_links=None, process_request=None)
but when i try to edit it ,it become visible  in line 377. Will you please check this?

**Comment by kanav-raina** [comment] 2018-02-23 20:32
please look at this @cathalgarvey

**Comment by cathalgarvey** [comment] 2018-02-23 20:49
Huh, you're right; I have no idea why that's happening! :)  I'm not very experienced with RST, it would be interesting to figure out why that's failing to display!

**Comment by kanav-raina** [comment] 2018-02-23 20:52
should i open an issue on this?

**Comment by kmike** [comment] 2018-02-23 21:08
@kanav-raina github doesn't process .rst docs fully, it doesn't support all Sphinx instructions, autodocs extensions, etc. This is not a bug. Please build Scrapy docs locally.

**Comment by kanav-raina** [comment] 2018-02-23 21:10
ok @kmike

**Comment by kanav-raina** [comment] 2018-02-23 21:11
@kmike  will you please brief  me a bit what I actually  have to do in this issue?

**Comment by kmike** [comment] 2018-02-23 21:24
@kanav-raina sure! So, currently CrawlSpider and related classes are documented in Scrapy docs. This in not convenient when checking CrawlSpider source code - methods should have docstrings. At the same time, duplicating the same documentation in two places (.rst files and method docstrings) is bad - it is very easy to modify one without changing the other. To solve it, Sphinx (software we use to build HTML docs from .rst files) provides [autodoc](http://www.sphinx-doc.org/en/stable/ext/autodoc.html) extension. 

Autodoc extension adds special processing instructions (automodule, automethod, etc.) which you can put to .rst files. When you build HTML from these .rst files, sphinx pulls docs from docstrings according to these instructions. This way you can only describe methods and classes once, in docstrings, and include this description in the documentation output.

So, a fix could look like https://github.com/scrapy/scrapy/pull/1291/files or https://github.com/scrapy/scrapy/pull/1149/files - note how a lot of text is removed from .rst file and moved to docstrings, and there are instructions to put this content back when building the docs.

It is not always possible (or desirable) to move everything to docstrings - some information is better suited to docs, e.g. tutorial-like parts, or notes which bring documentation page together. I haven't checked if this is the case for CrawlSpider, but you may have to choose what parts make sense as docstrings, and what parts don't. 

Anyways, I think an end result should be the following: CrawlSpider docs look the same after building, but most of the actual content is in docstrings now.

Here are instructions on how to build docs locally: https://github.com/scrapy/scrapy/tree/master/docs. I'm not 100% sure, but you also may need Scrapy installed.

**Comment by Cup0fCoffee** [comment] 2018-05-25 08:44
I tried to implement what @kmike suggested above. The issue is moving documentation as it is into the source file, makes you choose between leaving formatting for documentation or getting rid of it. The first option leads to hardly readable docstrings, but removing the formatting harms the documentation, thus neither of this options improves code comprehension and ease of getting familiar with it.

There is an option, to include short docstrings, load it into the documentation and then add more info in the documentation, but because of how Sphinx manages it, the documentation would become clunky and hard to read. Also, whenever something is changed, you would need to change it in two places.

I agree with @kmile that the documentation shouldn't be duplicated. I think, not having docstrings, but having clear and well-formatted documentation contributes to project long term.

**Comment by SlyCodePanda** [comment] 2018-12-17 09:51
Hi guys, is this still an issue that needs looking into? Or has someone already sorted this out?

**Comment by Gallaecio** [comment] 2019-03-08 14:17
Can we close this issue in favor of #713?

**Comment by aaditkamat** [comment] 2019-05-19 00:28
Hi guys, I would like to know what's the status of this issue?

**Comment by Gallaecio** [comment] 2019-05-20 19:46
I am currently working on bringing all API documentation to the source code, which includes this ticket.

Because it’s a lot, and all changes need to be reviewed by two people from the core team, I’m taking it step by step. Right now, I am waiting for https://github.com/scrapy/scrapy/pull/3706 to be reviewed and merged before I prepare a new request covering additional parts of the API.

**Comment by Gallaecio** [comment] 2019-08-19 15:47
Closing in favor of #713.

**Closed by Gallaecio** 2019-08-19 15:47 UTC
Labels: docs
