### ISSUE TITLE
Compare two scaped items for similarity

### ISSUE THREAD

**Issue by fbuchinger** [scrapy/scrapy#2584] opened 2017-02-22 22:05 UTC
Hi, I'm using scrapy to scrape a few historical HTML documents, which are ordered by date. later, I want to order the documents by their publication date and them in pairs of 2 for similarity. Is there an elegant way to do this in scrapy? 

Currently I'm trying to do this in my item pipeline (open the exported csv file in the close_spider method, parse it again, sort it, do the comparison). This feels rather clumsy. Is there a better way?

**Comment by kmike** [comment] 2017-02-22 22:55
Hey @fbuchinger,

We're using Scrapy issue tracker for bugs and feature requests; for support and usage questions we're using https://stackoverflow.com (use "scrapy" tag), so I'm closing this ticket. 

As for your question, I'd just create a separate script to post-process the result. Scrapy by design tries to output results row-by-row, without keeping the whole dataset in memory or reading past records from disk.

**Closed by kmike** 2017-02-22 22:55 UTC
