### ISSUE TITLE
scrapy always Starting new HTTP connection after crawl finished 

### ISSUE THREAD

**Issue by 3xp10it** [scrapy/scrapy#3068] opened 2018-01-11 01:14 UTC
I reopen [#3066][1] here,there are more details [here][2].

[1]: https://github.com/scrapy/scrapy/issues/3066
[2]: https://stackoverflow.com/questions/48182204/scrapy-always-starting-new-http-connection-after-crawl

**Comment by kmike** [comment] 2018-01-16 14:58
Hey @3xp10it,

It is hard to help you (both on stackoverflow and here) because there is no an easy way to reproduce this issue. To reproduce it one need to create some spider similar to yours, but you don't provide spider code. Someone suggested you to check https://stackoverflow.com/help/mcve - please check it! It is more effort, but it worths it; often when you have a minimal reproducable example you become able to solve a problem yourselves.

**Comment by cathalgarvey** [comment] 2018-02-20 13:38
Hi @3xp10it - Do you think you can provide a minimal example spider as @kmike suggested? I think we'll have to close this issue again otherwise, as we don't have the information we need to help debug it.

**Closed** 2018-02-21 15:25 UTC
Labels: needs more info
