### ISSUE TITLE
Question: Handling fragment identifiers

### ISSUE THREAD

**Issue by vella-nicholas** [scrapy/scrapy#4067] opened 2019-10-09 16:44 UTC
I am scraping a web page which has fragment identifiers (on the home page) for same page navigation. To make it clear I have this anchor tag `<a href="#idx1">1. Histoire</a>` and when you click on it you are taken to the 'Histoire' header on the same page.  `<h2 id="idx1">1. Histoire</h2>`.

Scrapy is following this fragment as `https://www.mysite.com/#idx1` (or `https://www.mysite.com#idx1`) and scraping the whole page again. Since this is the home page, it is yielding the same results as if it scraped the home page.

This behavior is not repeated for the rest of the fragment identifiers (I have many more). So for this anchor tag (on the same page) the above scenario is not manifested. `<a href="#idx2">2. Idées reçues</a>` -> Do not repeat itself for this.

Is this intentional or am I missing something?

```
import scrapy
from datetime import datetime
from netlinking.items import NetlinkItem
from urllib.parse import urlparse, urlunparse


class NetlinkingSpider(scrapy.Spider):
    name = "netlinking"
    referent_netloc = ''

    def __init__(self, url=None, *args, **kwargs):
        super(NetlinkingSpider, self).__init__(*args, **kwargs)
        parsed_uri = urlparse(url)
        self.referent_netloc = parsed_uri.netloc
        self.referent_netloc = self.referent_netloc.replace('www.', '')
        self.allowed_domains = [('%s' % self.referent_netloc)]
        self.start_urls = [('%s' % url)]

    def parse(self, response):
        for anchor in response.css('a'):
            netlink = NetlinkItem()
            netlink['anchor_text'] = anchor.css('a::text').get()
            netlink['referent_website'] = response.request.url
            netlink['referent_netloc'] = self.referent_netloc
            netlink['target_url'] = anchor.css('a::attr(href)').get()

            parsed_target_uri = urlparse(netlink['target_url'])
            if parsed_target_uri.netloc.strip() \
                    and (self.referent_netloc !=
                         parsed_target_uri.netloc.lower().replace('www.', '')):

                netlink['target_website'] = \
                    '{uri.scheme}://{uri.netloc}/'.format(
                    uri=parsed_target_uri)

                netlink['target_netloc'] = '{uri.netloc}'.format(
                    uri=parsed_target_uri).replace('www.', '')

                netlink['timestamp'] = datetime.now().strftime(
                    "%Y-%m-%d %H:%M:%S")

                yield netlink

       #Here I am aware that I am following all links but this problem does not repeat for #idx2 
       for a in response.css('a'):
           yield response.follow(a, callback=self.parse)
```

**Comment by elacuesta** [comment] 2019-10-09 17:09
Fragments are not taken into account by the [default dupefilter](https://docs.scrapy.org/en/1.7/topics/settings.html#dupefilter-class), which filters out subsequent requests to the same URL.

```python
>>> from scrapy.utils.request import request_fingerprint
>>> from scrapy import Request
>>> request_fingerprint(Request("https://example.org#fragment-one")) == request_fingerprint(Request("https://example.org#fragment-two"))
True
```

The [default `start_requests` method](https://github.com/scrapy/scrapy/blob/1.7.3/scrapy/spiders/__init__.py#L59-L73) adds `dont_filter=True`, that's why the first request, generated from the `start_urls` list doesn't count and the first yielded request goes through.



Here's an example showing the behaviour I'm describing:
```python
import scrapy

class DupefilterSpider(scrapy.Spider):
    name = 'dupefilter'
    start_urls = ['https://example.org#fragment-one']
    custom_settings = {
        'LOG_LEVEL': 'DEBUG',
        'DUPEFILTER_DEBUG': True,
    }

    def parse(self, response):
        self.logger.info('Request URL: %s, Response URL: %s', response.request.url, response.url)
        yield scrapy.Request('https://example.org#fragment-two')
        yield scrapy.Request('https://example.org#fragment-three')
```

Result:
```
(...)
2019-10-09 14:08:38 [scrapy.core.engine] INFO: Spider opened
2019-10-09 14:08:38 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-10-09 14:08:38 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-10-09 14:08:39 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org#fragment-one> (referer: None)
2019-10-09 14:08:39 [dupefilter] INFO: Request URL: https://example.org#fragment-one, Response URL: https://example.org
2019-10-09 14:08:39 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://example.org#fragment-three> (referer: https://example.org)
2019-10-09 14:08:39 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org#fragment-two> (referer: https://example.org)
2019-10-09 14:08:39 [dupefilter] INFO: Request URL: https://example.org#fragment-two, Response URL: https://example.org
2019-10-09 14:08:39 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://example.org#fragment-two> (referer: https://example.org)
2019-10-09 14:08:39 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://example.org#fragment-three> (referer: https://example.org)
2019-10-09 14:08:39 [scrapy.core.engine] INFO: Closing spider (finished)
(...)
```

I'm closing this issue as I think this is not a bug, please feel free to reopen if you think it's necessary.

**Closed by elacuesta** 2019-10-09 17:09 UTC

**Comment by vella-nicholas** [comment] 2019-10-10 12:41
Thank you, your answer helped me find a solution. I am setting `dont_filter=False` even for the  default start_requests method by adding this to the middleware:

```
def process_start_requests(self, start_requests, spider):
        for r in start_requests:
            new_request = Request(r.url, dont_filter=False)
            yield new_request
```

Can you confirm this is the correct way to do it?

On a side note, this was not reported as a bug, hence the tag on the title `Question`. Some repositories use the tag `question` or `triage` for this kind of issue.

**Comment by elacuesta** [comment] 2019-10-10 20:56
> Can you confirm this is the correct way to do it?

Looks good. It could be a little bit simpler by using [`Request.replace`](https://docs.scrapy.org/en/1.7/topics/request-response.html#scrapy.http.Request.replace):
```python
def process_start_requests(self, start_requests, spider):
    for r in start_requests:
        yield = r.replace(dont_filter=False)
```

Or even better, by defining a custom [`start_requests`](https://docs.scrapy.org/en/1.7/topics/spiders.html#scrapy.spiders.Spider.start_requests) method in the spider itself, that way you don't have to maintain a separate middleware component.

**Comment by vella-nicholas** [comment] 2019-10-11 07:31
Thank you very much!
