### ISSUE TITLE
Modify scrapy scheduler to allow for using queue class other than PriorityQueue

### ISSUE THREAD

**Issue by KrisB88** [scrapy/scrapy#1802] opened 2016-02-21 21:15 UTC
I'm currently working on a project for a client that is a rather broad crawl, something around 200-300 urls. I've been tweaking this project to maximize the scrapy performance because my item pipelines really don't add much overhead if any to the performance.  However, I ran into a problem with scrapy's built-in queue strategy.  
    The problem has been that the url queue becomes loaded with really long sequences of urls from a single domain.  Because I'm trying to maintain some kind of politeness to these sites with a reasonable download rate, the performance suffers greatly because every url has some kind of download delay which essentially stalls the scraper.  To fix this I implemented a simple queue that uses a heap which holds a PriorityQueue from queuelib to further filter urls by their domain.  Domains are managed separately in this class with heapq which allows for choosing the next url based on the domain which has been called least recently.  By doing so, I was able to increase the crawler's performance by over 500 percent using the exact same settings and only running a single instance of the spider.  This is just a first implementation that can be improved with some custom extensions, but as a first run has shown fantastic improvements in both download rates and cpu utilization.  
    There was one issue I ran into when making this change to scrapy which is that the scheduler initializes its memory queue to a PriorityQueue.  Therefore, I had to create a custom scheduler which only deviated from the built-in scheduler in its from_crawler.  **init**, and open methods.  Seems like a decent candidate for changes to the scheduler class and something I would be happy to do.  Anyways, just my thoughts and I'd love to hear what everyone else thinks.  I can share my code as well for anyone that wants to see the queue I'm using for this broad crawl.

**Comment by nyov** [comment] 2016-02-27 15:41
First, since the Scheduler is a configurable setting, that's what it's for.
That said, if all you needed to change was to use a custom priority queue, then it's probably a good candidate for making into a setting. I've wondered myself in the past why it's hard-coded there, but hadn't any need to change it.

Is #1822 doing what you had in mind there?

And if you came up with a good alternative for the PQ that may make sense as a default, that'd be nice to have a look at!

**Comment by KrisB88** [comment] 2016-02-27 18:41
Your modifications to the scheduler are exactly what I had done as well. I'll see if I can come up with a general and flexible enough default queue that could work.  I saw such an increase in performance for a generic broad crawl without any added complexity from making it distributed that I definitely think it could be worth it.  If you want to check out the queue I'm currently using and maybe offer some advice that would be great! You can find it at [https://github.com/chamilto/tnscraper/blob/master/tnscraper/queues/queue.py](url)

**Comment by kmike** [comment] 2016-02-27 19:09
I've also seen a problem with many requests to a single domain. The simplest solution is to decrease request priority for domain each N requests to this domain; this can be done either in a spider or in a middleware. It is not optimal because queuelib keeps a queue per each possible request priority, and so this is inefficient if there are many different request priorities; but if N is large enough it works ok. 

In other case I went as far as created a custom scheduler and custom request queues: one queue class for requests from a single domain, and another queue class for balancing between queues for a single domains. 

@KrisB88 The latter is very similar to your DomainPriorityQueue; instead of using a heap it uses a random sample (I like heap approach though), and for the extra flexibility domain is passed in request.meta, not extracted from URL: you can assing a custom 'scheduler slot' to request this way, not necesarily based on the domain. 

I think self.domains is not needed in your DomainPriorityQueue implementation - why can't you check self.pqueues directly?

In frontera this is solved in a different way: if I'm not mistaken, scheduler checks if downloader is busy processing requests for a single domain and asks queue not to send requests for this domain if there are many requests already.

**Comment by tianhuil** [comment] 2018-02-25 05:42
I would like to propose adding a `DomainScheduler` [implemented here](https://github.com/tianhuil/domain_scheduler) into scrapy.  It scrapes in a domain-smart way: by round-robin cycling through the domains. This has two benefits:

1. Spreading out load on the target server instead of hitting the server with many requests at once
2. Reducing delays caused by server-overloaded errors or CONCURRENT_REQUESTS_PER_IP type restrictions.

It implements the solution proposed in https://github.com/scrapy/scrapy/issues/1802#issue-135260562.  It is dependent on https://github.com/scrapy/queuelib/pull/21.  Thoughts?

**Comment by nyov** [comment] 2018-02-26 07:30
I don't see an issue with adding another queue implementation to queuelib. Seems to be a good place. 

I think this ticket is solved, #1822 has been merged. Let's open a new issue for the `DomainScheduler`?

**Comment by tianhuil** [comment] 2018-02-26 13:02
Will do!

**Comment by Gallaecio** [comment] 2019-07-09 13:03
Closing a per https://github.com/scrapy/scrapy/issues/1802#issuecomment-368413067

**Closed by Gallaecio** 2019-07-09 13:03 UTC
