### ISSUE TITLE
Change `FEED_URI` in spider to a value that depends on the argument passed

### ISSUE THREAD

**Issue by serhii73** [scrapy/scrapy#3900] opened 2019-07-24 09:04 UTC
Hello everyone.
I have a question.
I have a simple scrapy project.
I run my project like:
```bash
scrapy crawl mp -a city="Toronto, ON"
```
In 
```
def __init__(self, *args, **kwargs):
```
I get argument value like:
```
self.city = kwargs["city"]
```
In `seetings.py` I can add a line like:
```
FEED_FORMAT = "csv"
FEED_URI = "output/some_city.csv"
```
And information about need city will be saved in `output/some_city.csv` file.
##### Problem
But if I will be pass different cities like arguments to my spider, like:
```bash
scrapy crawl mp -a city="New York, NY"
```
then
```bash
scrapy crawl mp -a city="Toronto, ON"
```
then
```bash
scrapy crawl mp -a city="Chicago, IL"
```
etc
All information will be saved in  `output/some_city.csv` file.
##### What I want
I want to find a decision, when I pass `"Chicago, IL"`  - data will be saved in `Chicago_IL.csv` if I pass `"Toronto, ON"` in `Toronto_ON.csv`
I just need to change `FEED_URI` in my spider.
But how?
```
self.settings.attributes['FEED_URI']
```
I can get my `FEED_URI` in spider use this command, but how change this data?
I read this [link](https://stackoverflow.com/questions/42134570/update-scrapy-settings-based-on-spider-property/42135262) but I wrote a solution and it does not work.
I can use `-s` but it not conveniently.
Do you know how I can resolve it?
Thank you very much.

**Comment by Gallaecio** [comment] 2019-08-01 09:13
Duplicate of #2392

**Closed by Gallaecio** 2019-08-01 09:13 UTC

**Comment by Gallaecio** [comment] 2021-07-29 02:52
https://docs.scrapy.org/en/latest/topics/feed-exports.html#storage-uri-parameters
