### ISSUE TITLE
SplashFormRequest.from_response executes same request for multiple form parameters.

### ISSUE THREAD

**Issue by nehakansal** [scrapy/scrapy#2949] opened 2017-10-03 07:01 UTC
Hi,

I am using SplashFormRequest.from_response() method to submit a form multiple times with different parameters. The formdata is passed on correctly it seems, but eventually when the request is executed, only the first set of parameters are used for the subsequent requests too. I ran a test on google to submit 3 different parameters on the search form and get the same issue. I am pasting the relevant piece of code and part of the output log from the crawl. Any idea why this might be happening? Thanks.

This is part of the parse method.
```
            for formd in formparams:
              print('===== Submitting FORM ===== ' + json.dumps(formd))
              yield SplashFormRequest.from_response(
                response,  
                formdata=formd,
                method=GET,
                callback=self.parse,
                meta=meta, **kwargs)
```

Output log
```
2017-10-02 23:38:02 [scrapy.core.engine] INFO: Spider opened
2017-10-02 23:38:02 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
REQUEST === <GET http://google.com>
REQUEST === <GET http://www.google.com via http://127.0.0.1:8050/execute>
2017-10-02 23:38:09 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.google.com via http://127.0.0.1:8050/execute> (referer: None)
2017-10-02 23:38:10 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.google.com/?gws_rd=ssl>
<CDRItem: _id: '78EA5573E093F9030B1F945E84B59B51D405C360BB4C421ED93A66976195BC2C', url: 'https://www.google.com/?gws_rd=ssl', timestamp_crawl: '2017-10-03T06:38:10.971013Z'>
===== Submitting FORM ===== {"q": "happy"}
REQUEST === <GET http://google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy>
===== Submitting FORM ===== {"q": "sad"}
2017-10-02 23:38:10 [py.warnings] WARNING: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy_splash/middleware.py:184: UserWarning: Unexpected request.meta['splash']['_replaced_args']
  warnings.warn("Unexpected request.meta['splash']['_replaced_args']")
  
REQUEST === <GET http://google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=sad>
REQUEST === <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
REQUEST === <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
2017-10-02 23:38:10 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
===== Submitting FORM ===== {"q": "neutral"}
REQUEST === <GET http://google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=neutral>
REQUEST === <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
2017-10-02 23:38:11 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
REQUEST === <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
2017-10-02 23:38:22 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute> (referer: None)
2017-10-02 23:38:22 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy>
<CDRItem: _id: 'B31AF63FD579B31F9A18BE78F30F845C21DD5F7DE36838FE87CED836E5783BEB', url: 'https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy', timestamp_crawl: '2017-10-03T06:38:22.662764Z'>
2017-10-02 23:38:22 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Comment by kmike** [comment] 2017-10-03 07:33
I suspect meta=meta is the problem - in this example all requests use the same meta object (it is not copied). Could you try it with `meta=meta.copy()`? I'm closing this issue; please reopen it in https://github.com/scrapy-plugins/scrapy-splash/issues repo if it was not caused by sharing meta dict.

**Closed by kmike** 2017-10-03 07:33 UTC

**Comment by nehakansal** [comment] 2017-10-03 16:59
That was the issue, thank you so much! 
Could you please explain a little how using the same meta dict caused the issue? Are the form parameters eventually copied to the meta dict in the scrapy code?

**Comment by kmike** [comment] 2017-10-03 17:46
Yes, they are copied, but not in Scrapy - this is what scrapy-splash does. All these scrapy.Request subclasses available in scrapy-splash are helpers to populate `request.meta['splash']`; there is a middleware which converts this meta to real requests later.

**Comment by nehakansal** [comment] 2017-10-03 18:25
Okay, thanks for the explanation! One more followup question if you don't mind - in the output log that I pasted, you will see these two lines

```
REQUEST === <GET http://google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=sad>
REQUEST === <GET https://www.google.com/search?source=hp&oq=&gs_l=&btnG=Search&q=happy via http://127.0.0.1:8050/execute>
```
I added this log to the Undercrawler dupe_filter for debugging. Is the first line printed when Scrapy calls the filter and the second when scrapy-splash calls the filter?

**Comment by kmike** [comment] 2017-10-04 10:09
Hi @nehakansal,

Could you please provide more details on where these lines come from exactly?
Scrpy-splash is not calling the dupefilter itself, but it replaces request with a new request st some point, and dupefilter Scrapy uses must be aware of scrapy-splash specifics.

**Comment by inferlinkdev** [comment] 2017-10-05 17:23
The lines are coming from the DupeFilter class of Undercrawler (dupe_filter.py). I added a print statement right before the return in that class. 
Did you mean to say that dupefilter should ideally be called once for each request?
