### ISSUE TITLE
Content-length not set when body is not specified 

### ISSUE THREAD

**Issue by juanriaza** [scrapy/scrapy#823] opened 2014-07-29 12:08 UTC
POST requests with empty body lacks of Content-length header. Default behaviour should be to set that header with a value of zero.

Also worth noting that documentation [states](http://doc.scrapy.org/en/latest/topics/request-response.html#request-objects) that:

> If body is not given,, an empty string is stored

But implementation [differs](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/webclient.py#L96).

**Comment by drack3800** [comment] 2015-03-18 21:46
Hi. Is this bug actual now? I would like to fix it.
I ask because I could not find usages of ```ScrapyHTTPClientFactory``` in current version of scrapy, but @juanriaza mentioned that problem in this class.

**Comment by kmike** [comment] 2015-03-18 21:50
@drack3800 I don't know if this bug exists in current Scrapy master or not. Checking if the issue is still valid (maybe also writing a test for it) is a great way to help! Of course, fixing it if it is present is even better.

**Comment by drack3800** [comment] 2015-03-18 22:06
@kmike test that was provided above (with selfmade server and simple crawler) still does not pass.
```python
(scrapyenv)persiyanov@drack3800:~/PyProjects$ python server.py 
started at ('0.0.0.0', 8001)
Host: 0.0.0.0:8001
Accept-Language: en
Accept-Encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Scrapy/0.24.5 (+http://scrapy.org)

127.0.0.1 - - [19/Mar/2015 03:55:00] "POST / HTTP/1.1" 200 -
```
I will try to find out the problem.

**Comment by drack3800** [comment] 2015-03-20 22:19
I [wrote a test in forked repo](https://github.com/drack3800/scrapy/commit/1b6d5a011a5485f3f2c01b32fa425b512d90d7ef) for webclient which tests the problem, and it passes. But when I start a server
```python
import BaseHTTPServer

class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_POST(self):
        print(self.headers)
        self.send_response(200)
        self.end_headers()

def run():
    server_address = ('', 8001)
    httpd = BaseHTTPServer.HTTPServer(server_address, Handler)
    httpd.serve_forever()

if __name__ == '__main__':
    run()
```
and spider
```python
import scrapy                                                                                       


class MySpider(scrapy.Spider):                                                                      

    name = 'spider'                                                                                 

    def start_requests(self):                                                                       
        yield scrapy.Request('http://0.0.0.0:8001', method='POST')                          

    def parse(self, response):                                                                      
        return
```
the server doesn't show me the ```Content-Length``` header.

**Comment by kmike** [comment] 2015-08-27 22:12
Fixed by https://github.com/scrapy/scrapy/pull/1089 - thanks @drack3800!

**Comment by rolando** [comment] 2016-01-14 16:08
The fix only works when using the `HTTP10` downloader handler.

**Comment by redapple** [comment] 2016-02-22 15:03
Re-opening.
https://github.com/scrapy/scrapy/issues/1800 adds a tests for this on HTTP/1.1

**Comment by redapple** [comment] 2016-02-24 16:58
Fixed in https://github.com/scrapy/scrapy/pull/1800

**Closed by redapple** 2016-02-24 16:58 UTC
Labels: easy
