### ISSUE TITLE
Change field name for output

### ISSUE THREAD

**Issue by Sammeeey** [scrapy/scrapy#5509] opened 2022-05-27 00:17 UTC
## Summary

It would be great to have a simple way to change the field names for the output.

## Motivation

When we define an item class we usually use [Python variables for the names of the fields](https://docs.scrapy.org/en/latest/topics/items.html#declaring-item-subclasses).
However in the output files we'd rather have correctly spelled headers.
But if we use the current approach, we only have the variables names as headers by default:
![header of result speadsheet from scrapy](https://user-images.githubusercontent.com/49591562/170603916-98f3fda5-d444-4301-a749-d1022a619eaa.png)

## Describe alternatives you've considered

I wondered if [using an __init__ function for the item class](https://stackoverflow.com/a/69675451) would be the recommended way.
Or are there other options?

**Comment by Gallaecio** [comment] 2022-05-27 05:12
This is a duplicate of #3266, which is strongly related to #1008, and for which there is a (admittedly forgotten) https://github.com/scrapy/scrapy/pull/3696.

**Closed by Gallaecio** 2022-05-27 05:12 UTC

**Comment by Sammeeey** [comment] 2022-05-27 15:27
Thanks for the quick feedback✌

I hope that I could guide the discussion to the right direction.
