### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.7 

### ISSUE THREAD

**Issue by c8forfor** [scrapy/scrapy#1452] opened 2015-08-24 15:16 UTC
Hello, 
I run a ubuntu 14 LTS machine. 

I get a conflict error with every scrapy command.
For instance:
When I try :

scrapy startproject store_name

I get the following error: 
<addr>
Traceback (most recent call last):
  File "/usr/bin/scrapy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3084, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3070, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 653, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 666, in _build_from_requirements
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 844, in resolve
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1>=0.1.8'), set(['pyasn1-modules']))
</addr>
Can someone help me ?

**Comment by cvieiram** [comment] 2015-09-05 12:38
Did you figure it out?

**Comment by cYbercOsmOnauT** [comment] 2015-09-28 12:53
Take the Debian package. It works. I tried it out some minutes ago because I had the same problem.

http://pkgs.org/debian-sid/debian-main-i386/python-pyasn1_0.1.8-2_all.deb.html

**Comment by Yankee26** [comment] 2015-11-01 10:24
http://pkgs.org/debian-sid/debian-main-i386/python-pyasn1_0.1.8-2_all.deb.html
Must have been changed because it produces a website error.
Bob 11/1/2015

**Comment by Yankee26** [comment] 2015-11-01 10:41
Just found an answer that works!
http://stackoverflow.com/questions/32304886/error-while-starting-new-scrapy-project
sudo pip install pyasn1 --upgrade     
scrapy now works without errors.
Thanks Roberto

answered Sep 15 at 10:43
Roberto Zerbini
211

**Comment by Gallaecio** [comment] 2019-07-08 13:22
Closing because the issue was simply that an old version of a dependency was installed, there’s nothing to change on Scrapy’s side.

Anyone affected in the future should be able to find this issue or https://stackoverflow.com/a/32584004/939364 and learn what the issue is about and how to fix it.

**Closed by Gallaecio** 2019-07-08 13:22 UTC
