### ISSUE TITLE
Retry until finding working options for https sites

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#1435] opened 2015-08-14 22:19 UTC
We have seen multiple cases for crawlers failing to connect to https urls due to differences in SSL_options+openssl+pyopenssl, i.e. #82 #194 #1429 #1434 #1227 #981 #26 #1101, our users usually found workarounds hacking ContextFactory but solutions remain hidden and lost in private project's code.

I think we have a chance to fix this problem for everyone by automating the process of retrying until finding a working set of options.

I think we can design a solution around making ContextFactory aware of `request`, configuring it trough values in `request.meta` (similar to #186), but also adding a downloadermiddleware that retries requests using different SSL options, of course it learns and set working options per hostname on following requests.

**Comment by nyov** [comment] 2015-08-15 00:12
I have to say I think this is more a failure of twisted's libraries. At least from the issues I am aware of.
It's really hard to do SSL/TLS right on top of complex or broken libs.

Probably the idea here is a sensible solution, but I also think adding more magic  to hide broken implementation is bad design.
Moving away from the twisted's http client might be more preferrable to me, if it can be solved in a lightweight, asynchronous, way?

Certainly though, passing ssl connection options in a `request` is a very good idea, instead of (only) automagic detection.
Most crawlers will only go for "anonymous" data and not care about actual connection security and forward secrecy, but some may feel different (e.g. my bank account spider? ;) Automatically retrying and accepting a downgraded or insecure connection there could be disastrous.

**Comment by gmeans** [comment] 2015-08-15 12:45
I'm not sure this is so much a failure of Twisted's libraries as much as confusion after those SSL bugs released. I was surprised when I learned that SSLv23_METHOD actually implied protocol negotiation, and was just poorly named.

In addition OpenSSL's docs show a new method will be releasing, TLS_METHOD:

https://www.openssl.org/docs/ssl/TLSv1_server_method.html

My takeaway was that the underlying libs do the protocol negotiation, Scrapy shouldn't have to. The latest versions of Twisted create a default context that disables SSLv2 and SSLv3, so I wonder if the ScrapyContextFactory should be switched back to SSLv23_METHOD.

Outside of the OpenSSL version on my mac not supporting TLS1.1 and 1.2, all I had to update code wise for my issue (#1429) was change the method.

I think less magic is the better approach. Perhaps you could start including multiple ContextFactories similar to how downloaders are handled, and just have common configurations that handle odd SSL scenarios?

**Comment by juanriaza** [comment] 2015-12-03 10:58
I can reproduce this issue with `scrapy shell https://www.heb.com/browse/shop`

Looks like it always redirects to this url http://www.heb.com/error/sslerr.html indicating that the browser is not safe.

**Comment by redapple** [comment] 2016-02-09 16:55
@juanriaza , the trick from https://github.com/scrapy/scrapy/issues/1429#issuecomment-131782133 (and https://github.com/scrapy/scrapy/pull/1629) worked for me with `https://www.heb.com/browse/shop`

can you confirm on your end?

**Comment by redapple** [comment] 2016-02-10 10:48
as for the original discussion, @dangra , @nyov , @gmeans ,
I would rather that we leave the SSL/TLS layer agree with the target, negotiating with sane defaults (as SSLv23_method does), by default out of the box,
and offer pluggable context factories for special cases or needs.
I don't like the idea of retrying with different settings under-the-hood, on behalf of the user.
and I don't think configuring settings via requests meta would be easier than different available built-in context factories. (though I may be missing cases where one needs input from the user)

**Comment by nyov** [comment] 2016-02-10 14:18
Revisiting this, I think it might be good to have a user-friendly default, that simply works, for most users.
So long as behavior is somehow configurable (different context factories, etc.) and there would be some notification somehow if the project-chosen defaults are potentially insecure (such as an automated retrying might be), I'm fine with that.

But I'll excuse myself from this discussion, as I don't seem to have a good idea or strong opinion which way this might best be implemented. Both @dangra and @redapple make sense to me.

(Aside: It'd be cool to have the option to log the actual TLS connection options/Cipher Suite on first connection to a particular site, as a verification method. Doesn't have to be active by default.)

**Comment by juanriaza** [comment] 2016-02-20 10:22
@redapple works for me as well

**Comment by redapple** [comment] 2016-07-11 07:29
I'm closing this as #1794  is now merged.
I opened https://github.com/scrapy/scrapy/issues/2111 about @nyov idea of logging actual cypher suites.

**Closed by redapple** 2016-07-11 07:29 UTC
Labels: enhancement, https
