### ISSUE TITLE
Issue with using bindaddress

### ISSUE THREAD

**Issue by mikkogozalo** [scrapy/scrapy#1967] opened 2016-05-05 03:05 UTC
It seems that bindaddress isn't working. Snippet of the code where I test it is here:
https://gist.github.com/mikkogozalo/e44975444307a37078d43f8bc88e2489

Debug output is here:
https://gist.github.com/mikkogozalo/739d17964e2c133c80191bae22ef502e

**Comment by D-Kalck** [comment] 2017-10-23 09:14
I have the same problem, my server have several IPs and I want to use them as my outgoing IP with Scrapy but it doesn't work.

**Comment by elacuesta** [comment] 2019-01-04 14:43
It seems to me like this issue is not present anymore, at least I cannot reproduce it with the latest Scrapy code:
```
2019-01-04 11:38:34 [scrapy.core.engine] INFO: Spider opened
2019-01-04 11:38:34 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-01-04 11:38:34 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
['192.168.43.152', '192.168.1.4']
2019-01-04 11:38:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://httpbin.org/ip> (referer: None)
b'{\n  "origin": "186.49.x.x"\n}\n'
2019-01-04 11:38:35 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://httpbin.org/ip> (referer: None)
b'{\n  "origin": "179.28.x.x"\n}\n'
2019-01-04 11:38:35 [scrapy.core.engine] INFO: Closing spider (finished)
```

```
$ scrapy version -v
Scrapy       : 1.5.0
lxml         : 4.2.6.0
libxml2      : 2.9.9
cssselect    : 1.0.3
parsel       : 1.5.1
w3lib        : 1.19.0
Twisted      : 18.9.0
Python       : 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) - [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
pyOpenSSL    : 18.0.0 (OpenSSL 1.1.0j  20 Nov 2018)
cryptography : 2.4.2
Platform     : Darwin-18.2.0-x86_64-i386-64bit
```

However, I did find some oddities in the way IP addresses are handled from within the Scrapy shell, please take a look at #3565, and consider closing this if appropriate. Thanks!

**Comment by Gallaecio** [comment] 2019-08-14 11:36
Closing due to a lack of feedback from the original author.

**Closed by Gallaecio** 2019-08-14 11:36 UTC
