### ISSUE TITLE
Possible issue with uri_params

### ISSUE THREAD

**Issue by devster31** [scrapy/scrapy#5261] opened 2021-10-06 00:17 UTC
### Description
I tried following the docs here https://docs.scrapy.org/en/latest/topics/feed-exports.html#scrapy.extensions.feedexport.uri_params to have a dynamic Feed name.
Here is the relevant code:

`uri_params` function:
```py
from urllib.parse import urlsplit
from pathlib import PurePath


def source_params(params, spider):
    return {**params, "source_to_file": PurePath(urlsplit(spider.source).path).name}
```
Spider
```py
import scrapy
from pathlib import Path

"""Gets all videos from a playlist, should also work for actors"""


class PlaylistsSpider(scrapy.Spider):
    name = "playlists"
    custom_settings = {
        "FEEDS": {
            Path("%(source_to_file)s").with_suffix(".csv").name: {"format": "csv"}
        },
        "FEED_URI_PARAMS": "myproject.utils.source_params",
    }

    def __init__(self, *args, **kwargs):
        self.source = kwargs.pop("source")
        self.start_urls = [self.source]

    def parse(self, response):
        pass
```
### Steps to Reproduce
During debugging and breaking at this line https://github.com/scrapy/scrapy/blob/cbf934955223c29f0632fbba94d9586849a3b744/scrapy/extensions/feedexport.py#L542 
this happens:
```py
-> params['source_to_files']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'source_to_files'
```
and indeed there's no file output if I let it run

**Expected behavior:**
Export according to file name as specified by `FEEDS` and `URI_PARAMS`
**Actual behavior:**
No feed export
**Reproduces how often:**
Until I replaced this line: https://github.com/scrapy/scrapy/blob/cbf934955223c29f0632fbba94d9586849a3b744/scrapy/extensions/feedexport.py#L541
with the following:
```
        params = uripar_function(params, spider)
```
### Versions
```
Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.9.6 (default, Jun 29 2021, 05:25:02) - [Clang 12.0.5 (clang-1205.0.22.9)]
pyOpenSSL    : 21.0.0 (OpenSSL 1.1.1l  24 Aug 2021)
cryptography : 35.0.0
Platform     : macOS-11.4-x86_64-i386-64bit
```

**Comment by Gallaecio** [comment] 2021-10-06 08:32
Duplicate of #4962

**Closed by Gallaecio** 2021-10-06 08:32 UTC
