### ISSUE TITLE
Allow failing on potential data loss to trigger a retry

### ISSUE THREAD

**Issue by royahsan** [scrapy/scrapy#4120] opened 2019-11-03 00:55 UTC
### Description

By default settings of  [DOWNLOAD_FAIL_ON_DATALOSS](https://docs.scrapy.org/en/latest/topics/settings.html#download-fail-on-dataloss) implemented in [#2590](https://github.com/scrapy/scrapy/pull/2590), whenever `ResponseFailed([_DataLoss])` error occurs, it should be raised. 

 But currently, instead of raising error we pass it through to the callback function after adding `['partial']` flag to the response object. [This](https://github.com/scrapy/scrapy/blob/52a52e2388e465f81e56fb92a3d731531ea6f007/scrapy/core/downloader/handlers/http11.py#L410) is where we add the flag after checking the PotentialDataLoss.

```
elif reason.check(PotentialDataLoss):
    self._finished.callback((self._txresponse, body, ['partial']))
```` 
Now this prevents the retry middleware to step in and retry (depending on settings) the failed request.

**My understanding that `['partial']` keyword is a must indication of `ResponseFailed([_DataLoss])` is based on the code above and this [comment](https://github.com/scrapy/scrapy/issues/2086#issuecomment-230278099)  which suggests**

> PotentialDataLoss may be raised by a transfer encoding decoder's
nomoredata method to indicate that it cannot be determined if the
entire response body has been delivered.  This only occurs when making
requests to HTTP servers which do not set Content-Length or a
Transfer-Encoding in the response because in this case the end of the
response is indicated by the connection being closed, an event which may
also be due to a transient network problem or other error.

### Steps to Reproduce
Try to `Fetch` the following URL for around 150 times and somewhere in between the host server starts sending the partial/bad content-length header resulting DataLoss error and addition of ['partial']` keyword

URL: [https://ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=21816333](https://ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=21816333)

The above URL sometimes return a 404 before providing a response with the wrong `Content-Length` which consequently results in DataLoss / PotentialDataLoss. 

**Expected behavior:** 
ResponseFailed([_DataLoss]) exception should be raised.

**Actual behavior:**
Partial response passes through the engine to the callback function after adding `'partial'` flag. 
Following is one such example log generated by the example [url](//ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=21816333) above.

```
DEBUG: scrapy.core.engine: _on_success:  Crawled (200) <GET https://ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=21816333> ['partial']
```

**Reproduces how often:** 
Every time when the server's response results in possible  `DataLoss` error.

### Versions

Scrapy       : 1.7.3
lxml         : 4.4.1.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.7.0
Python       : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1c  28 May 2019)
cryptography : 2.7
Platform     : Windows-10-10.0.18362-SP0

### -- 

I could not find any URL to regenerate the `ResponseFailed([_DataLoss])` error at very first Request, if someone knows any such URL, please let me know so I can update the steps to Reproduce here. 

@rmax, @nyov

**Comment by Gallaecio** [comment] 2019-11-06 11:25
I believe you are mixing up ‘potential data loss’ (`partial` flag, caused e.g. by a missing `Content-Length` header) and actual ‘data loss’ (`dataloss` flag, caused e.g. by a `Content-Length` header value that does not match the received response).

In the `partial` cases, the current behavior is to assume the responses are correct but mention that they may not be through the `partial` flag.

Would you like to turn this issue into a request to add a settings to treat potential data losses as actual data losses?

**Comment by nyov** [comment] 2019-11-06 12:37
Hey @royahsan. This looks a bit tricky.

> My understanding that `['partial']` keyword is a must indication of `ResponseFailed([_DataLoss])` is based on the code above

From the [commit data](https://github.com/scrapy/scrapy/pull/2590/files), this is not what's happening. `['partial']` is added on `PotentialDataLoss`, not `_DataLoss`, as you said yourself:

>  [This](https://github.com/scrapy/scrapy/blob/52a52e2388e465f81e56fb92a3d731531ea6f007/scrapy/core/downloader/handlers/http11.py#L410) is where we add the flag after checking the PotentialDataLoss.

I can see why you would get confused there (I was too, just now), when the docs state:

>DOWNLOAD_FAIL_ON_DATALOSS
>
> Whether or not to fail on broken responses, that is, declared
``Content-Length`` does not match content sent by the server or chunked
response was not properly finish.

This could be explained a bit more explicitly.

The difference is this: A missing `Content-Length` header doesn't really matter, it's just like a missing checksum on transfered data length (but it will warn with the `partial` flag). It may or may not be complete, no way to verify without the "checksum"!
But when given, Scrapy checks the `Content-Length` header against the actual calculated body length, and if those are _different_, _then_ it raises the `ResponseFailed([_DataLoss])`, unless `fail_on_dataloss=False`.

If you want to treat potential dataloss (partial) as hard fails, I don't know if that's actually possible right now. So if that's what you want, let us know.

**Comment by royahsan** [comment] 2019-11-07 15:13
@Gallaecio , @nyov You are right I was mixing the mixing up` ‘potential data loss’` (partial flag, caused e.g. by a missing Content-Length header) and `actual ‘data loss’` (dataloss flag, caused e.g. by a Content-Length header value that does not match the received response).

I do not know whether or why these falgs should be treated as same, so it make better sense to close the issue. 
Thank you for the support.

**Comment by royahsan** [comment] 2019-11-07 19:37
@Gallaecio  what you think of the idea, of providing the option to raise or suppress `potential data loss` error, just like `actual data loss` error. 
For `actual data loss` error scrapy provides this option through [DOWNLOAD_FAIL_ON_DATALOSS](https://docs.scrapy.org/en/latest/topics/settings.html#download-fail-on-dataloss) settings

Is it reasonable to open a separate enhancement Issue with this idea?

**Comment by Gallaecio** [comment] 2019-11-08 08:22
I think it’s reasonable.

**Comment by Gallaecio** [comment] 2019-11-08 08:24
That said, I’ve never seen a potential data loss that is fixed upon retry. That is, if a request does not return a `Content-Length` header, retrying won’t make it suddenly provide the header. Have you found a website that does miss the `Content-Length` header only sometimes for a given request?

**Comment by royahsan** [comment] 2019-11-08 14:50
[this](https://ecorp.azcc.gov/BusinessSearch/BusinessInfo?entityNumber=21816333) website shows a potential data loss while it serves captcha verification page when a specific number of requests pass through the same IP. Retry using automatic proxy rotation (like [Crawlera](https://scrapinghub.com/crawlera)) in this case does solve the problem, but this obviously is very rare.

**Comment by Gallaecio** [comment] 2019-11-08 14:54
For that case, I believe solving #3590 would be better, since the problem is not the `Content-Type` header, but the fact that the response is a CAPTCHA response. If they started including a `Content-Type` header in those responses, you would still want to retry the corresponding request.

**Comment by royahsan** [comment] 2019-11-08 15:05
With that being said we can agree that in most cases retry does not solve `partial error` also If a user wants to alter/accept response or regenerate request from such responses, it can be done by detecting 'partial' flag in a middleware's `process_response` function.
So this feature dont have a use-case.

**Comment by Gallaecio** [comment] 2019-11-08 15:08
@royahsan Should we close this then?

**Closed** 2019-11-08 15:08 UTC
Labels: enhancement

**Comment by royahsan** [comment] 2019-11-08 15:11
Sure! any potential use cases for this, if any, can be dealt by [#3590](https://github.com/scrapy/scrapy/issues/3590)
