### ISSUE TITLE
S3FilesStore throws TypeError: __init__() missing 1 required positional argument: 'uri'

### ISSUE THREAD

**Issue by gesof** [scrapy/scrapy#4641] opened 2020-06-22 15:12 UTC
For some reason I keep getting annoying errors while trying to make the frontera/scrapy combination work and most of the time is due to lack of *really* working examples. Here is the last one:

settings.py
```
# export to S3 settings
AWS_ACCESS_KEY_ID = '***'
AWS_SECRET_ACCESS_KEY = '****'

FEED_URI = 's3://somecrawler/%(name)s/%(today)s.html'
FEEDS = {
    's3': {
        'format': 'html',
        'encoding': 'utf8',
        'store_empty': False,
        'fields': ['content'],
        'indent': 4,
    }
}

FEED_FORMAT = 'jsonlines'

ITEM_PIPELINES = {
    'scrapy.pipelines.files.S3FilesStore': 1
}
```

Please (2x) just be a little more elaborate in the documentation. Sample: https://docs.scrapy.org/en/latest/topics/feed-exports.html#feeds

`A dictionary in which every key is a feed URI ..` followed by an example with 3 keys, none related to a S3 case. And there are only 3 storage backends to store in the documentation so I would expect to see one example for each. Just saying..

**Comment by elacuesta** [comment] 2020-06-22 15:56
We strive to keep a reasonable balance between keeping the docs simple and covering every feature. Which changes would you suggest? Could you share the errors you're getting so we can see which parts of the docs could be improved?

Regarding your code: `FEED_URI` was deprecated and removed from the docs with the introduction of `FEEDS`. As the sentence you posted says, each key should be an [URI](https://tools.ietf.org/html/rfc3986#section-3), but "s3" does not comply with that. Instead, you should do something like:

```python
FEEDS = {
    's3://somecrawler/%(name)s/%(today)s.html': {
        'format': 'html',
        'encoding': 'utf8',
        'store_empty': False,
        'fields': ['content'],
        'indent': 4,
    }
}
```

**Comment by gesof** [comment] 2020-06-23 11:16
I figured it out so I used the format you suggested but the error is the same. I managed to move forward with a patch that I found online that is to use a custom pipeline based on the original class: 

    # ./pipelines/FixedS3FilesStore.py

`from scrapy.pipelines.files import S3FilesStore


class FixedS3FilesStore(S3FilesStore):
    # @classmethod
    # def from_crawler(cls, settings):
    #     uri = settings.get('FEED_URI')
    #     return S3FilesStore(uri)
    @classmethod
    def from_settings(cls, settings):
        k = list(settings.get('FEEDS'))
        uri = k[0]
        return S3FilesStore(uri)
`

**Comment by elacuesta** [comment] 2020-06-23 14:23
Please share the error you were getting.

**Comment by gesof** [comment] 2020-06-23 15:29
```
2020-06-23 18:23:34 [scrapy.utils.log] INFO: Scrapy 2.1.0 started (bot: tutorial)
2020-06-23 18:23:34 [scrapy.utils.log] INFO: Versions: lxml 4.5.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.2 (default, Jun  2 2020, 16:03:25) - [Clang 10.0.1 (clang-1001.0.46.4)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020), cryptography 2.9.2, Platform macOS-10.14.6-x86_64-i386-64bit
2020-06-23 18:23:34 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2020-06-23 18:23:34 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'tutorial',
 'NEWSPIDER_MODULE': 'tutorial.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['tutorial.spiders']}
2020-06-23 18:23:34 [scrapy.extensions.telnet] INFO: Telnet Password: 64eadd31ac9a883f
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from before-call.apigateway to before-call.api-gateway
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2020-06-23 18:23:35 [botocore.loaders] DEBUG: Loading JSON file: /Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/data/endpoints.json
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Event choose-service-name: calling handler <function handle_service_name_alias at 0x109665670>
2020-06-23 18:23:35 [botocore.loaders] DEBUG: Loading JSON file: /Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/data/s3/2006-03-01/service-2.json
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x109633040>
2020-06-23 18:23:35 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x10962cdc0>
2020-06-23 18:23:35 [botocore.endpoint] DEBUG: Setting s3 timeout as (60, 60)
2020-06-23 18:23:35 [botocore.loaders] DEBUG: Loading JSON file: /Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/data/_retry.json
2020-06-23 18:23:35 [botocore.client] DEBUG: Registering retry handlers for service: s3
2020-06-23 18:23:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2020-06-23 18:23:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-06-23 18:23:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
Unhandled error in Deferred:
2020-06-23 18:23:35 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 192, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 196, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/utils/misc.py", line 150, in create_instance
    return objcls(*args, **kwargs)
builtins.TypeError: __init__() missing 1 required positional argument: 'uri'

2020-06-23 18:23:35 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/macuser/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/utils/misc.py", line 150, in create_instance
    return objcls(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'uri'
```

**Comment by elacuesta** [comment] 2020-06-23 16:08
I think the issue here is that you're mixing two features:
* [Exporting scraped items to S3](https://docs.scrapy.org/en/2.1/topics/feed-exports.html#s3) ([`FEEDS`](https://docs.scrapy.org/en/2.1/topics/feed-exports.html#std-setting-FEEDS) setting)
* [Downloading files to S3](https://docs.scrapy.org/en/2.1/topics/media-pipeline.html#amazon-s3-storage) (`FILES_STORE`, `IMAGES_STORE` settings)

Maybe you are not providing a value for the [`FILES_STORE`](https://docs.scrapy.org/en/2.1/topics/media-pipeline.html#std-setting-FILES_STORE) setting?

**Comment by gesof** [comment] 2020-06-24 12:47
You were right, there was a mix of two concepts, both being under Item Pipelines. I abandoned the export option whose error was above and used the second option

**Comment by wRAR** [comment] 2020-06-26 08:57
@gesof can you confirm this was a configuration problem and we can close this?

**Comment by gesof** [comment] 2020-06-26 14:01
No, I can only confirm that in one configuration it worked. The error above refers to exporting items to S3, so there still is some issue.

**Comment by elacuesta** [comment] 2020-06-26 14:33
This is in fact a configuration issue AFAICT. The exception can be reproduced with the following spider:

```python
import scrapy

class FilesSpider(scrapy.Spider):
    name = "files_spider"
    start_urls = ["https://example.org"]
    custom_settings = {
        "ITEM_PIPELINES": {
            "scrapy.pipelines.files.S3FilesStore": 1
        },
    }

    def parse(self, response):
        pass
```

The problem is that `scrapy.pipelines.files.S3FilesStore` does not define any of the supported factory methods (`from_crawler`, `from_settings`) and is instantiated without passing any arguments, hence the "missing 1 required positional argument" message. Moreover, `S3FilesStore` is not a pipeline class, it should not be added to `ITEM_PIPELINES`. The correct way to use the files pipeline feature is explained [in the docs](https://docs.scrapy.org/en/2.2/topics/media-pipeline.html#enabling-your-media-pipeline).

I'm closing the issue, please feel free to reopen it if you think it's necessary.

**Closed by elacuesta** 2020-06-26 14:33 UTC
Labels: docs

**Comment by gesof** [comment] 2020-06-27 11:46
In order to clarify: "scrapy.pipelines.files.S3FilesStore" exsists only for being used by FilesPipeline or ImagesPipeline, like a protected class. 
And  "scrapy.extensions.feedexport.S3FeedStorage" is used by the Json/CSV/XMl exporters that in turn can be used in my own ItemPipeline [according to the docs](https://docs.scrapy.org/en/2.1/topics/exporters.html?highlight=%22group%20scraped%20items%20to%20different%20files%22#using-item-exporters)
