### ISSUE TITLE
loader.get_output_value returning None for a key that can be confirmed via loader.load_item

### ISSUE THREAD

**Issue by lekhakpadmanabh** [scrapy/scrapy#964] opened 2014-12-02 22:19 UTC
import scrapy

    class MyItem(scrapy.Item):
	    item1 = scrapy.Field()
        item_url = scrapy.Field()
	    item_address = scrapy.Field()
	    item_list = scrapy.Field()

    class MyLoader(scrapy.contrib.loader.ItemLoader):
        default_output_processor = TakeFirst()
        default_input_processor = MapCompose(unicode.strip)
        item_list_in = Identity()
        item_list_out = Identity()

    class MySpider(scrapy.Spider):

        name = 'myspider'
        start_urls = ['some-url']

        def parse(self, response):
            uls = response.xpath('//div[@id="someID"]//ul')
            for ul in uls:
                url = ul.xpath('.//li[1]/a/@href').extract()[0]
                loader = MyLoader(MyItem(), ul)
                loader.add_xpath('item1', './/li[1]/a/text()')
                loader.add_value('item_url', url)
                request = scrapy.Request(url, callback=self.parse_more)
                request.meta['item'] = loader.load_item()
                yield request

        def parse_more(self, response):
            loader = MyLoader(response.meta['item'], response=response)
            item_list = response.css('.nav-buttons.someclass').xpath('.//a/img/@alt').extract()
            loader.add_xpath('item_address', '//address//div[@class="address-info"]/text()')
            loader.add_value('item_list', item_list)
            #import pdb; pdb.set_trace()
            if loader.get_output_value('item_address') == "some address":
                 loader.add_value('address_code', 'FR')
            yield loader.load_item()

In pdb, for example, if we inspect a loader instance

    (pdb) loader.load_item()
    {'item_address': 'someval', ....}
    (pdb) type(loader.get_output_value('item_address'))
    <type: Nonetype>

As a result, the if-block is never executing.

**Comment by demelziraptor** [comment] 2015-03-10 14:47
It seems to be caused by populating the item loader with an item.

```
ipdb> mil = MyItemLoader()
ipdb> mil.add_value('TITLE', u'Cocoric\xf3')
ipdb> mil.load_item()
{'TITLE': u'Cocoric\xf3'}
ipdb> mil.get_output_value('TITLE')
u'Cocoric\xf3'

ipdb> mil = MyItemLoader(item={'TITLE': u'Cocoric\xf3'})
ipdb> mil.load_item()
{'TITLE': u'Cocoric\xf3'}
ipdb> mil.get_output_value('TITLE')
```

**Comment by nramirezuy** [comment] 2015-03-10 20:24
That one is the right behavior, `get_output_value` isn't supposed to access the item.

**Comment by demelziraptor** [comment] 2015-03-11 14:23
@nramirezuy I didn't realise that behaviour - why is that?

**Comment by nramirezuy** [comment] 2015-03-11 15:01
@demelziraptor 

Documentation:
```
get_output_value(field_name)

    Return the collected values parsed using the output processor, for the given field. This method doesn’t populate or modify the item at all.
```

The item contents were never touched by `output processor` of this instance. Doesn't make to much sense to access the item via ItemLoader :confused:

**Comment by redapple** [comment] 2016-09-14 12:58
If I'm not mistaken, this is a duplicate of https://github.com/scrapy/scrapy/issues/964
and it doesn't like like it's going to be fixed since the behaviour matches the docs and intention of `get_output_value`

**Comment by redapple** [comment] 2016-09-16 10:06
Marking as duplicate of #614
Unlikely to get fixed.

**Closed by redapple** 2016-09-16 10:06 UTC
