### ISSUE TITLE
Chunked decoder in 'CHUNK_LENGTH' state, still expecting more data to get to 'FINISHED' state

### ISSUE THREAD

**Issue by duangy** [scrapy/scrapy#2413] opened 2016-11-25 06:23 UTC
Traceback (most recent call last):
  File "/home/env/lib/python3.4/site-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/env/lib/python3.4/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/env/lib/python3.4/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: Chunked decoder in 'CHUNK_LENGTH' state, still expecting more data to get to 'FINISHED' state.>]

Did Anyone meet the same problem， and have any solution?

**Comment by redapple** [comment] 2016-11-30 13:15
Hi @duangy , I don't think this has been reported before.
Is it systematic? can you provide some sample code reproducing the issue?

**Comment by redapple** [comment] 2017-01-03 12:35
Hi @duangy , do you have any updates on this issue?

**Comment by rolando** [comment] 2017-02-28 23:22
This is related to https://github.com/scrapy/scrapy/issues/2586

**Comment by kmike** [comment] 2017-03-01 17:37
@rolando it should be fixed by https://github.com/scrapy/scrapy/pull/2590, right?

**Comment by rolando** [comment] 2017-03-01 17:53
@kmike yes, this is the case of the broken chunked response.

**Closed** 2017-03-01 17:54 UTC
Labels: http, insufficient info

**Comment by hcoura** [comment] 2017-05-29 19:34
I don't know if it is related, but I am commenting here due to the error been the same.
The example is on the repo below, it only happens when I have a USER_AGENT set.

https://github.com/hcoura/forbes_scrapy_error

Although I manage to get my production code working through overriding the request header when crawling forbes it felt kinda odd, so I decided to share

**Comment by kmike** [comment] 2017-05-29 19:39
@hcoura what Scrapy version are you using? Scrapy 1.4 got an option to process responses which raises these errors, instead of logging an exception; to use this feature set ``DOWNLOAD_FAIL_ON_DATALOSS = False`` in your settings.py (see https://doc.scrapy.org/en/latest/topics/settings.html#std:setting-DOWNLOAD_FAIL_ON_DATALOSS). By default the behavior is the same as before, ``DOWNLOAD_FAIL_ON_DATALOSS`` must be disabled explicitly.

**Comment by hcoura** [comment] 2017-05-29 19:47
I had just updated to 1.4 and didn't see this config, indeed it fixes the error message.
I needed to reset the User-Agent regardless to crawl the website but I guess it's probably unrelated.

Thanks for the fast response tho.
