### ISSUE TITLE
How to get all the items (via Signal API)

### ISSUE THREAD

**Issue by lolobosse** [scrapy/scrapy#3104] opened 2018-01-31 18:46 UTC
Hello there,

I wrote the following code:

```python
 process = CrawlerProcess()
 results = []

 def crawler_results(parse_result):
      results.append(parse_result)

 # The line stuff are some params, not interesting ;)
 process.crawl(BASpider, self.server, line[0], line[2], line[1])
 for p in process.crawlers:
     p.signals.connect(crawler_results, signal=scrapy.signals.item_dropped)
 process.start()
```

But the method `crawler_results` is never triggered and I do not understand why. Is it not supposed to work like this? (I mean, it's not working with `item_scrapped` or `engine_started` either) **I just get no events triggered**

Else, how would your retrieve the items of a spider with CrawlerProcess? (having a pipe is not something handy because I need to send all the data at once).

**Comment by cathalgarvey** [comment] 2018-02-06 14:29
Hi @lolobosse - Are you trying to collect items that are [dropped by a pipeline](https://scrapy.readthedocs.io/en/latest/topics/signals.html#scrapy.signals.item_dropped)? Because it sounds like you are not using Pipelines, is that correct?

It sounds like your requirement (collect everything, then send it all at once at the end of the crawl) might be better solved using a custom exporter - you can see the built-in examples [here](https://github.com/scrapy/scrapy/blob/master/scrapy/exporters.py). Your exporter might simply collect all the items into an in-memory datastructure and then use the `finish_exporting` method to pitch them off however you need. Or, you could write to a file and then send the file at the end.

Hope that helps?

**Comment by kmike** [comment] 2018-02-08 11:00
Hey @lolobosse! I can't reproduce the issue. The following script works for me, i.e. it prints results:

```py
# -*- coding: utf-8 -*-
import scrapy
import scrapy.signals
from scrapy.crawler import CrawlerProcess


class BASpider(scrapy.Spider):
    name = 'ba'
    start_urls = ['http://example.com']

    def parse(self, response):
        yield {'url': response.url}


process = CrawlerProcess()
results = []

def crawler_results(item, response, spider):
    results.append(item)
    print(results)

# The line stuff are some params, not interesting ;)
process.crawl(BASpider)
for p in process.crawlers:
    p.signals.connect(crawler_results, signal=scrapy.signals.item_scraped)

process.start()
``` 

Maybe the problem is that you're not using a right signature for a signal handler - see item_dropped argument names here: https://doc.scrapy.org/en/latest/topics/signals.html#item-dropped. Note that you must use the same argument names as in docs, because they are not passed as keyword arguments.

**Comment by lolobosse** [comment] 2018-02-08 21:09
@kmike Oh that last point may be true. I'll check! Thanks a lot for your answer!

I didn't even know that it was possible to do such a thing:
> they are not passed as keyword arguments

**Comment by kmike** [comment] 2018-02-08 21:11
sorry, I meant they *are* passed as keyword arguments, they are not passed as positional arguments :)

**Comment by lolobosse** [comment] 2018-02-08 21:12
@cathalgarvey Thanks for your message. No I do not use any pipelines because I just want to retrieve the items on the fly to send **easily** to another server.

The idea of the customer exporter is very elegant 🙏 but might be overkill if it works with the signal processing as @kmike says (I need to check though).

**Comment by kmike** [comment] 2018-02-08 22:08
@lolobosse just FYI: pipelines provide one feature which may be useful (heh, or not) in your case: process_item method can return Deferred. 

What it means is that you can wrap this method in `@inlineCallbacks` decorator and use something like [treq](http://treq.readthedocs.io/en/release-17.8.0/index.html) inside in order to upload results to a remote server in async way. I can't find a good example now. There is an example with Deferreds in https://doc.scrapy.org/en/latest/topics/item-pipeline.html#take-screenshot-of-item, but this code can be made more succinct and easy to read. 

If you want to do the same in a signal handler, you may have to start a background thread - otherwise you'll be doing blocking requests, i.e. when you're sending data to your server, Scrapy stops all other activity - downloads, etc.

**Comment by kmike** [comment] 2018-02-08 22:12
It could look like this (untested!):

```py
from twisted.internet.defer import inlineCallbacks

class UploadingPipeine:
    @inlineCallbacks
    def process_item(self, item):
        body = json.dumps(item).encode('ascii')    
        yield treq.post('http://my-server/api', body)

```

**Comment by kmike** [comment] 2018-02-12 22:36
@lolobosse can we close this issue? Was it an issue with signal argument names?

**Closed** 2018-02-18 23:33 UTC
