### ISSUE TITLE
Revise documentation about odd-numbered versions

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2232] opened 2016-09-13 12:23 UTC
[Versioning and API Stability](http://doc.scrapy.org/en/latest/versioning.html) states:

> Scrapy uses the odd-numbered versions for development releases.
> (...) Even Bs will be stable branches, and odd Bs will be development.

I believe this is not true anymore starting with 1.1, 1.1 being the current recommended stable version.

**Comment by kmike** [comment] 2016-09-13 13:48
I think it is a duplicate of https://github.com/scrapy/scrapy/issues/1317.

**Comment by redapple** [comment] 2016-09-13 13:52
oh @kmike , I missed that one.

**Closed** 2016-09-13 13:55 UTC
Labels: discuss, docs
