### ISSUE TITLE
Misleading information in scrapy

### ISSUE THREAD

**Issue by csalazar** [scrapy/scrapy#2719] opened 2017-04-27 12:48 UTC
Hi guys, I want to notify three misleading issues in scrapy information. 

First one, when a site sets two cookies, `response.headers` shows the key `Set-Cookie` with the data of the last key as a string. 

```python
{
    'Set-Cookie':` 'laravel_session=...; expires=Thu, 27-Apr-2017 14:18:16 GMT; Max-Age=7200; path=/; httponly',
    [...]
}
```

However, I can use `response.headers.getlist('Set-Cookie')` to get both two cookies, but I think the information returned by `response.headers` is misleading since it shows the value as a string and not as a list. It's rational to think that due to dictionary nature when there are two keys `Set-Cookie` the last will override the former one, then people will guess it's a problem of Scrapy handling cookies.

The second issue is that `custom_settings` in a spider won't be shown in the list of `Overriden settings` in scrapy log. I've created a vanilla project and with this spider as example:

```python
import scrapy


class ExampleSpider(scrapy.Spider):
    name = 'example'
    allowed_domains = ['example.com']
    start_urls = ['http://example.com/']
    custom_settings = {
        'COOKIES_ENABLED': False
    }

    def parse(self, response):
        pass
```

When I run the spider, the output is:

```
2017-04-27 09:33:42 [scrapy.utils.log] INFO: Scrapy 1.3.2 started (bot: set)
2017-04-27 09:33:42 [scrapy.utils.log] INFO: Overridden settings: {'BOT_NAME': 'set', 'NEWSPIDER_MODULE': 'set.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['set.spiders']}
```

`COOKIES_ENABLED` doesn't appears on the list but it's actually `False` in the logic, then it's just an information issue. I was in a project where `COOKIES_ENABLED=False` was set in `settings.py`, then when I set `COOKIES_ENABLED=True` in a spider it continued to show `COOKIES_ENABLED=False` in the spider log, making a confusion if `custom_settings` were already taken in consideration or not.

The last one is that I'm using master branch, with version `1.3.3` already released and `scrapy version` command shows that I'm using `1.3.2`.

I could make a pull request, just let me know if there's some technical reason of that behavior in any of the three issues.

--

`scrapy version -v` output: 

```
$ scrapy version -v
Scrapy    : 1.3.2
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23) - [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2k  26 Jan 2017)
Platform  : Linux-4.4.0-75-generic-x86_64-with-debian-stretch-sid
```

**Comment by kmike** [comment] 2017-04-27 21:11
Hey @csalazar,

1. It seems to be an issue with IPython. Both `repr(headers)` and `str(headers)` show lists, print(headers) show list values for me, and entering 'h' in a regular Python console shows a list value. I can only reproduce it with IPython. It looks like an IPython bug. It can be fixed this by providing a custom `__repr__` to CaselessDict, but I'm not sure it is a good solution.

2. Custom settings issue is discussed here: https://github.com/scrapy/scrapy/issues/1343.

3. Sorry, I can't reproduce it. Are you sure `scrapy` command is using Scrapy from `master` branch? Maybe versions are messed up with both conda and non-conda installed packages in play.

**Comment by redapple** [comment] 2017-05-04 12:13
@csalazar , @kmike , regarding point 3)
I can also see `scrapy version -v` showing 1.3.2 when using master branch.
And indeed, [master branch has `scrapy/VERSION` with 1.3.2](https://github.com/scrapy/scrapy/blob/master/scrapy/VERSION). This is from when 1.3.x and master diverged. Master branch should really say something like 1.4.0.dev

**Comment by Gallaecio** [comment] 2019-07-09 11:02
Closing since 1 is not a Scrapy issue, 2 is handled in #1343 and 3 seems solved.

**Closed by Gallaecio** 2019-07-09 11:02 UTC
