### ISSUE TITLE
fetch fails to update scrapy objects in scrapy shell.

### ISSUE THREAD

**Issue by bagratte** [scrapy/scrapy#1176] opened 2015-04-19 12:27 UTC
<pre>
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

<b>C:\Users\bagratte>scrapy shell</b>
2015-04-19 16:15:13+0400 [scrapy] INFO: Scrapy 0.24.5 started (bot: scrapybot)
2015-04-19 16:15:13+0400 [scrapy] INFO: Optional features available: ssl, http11
, django
2015-04-19 16:15:13+0400 [scrapy] INFO: Overridden settings: {'LOGSTATS_INTERVAL
': 0}
2015-04-19 16:15:13+0400 [scrapy] INFO: Enabled extensions: TelnetConsole, Close
Spider, WebService, CoreStats, SpiderState
2015-04-19 16:15:13+0400 [scrapy] INFO: Enabled downloader middlewares: HttpAuth
Middleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, Def
aultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, Redirec
tMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-04-19 16:15:13+0400 [scrapy] INFO: Enabled spider middlewares: HttpErrorMid
dleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddlew
are
2015-04-19 16:15:13+0400 [scrapy] INFO: Enabled item pipelines:
2015-04-19 16:15:13+0400 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6
026
2015-04-19 16:15:13+0400 [scrapy] DEBUG: Web service listening on 127.0.0.1:6083

[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x0000000004C57C88>
[s]   item       {}
[s]   settings   <scrapy.settings.Settings object at 0x0000000002271D68>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser

<b>In [1]: fetch('http://scrapy.org/')</b>
2015-04-19 16:15:40+0400 [default] INFO: Spider opened
2015-04-19 16:15:41+0400 [default] DEBUG: Redirecting (302) to <GET http://scrap
y.org/> from <GET http://scrapy.org/>
2015-04-19 16:15:41+0400 [default] DEBUG: Crawled (200) <GET http://scrapy.org/>
 (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x0000000004C57C88>
[s]   item       {}
[s]   request    <GET http://scrapy.org/>
[s]   response   <200 http://scrapy.org/>
[s]   settings   <scrapy.settings.Settings object at 0x0000000002271D68>
[s]   spider     <Spider 'default' at 0x63eaba8>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser

<b>In [2]: response

In [3]: response is None
Out[3]: True</b>

In [4]:
Do you really want to exit ([y]/n)?

<b>C:\Users\bagratte>scrapy shell http://scrapy.org/</b>
2015-04-19 16:16:05+0400 [scrapy] INFO: Scrapy 0.24.5 started (bot: scrapybot)
2015-04-19 16:16:05+0400 [scrapy] INFO: Optional features available: ssl, http11
, django
2015-04-19 16:16:05+0400 [scrapy] INFO: Overridden settings: {'LOGSTATS_INTERVAL
': 0}
2015-04-19 16:16:05+0400 [scrapy] INFO: Enabled extensions: TelnetConsole, Close
Spider, WebService, CoreStats, SpiderState
2015-04-19 16:16:05+0400 [scrapy] INFO: Enabled downloader middlewares: HttpAuth
Middleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, Def
aultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, Redirec
tMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-04-19 16:16:05+0400 [scrapy] INFO: Enabled spider middlewares: HttpErrorMid
dleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddlew
are
2015-04-19 16:16:05+0400 [scrapy] INFO: Enabled item pipelines:
2015-04-19 16:16:05+0400 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6
026
2015-04-19 16:16:05+0400 [scrapy] DEBUG: Web service listening on 127.0.0.1:6083

2015-04-19 16:16:05+0400 [default] INFO: Spider opened
2015-04-19 16:16:06+0400 [default] DEBUG: Crawled (200) <GET http://scrapy.org/>
 (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x0000000004C53278>
[s]   item       {}
[s]   request    <GET http://scrapy.org/>
[s]   response   <200 http://scrapy.org/>
[s]   settings   <scrapy.settings.Settings object at 0x00000000046DCDA0>
[s]   spider     <Spider 'default' at 0x513d4e0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser

<b>In [1]: response
Out[1]: <200 http://scrapy.org/></b>

<b>In [2]: fetch('http://www.python.org/')</b>
2015-04-19 16:16:41+0400 [default] DEBUG: Redirecting (301) to <GET https://www.
python.org/> from <GET http://www.python.org/>
2015-04-19 16:16:41+0400 [default] DEBUG: Crawled (200) <GET https://www.python.
org/> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x0000000004C53278>
[s]   item       {}
[s]   request    <GET http://www.python.org/>
[s]   response   <200 https://www.python.org/>
[s]   settings   <scrapy.settings.Settings object at 0x00000000046DCDA0>
[s]   spider     <Spider 'default' at 0x513d4e0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser

<b>In [3]: response
Out[3]: <200 http://scrapy.org/></b>

In [4]:
Do you really want to exit ([y]/n)?

C:\Users\bagratte>scrapy version -v
Scrapy  : 0.24.5
lxml    : 3.4.2.0
libxml2 : 2.9.0
Twisted : 15.1.0
Python  : 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: Windows-8-6.2.9200

C:\Users\bagratte>ipython --version
3.1.0

C:\Users\bagratte>
</pre>

is this an expected behavior?

**Comment by kmike** [comment] 2015-04-19 18:17
Likely it was fixed by https://github.com/scrapy/scrapy/pull/856, but the fix is not backported to 0.24.x branch. Could you try reproduce it using Scrapy master?

//cc @dangra - what about backporting https://github.com/scrapy/scrapy/pull/856 for 0.24.6?

**Comment by dangra** [comment] 2015-04-20 04:29
+1 I am surprised #856 wasn't backported

**Comment by dangra** [comment] 2015-04-20 04:52
v0.24.6 including the fixes for this issue is availble on pypi since today.

**Closed by dangra** 2015-04-20 04:52 UTC

**Comment by bagratte** [comment] 2015-04-20 10:08
0.24.6 shell seems to be working fine. thanks.
