### ISSUE TITLE
It seems like the last callback is executed for only one url but as many times as the total number of URLs

### ISSUE THREAD

**Issue by teddb** [scrapy/scrapy#1416] opened 2015-08-08 23:14 UTC
The following post had been brought up previously, but can someone post an explanation?

-------------------
Very tricky problem that I don't know how to debug. I have a spider which is a 3-level deep:

    def parse(self, response):
        # some treatment
        # a loop
             request = scrapy.Request(url=<calculated_url>, callback=parseChapter)
             request.meta['item'] = # a dictionary containing some data of the just parsed page
             yield request

    def parseChapter(self, response):
        # some treatment
        # a loop
             request = scrapy.Request(url=<calculated_url>, callback=parseCategory)
             request.meta['item'] = # a dictionary containing some data of the just parsed page
             # print request.meta['item'] is good and different in every iteration
             yield request

    def parseCategory(self, response):
        # print response.meta['item'] is not good because it displays the same value many times
        # for every new call of parseChapter, meta['item'] received is always the same
        # some treatment

The weird thing is that the passed dictionary in the meta of the request is the same in parseCategory, and response.url into parseCateogry is fine.
This problem I'm talking about happens only in the callback parseCategory, it does work well in parseChapter (passed meta is good and different for every new call)

Can you help me out with this?

**Comment by dangra** [comment] 2015-08-09 03:05
Dupe of #1257 

Short explanation: You are sharing the same item instead of copying it on every loop iteration, each request's meta carries a different item than following callbacks can mutate individually.

Check printing `id(item)` too, if it prints always the same number then the bug is in your code.

**Closed by dangra** 2015-08-09 03:05 UTC

**Comment by dangra** [comment] 2015-08-09 03:06
I closed this issue because it is not a bug, for general support questions use mailing lists https://groups.google.com/forum/#!forum/scrapy-users

**Comment by teddb** [comment] 2015-08-13 02:22
Still not sure if this is correct, but it solved my problem for now:

Change request.meta['item'] = item to request.meta['item'] = item.copy()
