### ISSUE TITLE
pip install scrapy

### ISSUE THREAD

**Issue by gbell27** [scrapy/scrapy#3752] opened 2019-04-20 22:25 UTC
You need first "pip install incremental" due to a misspelling in the lines for the installation of dependencies.

**Comment by noahshpak** [comment] 2019-04-23 22:19
I don't have this problem in python3.6

**Comment by gbell27** [comment] 2019-04-24 00:06
I first tried on 2.7 but went the same on 3.6 using the cached version of the package which wasn’t correctly installed. I saw that it was a common error but I solved it differently from the solutions written by someone else on stackoverflow and others. The error was python setup.py egg_info failed with error 1 described in github.com/palantir/python-language-server/issues/370

**Comment by Gallaecio** [comment] 2019-04-26 09:59
@gbell27 May this be a duplicate of #2808?

**Comment by Gallaecio** [comment] 2019-08-19 15:31
Closing due to a lack of feedback.

**Closed by Gallaecio** 2019-08-19 15:31 UTC
