### ISSUE TITLE
start_requests() not taking the Dynamic Variables

### ISSUE THREAD

**Issue by kgrvamsi** [scrapy/scrapy#1931] opened 2016-04-13 21:03 UTC
I'm being trying to iterate a loop of urls in which i have three layers of scraping done

1)Scrapy the first URL and get the respective data
2)Based upon the data use that in one of the for loop range
3)Run the Scraping and fetch new urls and append it to a variable and then again parse them

Here is the example code that i'm looking out for

```
from scrapy.spider import BaseSpider
from scrapy.http import Request

class TestSpider(BaseSpider):
    name = "test_spider"
    allowed_domains=["amazon.com"]
    some_value=0
    data=[]
    def start_requests(self):
        yield Request(first-url,callback=self.parse)
       ''' this is the place the some_value is not replaced with the new value '''
        for i in range(2, some_value):
            url = 'http://www.amazon.com/dp/%i/' % i
            yield Request(url,callback=self.somefunction)
        
         for site in data:
           yield Request(site,callback=self.somefunction)

    def parse(self, response):
        '''does nothing'''
        if self.some_value == 0:
              self.some_value = int(response.xpath(somexpath).extract())
        url =  response.xpath(somexpath).extract()[0]
        self.data.append(str(url))
        print 'parse'

**Comment by kmike** [comment] 2016-04-13 21:47
Hey @kgrvamsi,

Scrapy is async, so when your `for i in range(2, some_value):` loop is executed it is *guaranted* `parse` method is not called yet; it will be only called when the response for the first request will be received. This is by design.

To execute a loop only when `parse` is executed move the loop inside `parse` method.

I don't think this is a Scrapy bug, so I'm closing this ticket. We're using http://stackoverflow.com/ with 'scrapy' tag as a support channel; you may get a better support there.

**Closed by kmike** 2016-04-13 21:47 UTC

**Comment by collin0** [comment] 2018-03-16 16:43
hi @kgrvamsi,
i'm new to scrapy world and i want to do the same thing you was tryng to do, did you figure out some way to it ?, i'll be so grateful if you can help me.
thank you
