### ISSUE TITLE
HTTP 2 support

### ISSUE THREAD

**Issue by povilasb** [scrapy/scrapy#1854] opened 2016-03-09 11:00 UTC
I peeked at the docs, at the issues but couldn't find any info about HTTP 2 support.

Does `scrapy` support it?

**Comment by redapple** [comment] 2016-03-09 11:04
@povilasb ,
no, scrapy only supports HTTP/1.0 and HTTP/1.1 (we currently use `twisted.web.client.Agent`)

**Comment by pawelmhm** [comment] 2016-03-21 08:07
Looking into Twisted I found out there is work on adding HTTP 2 support to Twisted.web: https://twistedmatrix.com/trac/ticket/7460 Once this is merged upstream do you think Scrapy should also follow suit and add HTTP 2 support?

**Comment by mguerreiro** [comment] 2017-01-18 17:11
Up, this has been merged :)

**Comment by kmike** [comment] 2017-01-18 18:19
It seems the ticket is for HTTP2 server support, not for a client. 
There is an example of twisted http2 client in python-hyper docs: https://python-hyper.org/projects/h2/en/stable/twisted-post-example.html

**Comment by pawelmhm** [comment] 2017-01-19 15:10
it seems like work on Twisted client is not making much progress now, but this example you linked @kmike doesn't look terribly complicated so maybe we could just add h2 as Scrapy requirement and write our own HTTP2 Twisted-Scrapy client?

**Comment by AnshulMalik** [comment] 2017-03-06 19:37
Hi, 
I am a student from India, planning to participate in GSoC this year. There was a project regarding "New HTTP/1.1 download handler", this was required because some issues with twisted API, but they have recently resolved those issues (@redapple told me). 
Then I realized that scrapy doesn't have support for HTTP/2 so why not choose this as GSoC project.

I have also done a bit of research about twisted implementing HTTP/2, python-hyper which is nice implementation of HTTP/2, twisted also uses h2 for supportng for HTTP2.
Currently, Twisted only have support for HTTP2 on server side ( @kmike   )

As @pawelmhm mentioned, one way is to use h2 and start the work. Since we don't know when Twisted will add support for HTTP2 client, so we should write our client.

I am seeking your reviews for this idea, If I should do it, what things should I keep in mind, where can I find more info about HTTP2. And most important, is this idea worth? (Twisted might add support for HTTP2 in future)

**Comment by alexeyqu** [comment] 2018-03-10 10:55
Hi,
I'm a 5th year CS student from MIPT, Russia, planning to participate in GSoC this year.
I write in Python for over 3 years and teach it at MIPT, more detailed CV is [here](https://alexeyqu.github.io/).

This year, the HTTP/2 support is mentioned in the [ideas list](http://gsoc2018.scrapinghub.com/ideas/#download-handler).
On the low level, Scrapy uses twisted module for HTTP connections.
After looking at [Twisted](https://github.com/twisted/twisted) and [Hyper](https://github.com/Lukasa/hyper) repos, I realized that in terms of HTTP/2 support on the client side, nothing has changed since @AnshulMalik mentioned it here (except for [this](https://gist.github.com/Lukasa/57bd9a7332991821329d) gist with simple HTTP/2 client, but it was around for a long time).
That, obviously, give some points to the "use h2 and start the work" approach.

I wonder, is there a reason for silence on this topic (both here and in Twisted)? (I don't have any experience with HTTP/2 internals yet, so maybe I'm missing something crucial) 
I've just started familiarizing myself with Scrapy codebase, could you suggest some good first bugs to fix?

**Comment by kmike** [comment] 2018-03-12 12:17
Hey @alexeyqu! That's a feature which could make Scrapy more resource-efficient in some specific cases, not a bug which affects day-to-day work - probably that's the reason it gets less attention.

**Comment by somestupidpersonLA** [comment] 2020-01-03 20:43
Have the same issue, thought to circumvent by using httpx

**Comment by sakshamb2113** [comment] 2020-02-27 20:16
@Gallaecio I am interested in this issue.Can I work on this ?

**Comment by adityaa30** [comment] 2020-02-28 13:11
@Gallaecio @kmike Hey. I am a 3rd year CS student from NITT, India. I am planning to participate in GSOC this year. 
I want to work on this issue as my GSOC project. Can you please send some resources on this to refer?

**Comment by Gallaecio** [comment] 2020-03-12 09:30
@adityaa30 Sounds good to me :slightly_smiling_face:

**Comment by adityaa30** [comment] 2020-03-12 16:43
@Gallaecio Thanks for the reply. I have been understanding the workflow of [http11.py](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/handlers/http11.py) and wanted to know what are the key features that I should be focusing on?

**Comment by Gallaecio** [comment] 2020-03-12 19:10
Well, I guess it would be best to start by getting a working implementation, something that allows using HTTP/2.

When that works, the next step would be to add support for what our HTTP 1.1 implementation currently supports. Mostly that the settings that may be used to modify how HTTP 1.1 works also work similarly in HTTP/2 (where possible).

I think that would make the project complete. Extra goals may involve exposing additional features of HTTP/2 through settings, if they can be useful for web scraping. I wonder, for example, if it would make sense to allow users to limit concurrent requests per TCP connection; I’m not sure, though.

**Comment by adityaa30** [comment] 2020-03-13 10:57
@Gallaecio Thanks. I am working on a demo implementation now.

**Comment by adityaa30** [comment] 2020-03-23 12:13
@Gallaecio @wRAR I have prepared a draft of my application on Google docs
[https://docs.google.com/document/d/1AUjXgK9u1QcxqdjJxQObecgHQEKZfzO3U96ivBvblTw/edit?usp=sharing](https://docs.google.com/document/d/1AUjXgK9u1QcxqdjJxQObecgHQEKZfzO3U96ivBvblTw/edit?usp=sharing)

I would be happy to get a feedback about the proposal before submitting it.

**Comment by Gallaecio** [comment] 2020-03-23 18:10
The proposal looks great to me, very detailed :+1:

One topic that it does not cover, though, and one that I think may be specially important once there is HTTP/2 support in Scrapy, is how users will be able to configure which protocol is used. At the moment we have settings like `DOWNLOAD_HANDLERS`, `DOWNLOADER_HTTPCLIENTFACTORY`, `DOWNLOADER_CLIENTCONTEXTFACTORY`, `DOWNLOADER_CLIENT_TLS_*`. It would be great if you could think how HTTP/2 support fits in the picture, and if we need to make changes here (e.g. settings value changes, new settings, etc.) to support scenarios such as using HTTP/2 when possible but falling back to 1.1 otherwise, or the opposite.

**Comment by adityaa30** [comment] 2020-03-23 21:59
@Gallaecio Thanks a lot for the review.
> HTTP/2 support in Scrapy, is how users will be able to configure which protocol is used.

I will work on this now and update my proposal.

**Comment by adityaa30** [comment] 2020-03-29 06:24
@Gallaecio @wRAR I have updated my proposal. If you wouldn't mind taking another look, I would like to get some more feedback. [Link](https://docs.google.com/document/d/1AUjXgK9u1QcxqdjJxQObecgHQEKZfzO3U96ivBvblTw/edit?usp=sharing) to the proposal remains the same.

**Comment by Gallaecio** [comment] 2020-03-29 17:51
I cannot think of more feedback at the moment. It looks really thought-out and well put. :+1:

**Comment by adityaa30** [comment] 2020-03-30 05:01
@Gallaecio Thanks a lot.

**Comment by wRAR** [comment] 2020-03-30 18:24
I like the proposal @adityaa30 , thank you.

**Comment by adityaa30** [comment] 2020-04-01 23:13
@wRAR Thanks you! 🙂

**Comment by jseyfert** [comment] 2020-12-09 02:13
> Hey @kmike, I'm afraid I disagree. I'm seeing an increase in websites (using a specific vendor) that detect bot traffic based on HTTP2/HTTP1.1 version compared to what's the expected default from your user agent. While I do understand that that does not make it a priority for the Twisted team, I'm sure it has a significant impact for a lot of scrapy users.

Hi, @Glennvd 
I have encountered multiple sites that blocked scrapy due to HTTP1.1, but i am finding they are only identifying my spider due to scrapy automatically capitalizing the keys of the headers. I have been able to use a workaround that has worked 100% of the time so far.

**example**
This is what the site expects:
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,hi;q=0.8,pt;q=0.7

And this is what scrapy sends(even if you make them lowercase in the spider):
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,hi;q=0.8,pt;q=0.7

This seems to be a workaround to keep the keys lowercase:
```
headers={
    "":"accept-encoding: gzip, deflate, br",
    "":"accept-language: en-US,en;q=0.9,hi;q=0.8,pt;q=0.7",
},
```

I hope this helps someone:)

**Comment by GeorgeA92** [comment] 2020-12-09 09:13
Hi, @jseyfert.

> I have encountered multiple sites that blocked scrapy due to HTTP1.1, but i am finding they are only identifying my spider due to scrapy automatically capitalizing the keys of the headers.

It is related to #2711

**Closed** 2021-03-18 21:18 UTC
Labels: enhancement

**Comment by ikumar5am** [comment] 2023-12-04 07:47
HTTP2 experimental support is now added to Scrapy, checkout https://docs.scrapy.org/en/latest/topics/settings.html
