### ISSUE TITLE
USER_AGENT gets the spider stuck at "Listening to telnet console"

### ISSUE THREAD

**Issue by YoussefRamadan98** [scrapy/scrapy#5030] opened 2021-03-06 18:48 UTC
### Description

I have a spider for crawling product related data from tesco.com. The spider is deployed on Ubuntu 20.4 and was working just fine until it suddenly stopped and would not crawl for some reason. At first, I thought maybe I got banned by Tesco but using a simple curl command proved that I wasn't. After numerous debugging trials I removed the user agent I specified in the settings.py, which was previously working:

```Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36```

The spider then started working again. I thought maybe for some reason this user agent was not functioning so I tried a curl command with the same user agent and it worked. I then proceeded to changing the user agent in settings.py to different ones but still the spider was getting stuck on the "listening to telnet console".

**Expected behavior:** Spider to crawl the specified url

**Actual behavior:** Spider gets stuck on "listening to telnet console".

**Reproduces how often:** Everytime I specify a USER_AGENT in settings.py

### Versions

```
Scrapy       : 2.4.0
lxml         : 4.6.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.8.5 (default, Jan 27 2021, 15:41:15) - [GCC 9.3.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021)
cryptography : 3.4.6
Platform     : Linux-5.8.0-44-generic-x86_64-with-glibc2.29
```

**Comment by wRAR** [comment] 2021-03-07 18:49
"Spider gets stuck on "listening to telnet console"." just means it gets stuck on downloading the first URL, possibly because of the antibot logic (note that antibots can check not just the UA but a combination of identifying factors). As this is not a Scrapy problem but a problem specific to your settings and the website you are crawling i'm closing this.

**Closed by wRAR** 2021-03-07 18:49 UTC

**Comment by YoussefRamadan98** [comment] 2021-03-07 18:53
Yes I believed so as well in the beginning but as I mentioned, removing the USER_AGENT from settings.py allowed the crawler to work normally, which is unexpected if it is just simply anti bot logic. The problem is that the spider does not work when I specify a user agent as using the scrapy default allow it to work normally.

**Comment by wRAR** [comment] 2021-03-07 18:59
> which is unexpected if it is just simply anti bot logic.

Not that unexpected.

> The problem is that the spider does not work when I specify a user agent as using the scrapy default allow it to work normally.

The problem is that the website doesn't respond with these specific settings. If you think this is a Scrapy problem you'll need a justification.

**Comment by YoussefRamadan98** [comment] 2021-03-07 19:05
The reason I believe it is a Scrapy problem is that a simple commenting out of the USER_AGENT (i.e using the default Scrapy user agent) in settings.py and using the same exact settings makes the spider crawl without any issues on the same website that it was getting stuck on.

**Comment by wRAR** [comment] 2021-03-07 19:11
OK, please provide a minimal reproducible example for this Scrapy issue.

**Comment by YoussefRamadan98** [comment] 2021-03-07 22:23
When running 
```
scrapy shell -s USER_AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36' 'www.tesco.com'
```
the spider gets stuck and does not crawl. However, if I simply run

```
scrapy shell 'www.tesco.com'
```
the spider crawls without any issues. it is worth noting that I am not using my project settings. These commands were run in a clean and newly created  virtual environment isolated from my project's virtual environment.

**Comment by wRAR** [comment] 2021-03-08 07:23
> the spider gets stuck and does not crawl.

It doesn't for me. This is not a Scrapy problem.
